In [1]:
import pandas as pd
import tweepy
import re

MU=pd.read_csv(open('MU-geo.csv','rU'),sep=',')
MC=pd.read_csv(open('MC-geo.csv','rU'),sep=',')

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: 'U' mode is deprecated
  """
/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:6: DeprecationWarning: 'U' mode is deprecated

In [3]:
#positive

MUp=MU[MU['sentiment']>0]
MUp=MUp.reset_index(drop=True)
MCp=MC[MC['sentiment']>0]
MCp=MCp.reset_index(drop=True)

In [4]:
#negative

MUn=MU[MU['sentiment']<0]
MUn=MUn.reset_index(drop=True)
MCn=MC[MC['sentiment']<0]
MCn=MCn.reset_index(drop=True)

In [7]:
print(len(MU))
print(len(MUn))
print(len(MC))
print(len(MCn))

100129
9563
95036
9365

In [57]:
#all
print(MUn.shape)
print(MCn.shape)

(6730, 14)
(6755, 14)

In [174]:
MCp=MCp.drop('geo',axis=1)
MUp=MUp.drop('geo',axis=1)

In [56]:
MCp=MCp[MCp['location'].notnull()]
MUp=MUp[MUp['location'].notnull()]
MCn=MCn[MCn['location'].notnull()]
MUn=MUn[MUn['location'].notnull()]

In [58]:
MCn=MCn.reset_index(drop=True)
MUn=MUn.reset_index(drop=True)

In [59]:
MCn.to_csv("MCn-geo.csv",index=False,sep=',')
MUn.to_csv("MUn-geo.csv",index=False,sep=',')

In [50]:
addresses = ["380 New York St, Redlands, CA", 
             "1 World Way, Los Angeles, CA",
             "1200 Getty Center Drive, Los Angeles, CA", 
             "5905 Wilshire Boulevard, Los Angeles, CA",
             "100 Universal City Plaza, Universal City, CA 91608",
             "4800 Oak Grove Dr, Pasadena, CA 91109"]

In [51]:
from arcgis.gis import GIS
from arcgis.geocoding import get_geocoders, batch_geocode

gis = GIS('http://www.arcgis.com',"daqians123", "jxsdq123")

# use the GIS's configured geocoder
geocoder = get_geocoders(gis)[0]

In [ ]:
print("MaxBatchSize : " + str(geocoder.properties.locatorProperties.MaxBatchSize))
print("SuggestedBatchSize : " + str(geocoder.properties.locatorProperties.SuggestedBatchSize))

In [32]:
map = gis.map("London", 5)
map

In [119]:
for address in results:
    print(address['attributes']['Country'])

USA
USA
USA
USA
USA
USA

In [19]:
for i in range(2):
    try:
        add=list(MCp['location'][100*i:100*(i+1)])
        results=batch_geocode(add)
        k=0
        for a in add:
            MCp['lat'][k+100*i]=a['location']['y']
            MCp['lon'][k+100*i]=a['location']['x']
            MCp['geocode'][k+100*i]=str(a['attributes']['Country'])
            MUp['co']=True
            k+=1
            if k==99:
                print(i,a['attributes']['Country'])
    except BaseException as e:
            print(e)

Token is valid but access is denied.
User does not have permissions to access geocodeAddresses.

Token is valid but access is denied.
User does not have permissions to access geocodeAddresses.
(Error Code: 403)

Token is valid but access is denied.
User does not have permissions to access geocodeAddresses.

Token is valid but access is denied.
User does not have permissions to access geocodeAddresses.
(Error Code: 403)

In [6]:
from geopy.geocoders import ArcGIS, Nominatim, OpenCage, GoogleV3, DataBC


print('creating geocoding objects!')

arcgis = ArcGIS(timeout=1)
nominatim = Nominatim(timeout=1)
googlev3 = GoogleV3(timeout=1)
databc=DataBC(timeout=1)




# choose and order your preference for geocoders here
geocoders = [arcgis, nominatim]

def geocode(address,i):
    try:
        # try to geocode using a service
        place, (lat, lng) = geocoders[(i+1)%4].geocode(address)
        # if it returns a location
        if place != None:
            return place, lat, lng
        else:
            return 'null','null','null'
    except:
        # catch whatever errors, likely timeout, and return null values
        return 'null','null','null'

    # if all services have failed to geocode, return null values
    return 'null','null','null'

creating geocoding objects!

In [11]:
for i in range(5000):
    
    try:
        # configure this based upon your input CSV file
        place, lat, lng = geocode(MUn['location'][i],i)
        if(place!='null'):
            MUn['geocode'][i]=place
            MUn['lat'][i]=lat
            MUn['lon'][i]=lng
            MUn['co'][i]=True
        print(i,place)
    except BaseException as e:
        print(e)

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

0 X Región de Los Lagos, Chile
1 Kuka, Katsina
2 London, Greater London, England, UK
3 Pori
4 null
5 Accra, Accra Metropolis, Greater Accra
6 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
7 Glasgow, Lanarkshire, Scotland
8 null
9 Devils Elbow Rd NW, Corydon, Indiana, 47112
10 กรุงเทพมหานคร, ประเทศไทย
11 White, Pennsylvania
12 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
13 Manchester, Lancashire, England
14 Karen, Montgomery County, Texas, United States of America
15 Malaysia
16 Subang Jaya, Selangor, 47610, Malaysia
17 Diamond Bay, Arkansas
18 null
19 Greece
20 Manchester, Greater Manchester, North West England, England, UK
21 Glasgow, Lanarkshire, Scotland
22 London, Greater London, England, UK
23 Zanzibar, Mjini, Mjini Magharibi
24 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
25 Lagos, Lagos Island, Lagos
26 Nairobi, Kenya
27 Druid Hills, Georgia
28 null
29 Canaries
30 Valladolid, Castilla y León, España
31 Earth, Texas
32 NSN, Malaysia
33 Namibia
34 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
35 Malaysia
36 India
37 Kota
38 Wales, UK
39 null
40 null
41 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
42 بيروت, رأس بيروت, محافظة بيروت, لبنان
43 Kuantan, Pahang
44 Liverpool, North West England, England, UK
45 Trengganu, Terengganu
46 Manchester, Greater Manchester, North West England, England, UK
47 Notown, Stockbridge, Town of, Vermont
48 UiTM Perlis, Jalan Padang Nyu, Kampung Kubang Gajah, Perlis, 02600, Malaysia
49 COM
50 Cardiff, Wales, CF, UK
51 null
52 Enugu, Enugu North, Enugu, 400.0, Nigeria
53 Ghana
54 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
55 Nairobi
56 Kumasi, Ashanti Region, Ghana
57 IN
58 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
59 Singapore
60 Singapore, Central, 178957, Singapore
61 Gmail
62 Yorkshire, Cattaraugus County, New York, 14173, United States of America
63 Manchester, Lancashire, England
64 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
65 Negril, Westmoreland
66 London, Greater London, England, UK
67 United Kingdom
68 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
69 Abuja, Abuja Municipal, Federal Capital Territory
70 Abeokuta, Abeokuta South, Ogun, Nigeria
71 Lagos, Lagos Island, Lagos
72 Indonesia
73 Bonnybridge, Stirlingshire, Scotland
74 Nairobi, Kenya
75 New York
76 Lagos, Lagos Island, Lagos, 71510, Nigeria
77 United States
78 Kaduna, Nigeria
79 Algérie
80 Nigeria
81 Edinburgh, Midlothian, Scotland
82 Inverness, Highland, Scotland, IV1 1PJ, UK
83 West African Union
84 Mdantsane, Buffalo City Metropolitan Municipality, Eastern Cape, 5219, South Africa
85 47130
86 Lagos, Lagos Island, Lagos, 71510, Nigeria
87 Manchester, Lancashire, England
88 MUFC Ticketing and Membership Services, Bridgewater Canal Towpath, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0SZ, UK
89 Ghana
90 null
91 San Diego, California
92 UK
93 Manchester, Lancashire, England
94 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
95 United Kingdom
96 null
97 Prishtinë, Komuna e Prishtinës
98 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
99 Lagos, Lagos Island, Lagos
100 null
101 Kumasi, Kumasi Metropolitan, Ashanti
102 Portsmouth, South East, England, PO1 5QH, UK
103 Temporarium
104 null
105 Lagos, Lagos Island, Lagos
106 Nairobi, Kenya
107 Mumbai, Maharashtra
108 null
109 UK
110 Mumbai, Greater Bombay, Maharashtra, 400001, India
111 Lagos, Lagos Island, Lagos
112 New Delhi, Delhi, India
113 London, England
114 Manchester, Greater Manchester, North West England, England, UK
115 Lagos, Lagos Island, Lagos
116 Lagos, Lagos Island, Lagos, 71510, Nigeria
117 United States
118 Mumbai, Greater Bombay, Maharashtra, 400001, India
119 Worldwide
120 Lagos, Lagos Island, Lagos, 71510, Nigeria
121 Manchester, Lancashire, England
122 Chancellors, Whitworth Lane, Fallowfield, Manchester, Greater Manchester, North West England, England, M14 6NN, UK
123 Far Away
124 null
125 Home, Pennsylvania
126 Southend-on-Sea, East of England, England, UK
127 Singapore
128 대한민국
129 Manchester, Lancashire, England
130 Manchester, Greater Manchester, North West England, England, UK
131 Earth, Texas
132 Ireland
133 Sheffield, South Yorkshire, England
134 null
135 Bandung, Sumur Bandung, Bandung, Jawa Barat
136 null
137 Ig, Ljubljana
138 UK
139 Ireland
140 Linköping, Landskapet Östergötland, Östergötlands län, Götaland, 582 24, Sverige
141 Westside, Georgia
142 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
143 United Kingdom
144 Lagos, Lagos Island, Lagos, 71510, Nigeria
145 Manchester, Lancashire, England
146 Lagos, Lagos Island, Lagos, 71510, Nigeria
147 Lag, Bình Thuận
148 Bauchi, Nigeria
149 Manchester, Lancashire, England
150 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
151 Nigeria
152 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
153 Abuja, Abuja Municipal, Federal Capital Territory
154 NYC, New York, United States of America
155 Lagos, Lagos Island, Lagos
156 Lagos, Lagos Island, Lagos, 71510, Nigeria
157 Jalan Marina Bay, Miri, Division Miri, 98000, Sarawak
158 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
159 Cave, Roma
160 Cave, RM, LAZ, Italia
161 Abuja, Abuja Municipal, Federal Capital Territory
162 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
163 United States
164 null
165 Worldwide
166 Lagos, Lagos Island, Lagos, 71510, Nigeria
167 Nairobi
168 Lagos, Lagos Island, Lagos, 71510, Nigeria
169 Lagos, Lagos Island, Lagos
170 Lagos, Lagos Island, Lagos, 71510, Nigeria
171 New York
172 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
173 Aruba
174 null
175 Lancashire, England
176 London, Greater London, England, UK
177 Breaks, Virginia
178 Manchester, Greater Manchester, North West England, England, UK
179 London, England
180 Rua Abuad Faráh, Guaxupé, Microrregião São Sebastiao do Paraíso, Mesorregião Sul/Sudoeste de Minas, MG, Região Sudeste, Brasil
181 Planet Earth Water
182 Kano, Kano Municipal, Kano, PMB 3401, Nigeria
183 London, England
184 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
185 Singapore
186 Prestea, Western Region, Ghana
187 Cia
188 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
189 Le Havre, Seine-Maritime, Normandie
190 null
191 Sarawak Maritime Academy
192 Manchester, Greater Manchester, North West England, England, UK
193 London, England
194 ‏پاکستان‎
195 England
196 null
197 Constantine
198 null
199 Sunyani, Brong Ahafo
200 Ghana
201 Canary Wharf, London, England
202 Ghana
203 London, England
204 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
205 Damaturu, Yobe
206 South Africa
207 Nairobi
208 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
209 Abuja, Abuja Municipal, Federal Capital Territory
210 Manchester, Greater Manchester, North West England, England, UK
211 Soweto, Orlando West, Johannesburg, Gauteng
212 null
213 Newcastle, Tyne and Wear, England
214 Derrylin, County Fermanagh, Northern Ireland, BT92 9LA, UK
215 Lima, Provincia de Lima
216 London, Greater London, England, UK
217 London, England
218 null
219 02152
220 Newcastle upon Tyne, Tyne and Wear, North East England, England, UK
221 Newcastle upon Tyne, Tyne and Wear, England
222 Nigeria Road, Charlton, Greenwich, London, Greater London, England, SE7 7BS, UK
223 New Delhi, Connaught Place, New Delhi, Delhi
224 Serio, Microrregião das Chapadas do Alto Itapecuru, Mesorregião Leste Maranhense, MA, Região Nordeste, Brasil
225 Stockholm
226 Joe, Panta, Bong County, Liberia
227 Lincoln, Lincolnshire, England
228 India
229 Johannesburg, Gauteng
230 NG, Bristol Road South, Bournbrook, Birmingham, West Midlands Combined Authority, West Midlands, England, B29, UK
231 United Kingdom
232 Manchester, Greater Manchester, North West England, England, UK

233 Nairobi
234 Lagos, Lagos Island, Lagos, 71510, Nigeria
235 Islamabad, Islāmābād
236 The Edge Theatre & Arts Centre, Manchester Road, Chorlton-cum-Hardy, Manchester, Greater Manchester, North West England, England, M21 9JG, UK
237 Oxford, Oxfordshire, England
238 The King's Head (now a hotel), Church Street, West Ham, Newham, London, Greater London, England, E15, UK
239 Dewsbury, West Yorkshire, England
240 Красноярск, городской округ Красноярск, Красноярский край, СФО, 660000, РФ
241 Sydney, New South Wales
242 Tanzania
243 United Kingdom
244 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
245 United Kingdom
246 Enugu, Enugu North, Enugu, 400.0, Nigeria
247 Noida, Gautam Buddha Nagar, Uttar Pradesh
248 London, Greater London, England, UK
249 London, England
250 Bronze, Cape Town Ward 81, Mitchells Plain, City of Cape Town, Western Cape, 7785, South Africa
251 null
252 Singapore, Central, 178957, Singapore
253 India
254 India
255 Hood, Virginia
256 Singapore, Central, 178957, Singapore
257 Jakarta, DKI Jakarta
258 Shah Alam, Selangor, 40000, Malaysia
259 England, Naledi, Dr Ruth Segomotsi Mompati, North West
260 Lusaka, Lusaka Province, Zambia
261 TO
262 London, Greater London, England, UK
263 Nigeria
264 Malaysia
265 New York
266 Sheffield, Yorkshire and the Humber, England, UK
267 New Delhi, Connaught Place, New Delhi, Delhi
268 Nairobi, Kenya
269 Shah Alam, Seksyen 7, Shah Alam, Petaling, Selangor
270 null
271 Manchester, Lancashire, England
272 Kathmandu, काठमाडौं, बागमती अञ्चल, मध्यमाञ्चल विकास क्षेत्र, नेपाल
273 Nigeria
274 Nigeria
275 Besut, Terengganu
276 Nigeria
277 Old Trafford, Manchester, Lancashire, England
278 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
279 Malta
280 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
281 New Delhi World
282 Nigeria
283 Kano
284 Masjid Wilayah Persekutuan, Jalan Ibadah, Bukit Tunku, Kampung Palimbayan Indah, KL, 50480, Malaysia
285 Lagos, Lagos Island, Lagos
286 Tingley, Yorkshire and the Humber, England, WF3 1UR, UK
287 null
288 London, Greater London, England, UK
289 मुंबई, बॉम्बे, महाराष्ट्र
290 Nairobi, Kenya
291 Everywhere Branch
292 null
293 South Africa
294 Tema, Greater Accra Region, TM3 8AA, Ghana
295 Bristol, Avon, England
296 Lagos, Lagos Island, Lagos, 71510, Nigeria
297 02152
298 Lagos, Lagos Island, Lagos, 71510, Nigeria
299 Bintulu, Division Bintulu, Sarawak
300 Lagos, Lagos Island, Lagos, 71510, Nigeria
301 Nigeria
302 ICT, ‏پاکستان‎
303 Old Trafford, Manchester, Lancashire, England
304 null
305 Singapore
306 دبي, دبي‎, الإمارات العربيّة المتّحدة
307 Worldwide
308 null
309 Ireland
310 ኢትዮጵያ
311 Lagos, Lagos Island, Lagos
312 Nigeria
313 United Kingdom
314 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
315 Johor Bahru, Johor
316 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
317 Student
318 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
319 Lagos, Lagos Island, Lagos
320 Mumbai, Greater Bombay, Maharashtra, 400001, India
321 Jemeppe-sur-Sambre
322 Manchester, Greater Manchester, North West England, England, UK
323 Indonesia
324 Kuala Lumpur, Gorontalo, Indonesia
325 USA
326 Capetown, Humboldt County, California, United States of America
327 Lebuhraya Baru Pantai, Taman Desa, Kuala Lumpur, 58100, Wilayah Persekutuan
328 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
329 Kenya
330 ኢትዮጵያ
331 India
332 Putrajaya, Malaysia
333 New Delhi, Connaught Place, New Delhi, Delhi
334 null
335 Sydney, New South Wales
336 Kuching, Kuching Division, Sarawak, 93XXX, Malaysia
337 Sydney, New South Wales
338 Mothership, Newtownsmith, Glasthule, Dun Laoghaire-Glasthule ED, Dún Laoghaire, Dún Laoghaire-Rathdown, County Dublin, Leinster, A96 DF24, Ireland
339 Manchester, Lancashire, England
340 Theatre Royal, 5, Westgate Street, Bury St. Edmunds, St Edmundsbury, Suffolk, East of England, England, IP33 1QR, UK
341 New York
342 Manchester, Greater Manchester, North West England, England, UK
343 United Tiling
344 Balik Pulau, PNG, 11020, Malaysia
345 London, England
346 Nigeria
347 Bernabé
348 Manchester, Greater Manchester, North West England, England, UK
349 Oklahoma City, Oklahoma
350 Common area, Chesterfield, St. Louis County, Missouri, 63005, United States of America
351 Hamburg, Pennsylvania
352 null
353 Bandar Baru Selayang, Batu Caves, Gombak, Selangor
354 Kuala Lumpur, Gorontalo, Indonesia
355 Galaxy, Columbia, South Carolina
356 Daerah Istimewa Yogyakarta, Indonesia
357 16040, Hilliards, Pennsylvania
358 Manchester, Greater Manchester, North West England, England, UK
359 Guadalajara, Jalisco
360 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
361 Old Trafford, Manchester, Lancashire, England
362 Dublin, County Dublin, Leinster, Ireland
363 Gki Sulsel
364 Selayang, Selangor, 68100, Malaysia
365 Old Trafford, Manchester, Lancashire, England
366 India
367 Géorgie
368 Kebon Jeruk, Jakarta Barat, Daerah Khusus Ibukota Jakarta, Indonesia
369 Portsmouth, Hampshire, England
370 Ondo, Nigeria
371 null
372 Smotherfly Wide, Amber Valley, Derbyshire, East Midlands, England, NG16 6PN, UK
373 Abu Dhabi
374 Peña Madridista Badalona, carrer d'Austràlia, Pep Ventura, Sant Joan de Llefià, Badalona, BCN, CAT, 08020, España
375 Old Trafford, Manchester, Lancashire, England
376 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
377 Manchester, Lancashire, England
378 Kota Kinabalu, Sabah, 88000, Malaysia
379 Salford, Lancashire, England
380 Melbourne, Brevard County, Florida, United States of America
381 Manchester, Lancashire, England
382 Liverpool, North West England, England, UK
383 Manchester, Lancashire, England
384 Nigeria
385 Blarney, uMgungundlovu District Municipality, KwaZulu-Natal
386 Harare, Harare Province, 0000, Zimbabwe
387 Wishaw, Lanarkshire, Scotland
388 Manchester, Greater Manchester, North West England, England, UK
389 Kano
390 Nigeria
391 San Juan de los Lagos, Jalisco
392 Behind the Mill Dam, Belfast, Waldo County, Maine, 04915, United States of America
393 Laois
394 Redmond, King County, Washington, United States of America
395 USA
396 Zamboanga Peninsula, Philippines
397 Dar es Salaam, Kinondoni, Dar es Salaam
398 Manchester, Greater Manchester, North West England, England, UK
399 Lidköping
400 Singapore, Central, 178957, Singapore
401 Jalan Banda Hilir, Taman Melaka Raya, Melaka, Melaka Tengah, 75000, Melaka
402 Lagos, Lagos Island, Lagos, 71510, Nigeria
403 Kungsbacka
404 Nairobi, Kenya
405 Newark, New Jersey
406 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
407 Africa
408 Ilesa, Ilesha East, Osun, Nigeria
409 Darul Makmur, Nagan Raya, Aceh
410 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
411 Portsmouth, Hampshire, England
412 Lagos, Lagos Island, Lagos, 71510, Nigeria
413 Nigeria
414 Urmston, Greater Manchester, North West England, England, M41 9HD, UK
415 Co Wicklow, Wicklow
416 null
417 New York
418 İzmir, Ege Bölgesi, 35240, Türkiye
419 London, England
420 Glasgow City, Scotland, UK
421 Urmston, Manchester, Lancashire, England
422 Lagos, Lagos Island, Lagos, 71510, Nigeria
423 Zimbabwe
424 Kano, Kano Municipal, Kano, PMB 3401, Nigeria
425 Manchester, Lancashire, England
426 Atlanta, Fulton County, Georgia, United States of America
427 Chellaston, Derby, Derbyshire, England
428 Cave, RM, LAZ, Italia
429 Kuka, Katsina
430 Sunyani, Brong-Ahafo Region, Ghana
431 Accra, Accra Metropolis, Greater Accra
432 Lagos, Lagos Island, Lagos, 71510, Nigeria
433 Nigeria
434 Stepps, North Lanarkshire, Scotland, G33 6HY, UK
435 Port Harcourt, Rivers
436 Tanzania
437 Ghana
438 Kasese, Western Region, Uganda
439 Tannahills
440 Fairfax, Fairfax City, Virginia, United States of America
441 Lagos, Lagos Island, Lagos
442 Nigeria
443 Platt Lane Complex
444 Pontefract, Yorkshire and the Humber, England, WF8 1PN, UK
445 New Delhi, Connaught Place, New Delhi, Delhi
446 Bobigny, Seine-Saint-Denis, Île-de-France, France métropolitaine, 93000, France

447 Cork City
448 Mumbai, Greater Bombay, Maharashtra, 400001, India
449 Manchester, Lancashire, England
450 About, CUE, Mvila, SU, Cameroun
451 Mars, Pennsylvania
452 null
453 Accra, Accra Metropolis, Greater Accra
454 Midlands, Devon, South West England, England, PL19 9NF, UK
455 Killarney, Kerry
456 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
457 London, England
458 null
459 Manchester, Lancashire, England
460 England, UK
461 Tottenham, London, England
462 South Essex College, Luker Road, Prittlewell, Southend-on-Sea, East of England, England, SS1 1ND, UK
463 Manchester, Lancashire, England
464 Lagos, Lagos Island, Lagos, 71510, Nigeria
465 Sutton Coldfield, West Midlands, England
466 Brasil
467 None of Your Business
468 My World, 105, Calle 19, Centro financiero de San Isidro, San Isidro, Lima, AN ISIDRO 15036, Perú
469 Sunderland, Tyne and Wear, England
470 Leeds, Yorkshire and the Humber, England, UK
471 Celbridge, Naas, Kildare
472 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
473 Laois
474 null
475 Purano Dhaka, Pokhara, Rapti
476 null
477 Omnipresent
478 Dublin, County Dublin, Leinster, Ireland
479 São Paulo
480 Malaysia
481 Town Wall, New Ross, Wexford
482 PGH, Allegheny County, Pennsylvania, United States of America
483 Europe, Cape Town, Western Cape
484 My World, 105, Calle 19, Centro financiero de San Isidro, San Isidro, Lima, AN ISIDRO 15036, Perú
485 Gaza, Gaza Strip
486 Manchester, Greater Manchester, North West England, England, UK
487 Nigeria
488 Manchester, Greater Manchester, North West England, England, UK
489 The Patch, Victoria
490 Vosloorus, Ekurhuleni, City of Ekurhuleni Metropolitan Municipality, Gauteng, 1431, South Africa
491 Kimberley, Frances Baard, Northern Cape
492 ⚽️, Avenida Las Vegas, La Paz, Envigado, Valle de Aburrá, Antioquia, 055420, Colombia
493 Iron, Aisne, Hauts-de-France
494 Kedah, Malaysia
495 Manhattan, New York
496 Danmark
497 Pulau Pinang
498 Penang, Jawa Timur, Indonesia
499 Eire
500 Nigeria
501 Nigeria
502 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
503 Bangor, County Down, Northern Ireland
504 صحار, محافظة شمال الباطنة, عمان
505 UK
506 Nairobi, Kenya
507 Beal Feirste, Belfast, City of Belfast, N Ireland
508 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
509 Indore, Madhya Pradesh
510 Hounslow, London, Greater London, England, TW3 1BL, UK
511 Orlando, Florida
512 null
513 Wigan, Lancashire, England
514 Espoo, Helsingin seutukunta, Uusimaa, Etelä-Suomi, Manner-Suomi, Suomi
515 Kaduna, Kaduna North, Kaduna
516 Morogoro, Coastal, 6284, Tanzania
517 Old Trafford, Manchester, Lancashire, England
518 In The Matrix, Frederiks Allé, Åbyhøj, Aarhus, Aarhus Kommune, Region Midtjylland, 8000, Danmark
519 Sandton, Sandown, Johannesburg, Gauteng
520 Ripponden, Yorkshire and the Humber, England, HX6, UK
521 Lagos, Lagos Island, Lagos
522 NYC, New York, United States of America
523 England, Naledi, Dr Ruth Segomotsi Mompati, North West
524 null
525 England, Naledi, Dr Ruth Segomotsi Mompati, North West
526 Leeds, Yorkshire and the Humber, England, UK
527 Kuala Selangor, Selangor
528 Rio de Janeiro, Microrregião Rio de Janeiro, Região Metropolitana do Rio de Janeiro, RJ, Região Sudeste, Brasil
529 Nairobi
530 ঢাকা, ঢাকা বিভাগ, 12, বাংলাদেশ
531 Etihad Stadium
532 Unknown, The Bahamas
533 Ireland
534 Bermuda
535 Texas
536 Dublin, County Dublin, Leinster, Ireland
537 Nigeria
538 Granite City, Conference Center Drive, East Peoria, Tazewell County, Illinois, 61611, United States of America
539 Sungai Buloh, Gombak, Selangor
540 Southeastern Mass. Educational Collaborative (SMEC) - Transitional Services Level II, Peckham Road, New Bedford, Bristol County, Massachusetts, 02745, United States of America
541 Mumbai, Maharashtra
542 null
543 Downham Market, Norfolk, England
544 null
545 Manchester, Lancashire, England
546 Dublin, County Dublin, Leinster, Ireland
547 Limerick
548 Dreamland, Houghton County, Michigan, United States of America
549 Johore, Johor
550 Wales, UK
551 Bandar Baru Klang, Kapar, Klang, Selangor
552 Dublin, County Dublin, Leinster, Ireland
553 Kenya
554 Manchester, Greater Manchester, North West England, England, UK
555 Yogyakarta, Daerah Istimewa Yogyakarta
556 Dallas, Dallas County, Texas, United States of America
557 Ibadan, Oyo
558 Malaysia
559 Lagos, Lagos Island, Lagos
560 Mumbai, Greater Bombay, Maharashtra, 400001, India
561 407
562 null
563 Scotland
564 London, Greater London, England, UK
565 Scotland
566 Toronto, Ontario, Canada
567 Nairobi
568 null
569 Nairobi
570 DMCC AUTO .donny, 10, Pond Road, San Fernando, VISTABELLA, Trinidad and Tobago
571 Nairobi
572 Letterkenny, County Donegal, Ireland
573 Manchester, Lancashire, England
574 null
575 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
576 Manchester, Greater Manchester, North West England, England, UK
577 Shah Alam, Seksyen 7, Shah Alam, Petaling, Selangor
578 null
579 Nigeria
580 Kaduna, Nigeria
581 Ig, Ljubljana
582 Trinidad and Tobago
583 Gauteng Ave, Lakeside Ext 2, Johannesburg, Gauteng, 1805
584 Wolverhampton, West Midlands Combined Authority, West Midlands, England, UK
585 Dublin
586 Kaduna, Nigeria
587 Germany
588 اليمن
589 Kaduna, Kaduna North, Kaduna
590 Liverpool, North West England, England, UK
591 Paris, Île-de-France
592 Subang Jaya, Selangor, 47610, Malaysia
593 Somewhere
594 Iringa, Southern Highlands, Tanzania
595 Galaxy, Columbia, South Carolina
596 Manchester, Greater Manchester, North West England, England, UK
597 Old Trafford, Manchester, Lancashire, England
598 null
599 United Kingdom
600 null
601 Birmingham, West Midlands, England
602 الأرض, حضرموت, اليمن
603 Glasgow, Lanarkshire, Scotland
604 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
605 Manchester, Lancashire, England
606 London, Greater London, England, UK
607 London, England
608 London, Greater London, England, UK
609 Lagos, Lagos Island, Lagos
610 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
611 Happy, Kentucky
612 null
613 Nairobi
614 null
615 Vancouver, British Columbia
616 Santiago Bernabéu, Paseo de la Castellana, Chamartín, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28020, España
617 Bachok, Kelantan
618 Mbeya, Southern Highlands, Tanzania
619 Accra, Accra Metropolis, Greater Accra
620 London, Greater London, England, UK
621 In My Room
622 Malaysia
623 null
624 UK
625 Makassar, Sulawesi Selatan
626 Bloemfontein, Mangaung Metropolitan Municipality, Free State, 9301, South Africa
627 London, England
628 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
629 Manchester, Lancashire, England
630 Mumbai, Greater Bombay, Maharashtra, 400001, India
631 London, England
632 Manchester, Greater Manchester, North West England, England, UK
633 Manchester, Lancashire, England
634 null
635 Kota Bharu, Kelantan
636 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
637 Everywhere Branch
638 Kota Damansara, PJ, Selangor, 47810, Malaysia
639 West Bromwich, West Midlands, England
640 Nairobi, Kenya
641 St Germans, Saltash, Cornwall, England
642 Islamabad, East Gate, San Juan, Taytay, Rizal, Calabarzon, 1920, Philippines
643 Kumasi, Kumasi Metropolitan, Ashanti
644 null
645 Wind Ln, Waterboro, Maine, 04087
646 Portugal
647 Nigeria
648 PGH, Allegheny County, Pennsylvania, United States of America
649 SC
650 Sverige
651 Etihad Stadium
652 Pitch, Ballytivnan, Sligo North ED, The Borough District of Sligo, County Sligo, Connacht, Ireland
653 My Domain
654 Signal Iduna Park, 50, Strobelallee, Brünninghausen, Dortmund, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 44139, Deutschland
655 Gauteng Ave, Lakeside Ext 2, Johannesburg, Gauteng, 1805
656 Manchester, Greater Manchester, North West England, England, UK
657 Universe
658 Michigan, United States of America
659 Old Trafford, Manchester, Lancashire, England
660 Kochi, Ernakulam, Kerala, 628002, India
661 Randburg, Ferndale, Johannesburg, Gauteng
662 North Carolina, United States of America
663 Lagos, Lagos Island, Lagos

664 Addonics Solutions Pvt. Ltd, Vile Parle, Mumbai, Dayaldas Road, Vagri Wada, Vile Parle East, Mumbai, Greater Bombay, Maharashtra, 400057, India
665 United Kingdom
666 Manchester, Greater Manchester, North West England, England, UK
667 Kaduna, Kaduna North, Kaduna
668 null
669 WIU
670 null
671 Manchester United
672 München, OB, Bayern, Deutschland
673 Igloo, Alaska
674 null
675 Old Trafford
676 Manchester, Greater Manchester, North West England, England, UK
677 Serang, Banten
678 Manchester, Greater Manchester, North West England, England, UK
679 Lier
680 Surabaya, Jawa Timur, 60174, Indonesia
681 Johor Bahru, Johor
682 Joensuu, Itä-Suomen aluehallintovirasto, Itä-Suomi, Manner-Suomi, 81200, Suomi
683 Durban, eThekwini, Kwazulu Natal
684 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
685 UK
686 Singapore, Central, 178957, Singapore
687 Lancashire, England
688 Newport, Carisbrooke, Isle of Wight, South East, England, UK
689 West, Texas
690 null
691 London, England
692 City of Nottingham, East Midlands, England, UK
693 Tromsø, Troms
694 ‏پاکستان‎
695 Nairobi
696 Malaysia
697 England
698 Manchester, Greater Manchester, North West England, England, UK
699 London, England
700 UK
701 Tanzania
702 null
703 Nigeria
704 Kericho, Kenya
705 Ohio
706 Linköping, Landskapet Östergötland, Östergötlands län, Götaland, 582 24, Sverige
707 Suffolk, Virginia
708 Ampang, Selangor, 6, Malaysia
709 Atlanta, Georgia
710 Lagos, Lagos Island, Lagos, 71510, Nigeria
711 02152
712 null
713 Lebanon
714 Glasgow City, Scotland, UK
715 Ipoh, Kinta, Perak
716 Sarawak, Malaysia
717 Polokwane, Capricorn, Limpopo
718 Wales, UK
719 London, England
720 Arlington, Tarrant County, Texas, United States of America
721 2010
722 Cape Coast, Central Region, Ghana
723 El Salvador
724 Kedah, Malaysia
725 New Delhi, Connaught Place, New Delhi, Delhi
726 Florida, United States of America
727 Singapore
728 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
729 London, England
730 Palmdale, Los Angeles County, California, United States of America
731 Pasir Gudang, Johor Bahru, Johor
732 PRK, Malaysia
733 Via Massi, 47034, Forlimpopoli, FC
734 Chesterfield, Derbyshire, East Midlands, England, UK
735 Katy, Texas
736 null
737 Tebet, Jakarta, DKI Jakarta
738 Jakarta, Gambir, Jakarta Pusat, Daerah Khusus Ibukota Jakarta, 10110, Indonesia
739 Kumasi, Kumasi Metropolitan, Ashanti
740 Napa Auto Parts, Finley Road, Tri County Plaza, Allens Crossroads, Westmoreland County, Pennsylvania, 15012, United States of America
741 Bernabé
742 PNG, Malaysia
743 Palamaner, Chittoor, Andhra Pradesh
744 Yelwa, Yauri, Kebbi, Nigeria
745 In My Room
746 Chembur, Ramakrishna Chemburkar Marg, Chembur Gaothan, Chembur West, Mumbai, Greater Bombay, Maharashtra, 400074, India
747 Mooresville, North Carolina
748 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
749 null
750 Kampala, Central Region, 7063, Uganda
751 Malaysia
752 Sungai Kelang, Selangor, 50100, Malaysia
753 Kuala Selangor, Selangor
754 City of Edinburgh, Scotland, UK
755 Toronto, Ontario
756 null
757 Singapore, Bukal, Pagbilao, Quezon, Calabarzon
758 England, UK
759 Madrid, Comunidad de Madrid
760 Kuala Lumpur, Jalan Pekeliling KLIA, Kampung Baru Lanjut, Salak, Sepang, Selangor, 71760, Malaysia
761 Congleton, Cheshire, England
762 null
763 Moscow
764 null
765 Malaysia
766 Sidoarjo, Jalan Diponegoro, Lemahputro, Jawa Timur, 60271, Indonesia
767 Perak, Temerloh, Pahang
768 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
769 Singapore
770 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
771 Nigeria
772 null
773 Manchester United
774 Virginia, United States of America
775 Singapore
776 Bali, Gianyar, Bali, Indonesia
777 Malaysia
778 The Warren, Epping Forest, Essex, East of England, England, CM16 5HN, UK
779 Spain
780 Dogondaji, Tambuwal, Sokoto, Nigeria
781 Suisse
782 Sokoto, Nigeria
783 Theatre of Dreams
784 Shah Alam, Selangor, 40000, Malaysia
785 England, Naledi, Dr Ruth Segomotsi Mompati, North West
786 Al Khobar Graveyard, العقربية, الخبر, المنطقة الشرقية, السعودية
787 อำเภอป่าพะยอม จังหวัดพัทลุง
788 Lagos, Lagos Island, Lagos, 71510, Nigeria
789 Damauli, Western Region
790 Singapore, Central, 178957, Singapore
791 null
792 Charlotte, Mecklenburg County, North Carolina, United States of America
793 Versailles
794 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
795 Pretoria, Tshwane, Gauteng
796 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
797 Livingston, West Lothian, Scotland
798 null
799 Mumbai, Maharashtra
800 Kuching, Kuching Division, Sarawak, 93XXX, Malaysia
801 Eden, Western Cape
802 Indonesia
803 Kampala
804 Harare, Harare Province, 0000, Zimbabwe
805 null
806 Google, 355, Main Street, East Cambridge, Cambridge, Suffolk, Massachusetts, 02142, United States of America
807 Houston, Texas
808 Illinois, United States of America
809 Venezuela
810 Johor Bahru, Johor, 80250, Malaysia
811 Hà Nội
812 Osun, Nigeria
813 Bontang, Kalimantan Timur
814 null
815 Gonfreville-l'Orcher, Seine-Maritime, Normandie
816 Sungai Buloh, Selangor, 47830, Malaysia
817 Surakarta, Jawa Tengah
818 null
819 Sakoli, Bhandara, Maharashtra
820 HSBC Treetop Walk, Bukit Timah, Northwest, 578774, Singapore
821 Worldwide
822 Lagos, Lagos Island, Lagos, 71510, Nigeria
823 Puerto Rico
824 UK
825 Jakarta, DKI Jakarta
826 Manchester, Greater Manchester, North West England, England, UK
827 Glasgow, Lanarkshire, Scotland
828 null
829 Home, Pennsylvania
830 Lagos, Lagos Island, Lagos, 71510, Nigeria
831 Manchester United
832 서울특별시, 대한민국
833 Lagos, Lagos Island, Lagos
834 Rustenburg, Bojanala Platinum District Municipality, North West, South Africa
835 Bengaluru, Karnataka
836 X-Large, 17, Herrengasse, Lebing, Hartberg, Bezirk Hartberg-Fürstenfeld, Steiermark, 8230, Österreich
837 Keket, East Java
838 Kenya
839 المملكة العربية السعودية
840 Malaysia
841 München, Bayern
842 Gurun, K Muda, Kedah, 08800, Malaysia
843 Valeria
844 Wales, UK
845 Cole, Texas
846 Jeddah, Bliss, V&G Subdivision, Tacloban, Leyte, Eastern Visayas, 6500, Philippines
847 Autoroute du Nord, 62128, Saint-Léger, Pas-de-Calais, Hauts-de-France
848 Melaka, Melaka Tengah, MLK, 75000, Malaysia
849 Spain
850 Blue moon, 5115, PGH, Allegheny County, Pennsylvania, 15201, United States of America
851 Kuala Berang, Hulu Terengganu, Terengganu
852 Malaysia
853 صحار, شمال الباطنة
854 Hawaii, United States of America
855 0267
856 Bengaluru, Bangalore Urban, Karnataka, 560001, India
857 Le Havre, Seine-Maritime, Normandie
858 日本
859 Greater Accra
860 Terra, Tooele County, Utah, United States of America
861 London, England
862 Gidi, Tibesti تيبستي, Tchad تشاد
863 Nairobi
864 Dublin, County Dublin, Leinster, Ireland
865 United Kingdom
866 England, UK
867 The Sleepy Owl
868 Dublin, County Dublin, Leinster, Ireland
869 Mbarara
870 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
871 United Kingdom
872 England, UK
873 England
874 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
875 New Delhi, Connaught Place, New Delhi, Delhi
876 Kedah, Malaysia
877 Deutschland
878 Kaduna, Nigeria
879 United Kingdom
880 Katsina, Nigeria
881 Indonesia
882 Lagos, Lagos Island, Lagos, 71510, Nigeria
883 Gaborone
884 Lagos, Lagos Island, Lagos, 71510, Nigeria
885 Old Trafford, Manchester, Lancashire, England
886 Uhuru Peak, Rombo, Kilimanjaro, Tanzania
887 Maidenhead, Berkshire, England
888 null
889 Sunyani, Brong Ahafo
890 Manchester, Greater Manchester, North West England, England, UK
891 Lagos, Lagos Island, Lagos
892 Brunei Darussalam
893 Liverpool, Merseyside, England
894 London, Greater London, England, UK
895 Galway
896 Belfast, County Antrim, Northern Ireland, BT1 5GS, UK
897 Tannahills
898 London, Greater London, England, UK
899 Westerose, Wetaskiwin County No 10, Alberta
900 UK
901 المملكة العربية السعودية
902 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
903 United Kingdom
904 England, UK
905 United Kingdom
906 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
907 England
908 England, UK
909 Illinois
910 Kampala, Central Region, 7063, Uganda
911 United Kingdom
912 Rovigo, RO, VEN, 45100, Italia

913 Manchester, Lancashire, England
914 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
915 Lagos, Lagos Island, Lagos
916 null
917 Kolkata, Calcutta, West Bengal
918 null
919 Old Trafford, Manchester, Lancashire, England
920 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
921 Johannesburg, Gauteng
922 London, Greater London, England, UK
923 Northern Ireland
924 null
925 Manchester, Lancashire, England
926 MUFC Ticketing and Membership Services, Bridgewater Canal Towpath, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0SZ, UK
927 Lagos, Lagos Island, Lagos
928 Nigeria
929 Nakuru
930 Bristol, City of Bristol, South West England, England, UK
931 UK
932 Lagos, Lagos Island, Lagos, 71510, Nigeria
933 Manchester, Lancashire, England
934 Ahmedabad, Ahmadabad, Gujarat, 380001, India
935 Leeds, West Yorkshire, England
936 Cardiff, Wales, CF, UK
937 UAE
938 नेपाल
939 Africa
940 Dublin, County Dublin, Leinster, Ireland
941 Bengaluru, Karnataka
942 Chancellors, Whitworth Lane, Fallowfield, Manchester, Greater Manchester, North West England, England, M14 6NN, UK
943 Canada
944 Warri, Warri South, Delta, Nigeria
945 Africa
946 Bavaria, Matthias-Pschorr-Straße, Bezirksteil St. Paul, Stadtbezirk 02 Ludwigsvorstadt-Isarvorstadt, München, OB, Bayern, 80336, Deutschland
947 Littoral
948 Lagos, Lagos Island, Lagos, 71510, Nigeria
949 Lagos, Lagos Island, Lagos
950 Lagos, Lagos Island, Lagos, 71510, Nigeria
951 United States
952 CAT, España
953 Nigeria
954 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
955 United Kingdom
956 Antarctica
957 Berlin
958 Lagos, Lagos Island, Lagos, 71510, Nigeria
959 Don, Pak Thong Chai, Nakhon Ratchasima
960 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
961 Melbourne, Victoria
962 Manchester, Greater Manchester, North West England, England, UK
963 South Africa
964 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
965 Leeds, West Yorkshire, England
966 Nigeria
967 London, England
968 null
969 Cheshire, Oregon
970 Lagos, Lagos Island, Lagos, 71510, Nigeria
971 Manchester, Lancashire, England
972 Anfield, Anfield Road, Walton, Liverpool, North West England, England, L4 0TH, UK
973 Liverpool, Merseyside, England
974 Nairobi, Kenya
975 null
976 South Africa
977 United Kingdom
978 null
979 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
980 United States of America
981 New York
982 Kaduna, Nigeria
983 Newcastle Close, Thorpe St Andrew, Norwich, Norfolk, England, NR7 0
984 Zimbabwe
985 Ocean Floor
986 null
987 London, England
988 Lagos, Lagos Island, Lagos, 71510, Nigeria
989 La Cosmerie, Assé-le-Riboul, Sarthe, Pays de la Loire
990 null
991 Lagos, Lagos Island, Lagos
992 NYC, New York, United States of America
993 UK
994 Mumbai, Greater Bombay, Maharashtra, 400001, India
995 London, England
996 Glasgow City, Scotland, UK
997 Glasgow, Lanarkshire, Scotland
998 Auckland, 1010, New Zealand/Aotearoa
999 Boothstown, City and Borough of Salford, England
1000 Glasgow City, Scotland, UK
1001 Wild West
1002 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1003 Manchester, Lancashire, England
1004 Derby, East Midlands, England, DE1, UK
1005 Coatbridge, Lanarkshire, Scotland
1006 Glasgow City, Scotland, UK
1007 Scotland
1008 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
1009 California
1010 null
1011 Zimbabwe
1012 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1013 Etihad Stadium
1014 דרום אפריקה/יוהנסבורג, שדרות דרום אפריקה, אפרידר, אשקלון, מחוז הדרום, 78503, מדינת ישראל
1015 Ghana
1016 Valsād, Valsad, Gujarat, India
1017 Newcastle upon Tyne, Tyne and Wear, England
1018 null
1019 Anambra
1020 Manchester, Greater Manchester, North West England, England, UK
1021 Lagos, Lagos Island, Lagos
1022 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1023 Morecambe, Lancashire, England
1024 Zimbabwe
1025 Zimbabwe
1026 日本
1027 Lagos, Lagos Island, Lagos
1028 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
1029 United Kingdom
1030 Trenton, Dade County, Georgia, United States of America
1031 Mumbai, Maharashtra
1032 null
1033 New Jersey
1034 Fairfield County, Connecticut, United States of America
1035 Kingston
1036 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1037 Nairobi
1038 null
1039 0254
1040 Australia
1041 Old Trafford, Manchester, Lancashire, England
1042 Nigeria
1043 United Kingdom
1044 null
1045 Dar es Salaam, Kinondoni, Dar es Salaam
1046 Nigeria
1047 Island, Ohio
1048 London, Greater London, England, UK
1049 Kingston
1050 null
1051 United Kingdom
1052 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1053 United States
1054 United States of America
1055 Winner, South Dakota
1056 Mumbai, Greater Bombay, Maharashtra, 400001, India
1057 Manchester, Lancashire, England
1058 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1059 Bantul, Daerah Istimewa Yogyakarta
1060 Twitter, 1355, Market Street, Civic Center, SF, California, 94114, United States of America
1061 Japan
1062 Goiânia, Microrregião de Goiânia, Mesorregião Centro Goiano, GO, Região Centro-Oeste, Brasil
1063 Banyumas, Jawa Tengah
1064 London, Greater London, England, UK
1065 Kanpur, Kanpur Nagar, Uttar Pradesh
1066 Manchester, Greater Manchester, North West England, England, UK
1067 Lagos, Lagos Island, Lagos
1068 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1069 United Kingdom
1070 Quito, Pichincha, Ecuador
1071 null
1072 Bali, Gianyar, Bali, Indonesia
1073 Bali, Pali, Rajasthan
1074 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1075 Lagos, Lagos Island, Lagos
1076 null
1077 Quito
1078 Atlanta, Fulton County, Georgia, United States of America
1079 Universe
1080 Quito, Pichincha, Ecuador
1081 United Kingdom
1082 United States of America
1083 Manchester, Lancashire, England
1084 Woodlands, Northwest, 738343, Singapore
1085 East
1086 Ciudad de México, Cuauhtémoc, 06060, México
1087 Somewhere
1088 Indiana, United States of America
1089 Klang, Selangor
1090 null
1091 Singaraja, Bali
1092 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1093 Accra, Accra Metropolis, Greater Accra
1094 England, UK
1095 England
1096 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1097 Ashton in Makerfield, Wigan, Lancashire, England
1098 Place My Yazid, Zone Touristique de l'Agdal ⵜⴰⵎⵏⴰⴹⵜ ⵜⴰⵎⴰⵍⵍⴰⵢⴰⵏⵜ ⵏ ⵓⴳⴷⴰⵍ, Mechouar Kasbah المشور القصبة, Pachalik de Méchouar Kasba, Préfecture de Marrakech عمالة مراكش, Marrakech-Safi ⵎⵕⵕⴰⴽⵛ-ⴰⵙⴼⵉ مراكش-أسفي, Maroc
1099 Sheffield, South Yorkshire, England
1100 Kano, Kano Municipal, Kano, PMB 3401, Nigeria
1101 Manchester, Lancashire, England
1102 Comunidad de Madrid, España
1103 United Kingdom
1104 Manchester, Greater Manchester, North West England, England, UK
1105 Football World
1106 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
1107 Kenya
1108 Nairobi, Kenya
1109 Manchester, Lancashire, England
1110 null
1111 AT
1112 China, Nuevo León, México
1113 Sydney, New South Wales
1114 Belfast, County Antrim, Northern Ireland, BT1 5GS, UK
1115 null
1116 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1117 Warrington, Cheshire, England
1118 null
1119 Ireland
1120 Shqipëria
1121 England
1122 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
1123 Manchester, Lancashire, England
1124 HD6 283, Towngate Avenue, Calderdale, Yorkshire and the Humber, England, HD6 4HX, UK
1125 A Capital
1126 Yorkshire, Cattaraugus County, New York, 14173, United States of America
1127 Huddersfield, West Yorkshire, England
1128 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1129 Huddersfield, West Yorkshire, England
1130 Montréal, Montréal (06), Québec, Canada
1131 Kumasi, Kumasi Metropolitan, Ashanti
1132 Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, España
1133 Chesterfield, Derbyshire, England
1134 null
1135 United Kingdom
1136 23 August, Constanța, 907005, România
1137 Bombay Bag
1138 null
1139 Hambleton, Selby, North Yorkshire, England
1140 Liverpool, North West England, England, UK
1141 België
1142 Cork, County Cork, Munster, T12 PR83, Ireland
1143 Birmingham, West Midlands, England
1144 null
1145 Accra, Accra Metropolis, Greater Accra

1146 Liverpool, North West England, England, UK
1147 Liverpool, Merseyside, England
1148 Sunyani, Brong-Ahafo Region, Ghana
1149 United Kingdom
1150 Field, Wall Township, Monmouth County, New Jersey, 07719, United States of America
1151 Ingenieros Industriales(Upm)
1152 null
1153 England, Naledi, Dr Ruth Segomotsi Mompati, North West
1154 Liverpool, North West England, England, UK
1155 Wirral, Merseyside, England
1156 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1157 Wirral Villas, Wallasey, Merseyside, England, CH45 3
1158 Durham, County Durham, North East England, England, DH1 3NE, UK
1159 Manchester, Lancashire, England
1160 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1161 Earth, Texas
1162 Lusaka, Lusaka Province, Zambia
1163 Liverpool, Merseyside, England
1164 Manchester, Greater Manchester, North West England, England, UK
1165 Dewsbury, West Yorkshire, England
1166 Chingola, Copperbelt Province, Zambia
1167 nou Camp
1168 Earth, Lamb County, Texas, 79031, United States of America
1169 United Kingdom
1170 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1171 Miami, Florida
1172 PGH, Allegheny County, Pennsylvania, United States of America
1173 Earth, Texas
1174 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
1175 Belfast, County Antrim, Northern Ireland
1176 Entebbe, Wakiso, Central Region, 7545, Uganda
1177 Chitown
1178 null
1179 Out, Mandee, Himachal Pradesh
1180 19, 環球大廈 World-Wide House, 中環 Central District, 香港, 中西區 Central and Western District, 香港島 Hong Kong Island, HK, 中国
1181 USA
1182 W202, 货运北路, 朝阳区 / Chaoyang, 北京市, 101312, 中国
1183 Chennai, Tamil Nadu
1184 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1185 England
1186 UK
1187 Salvador, Bahia
1188 Manchester, Greater Manchester, North West England, England, UK
1189 Manchester, Lancashire, England
1190 Nairobi, Kenya
1191 Los Sánchez
1192 The Country, Alamance County, North Carolina, 27215-5151, United States of America
1193 Nigeria
1194 null
1195 United Kingdom
1196 null
1197 Köln, Nordrhein-Westfalen
1198 The Sussex, Long Acre, St Clement Danes, Covent Garden, City of Westminster, London, Greater London, England, WC2E 9JR, UK
1199 Sam's Rd, Cochrane District, Ontario, P0L
1200 UK
1201 Nottingham, Nottinghamshire, England
1202 Nigeria
1203 Worldwide
1204 Nigeria
1205 Bhind, Madhya Pradesh
1206 null
1207 Lekki, Lagos
1208 Lagos, Lagos Island, Lagos, 71510, Nigeria
1209 Abuja, Abuja Municipal, Federal Capital Territory
1210 Federal Capital Territory, Nigeria
1211 Nigeria
1212 Nigeria
1213 Sa
1214 Lagos, Lagos Island, Lagos, 71510, Nigeria
1215 Lagos, Lagos Island, Lagos
1216 Nigeria
1217 Huddersfield, West Yorkshire, England
1218 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1219 東京都大島町泉津福重
1220 Warri, Warri South, Delta, Nigeria
1221 Staplehurst, Tonbridge, Kent, England
1222 Smotherfly Wide, Amber Valley, Derbyshire, East Midlands, England, NG16 6PN, UK
1223 Port Harcourt, Rivers
1224 San Siro, Via dei Piccolomini, San Siro, Milano, MI, LOM, 20148, Italia
1225 Utopia, Florida
1226 Nigeria
1227 Ghana
1228 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
1229 Manchester, Lancashire, England
1230 الإمارات العربيّة المتّحدة
1231 Paradise, Nevada
1232 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1233 Cape Town, Western Cape
1234 Tema, Greater Accra Region, TM3 8AA, Ghana
1235 Rua José Mendes, Lagoa, Ouro Preto, Minas Gerais, 35400-000
1236 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
1237 null
1238 Manchester, Greater Manchester, North West England, England, UK
1239 Ghana
1240 Manchester, Greater Manchester, North West England, England, UK
1241 India
1242 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1243 Fort McMurray, Wood Buffalo, Alberta
1244 Venezuela
1245 United Kingdom
1246 The Matrix, Eshiels, Scottish Borders, Scotland, EH45 8ND, UK
1247 Shaolin
1248 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1249 Lagos, Lagos Island, Lagos
1250 Manchester, Greater Manchester, North West England, England, UK
1251 Nairobi
1252 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
1253 Tema, Tema Municipal, Greater Accra
1254 Sevilla, Andalucía, España
1255 Venezuela
1256 null
1257 Venezuela
1258 Vellore, Vellore district, Tamil Nadu, 632002, India
1259 Hubli, Dharwad, Karnataka
1260 India
1261 The Earth
1262 Ghana
1263 Somewhere
1264 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1265 MD
1266 Manchester, Greater Manchester, North West England, England, UK
1267 Accra, Accra Metropolis, Greater Accra
1268 Africa
1269 Chase
1270 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1271 Tema, Tema Municipal, Greater Accra
1272 null
1273 UT
1274 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1275 Ghana
1276 India
1277 Infinity Wireless & Beyond
1278 null
1279 Nigeria
1280 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1281 Kanayannur, Ernakulam, Kerala
1282 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1283 United States
1284 Manchester, Greater Manchester, North West England, England, UK
1285 Timeline
1286 Orlando, Orange County, Florida, United States of America
1287 Everywhere Branch
1288 null
1289 Goodison Park
1290 Manchester, Greater Manchester, North West England, England, UK
1291 Mumbai, Maharashtra
1292 null
1293 Tema, Tema Municipal, Greater Accra
1294 California, United States of America
1295 London, England
1296 Boston, Suffolk, Massachusetts, United States of America
1297 Ireland
1298 Ne, GE, LIG, 16042, Italia
1299 Chicago, Illinois
1300 Kumasi, Ashanti Region, Ghana
1301 Bahrain
1302 Manchester, Greater Manchester, North West England, England, UK
1303 null
1304 Venezuela
1305 Nigeria
1306 null
1307 Monaco
1308 paris, Plaça Paris, Lloret de Mar, Selva, Girona, CAT, 17310, España
1309 United Kingdom
1310 San Siro, Via dei Piccolomini, San Siro, Milano, MI, LOM, 20148, Italia
1311 Camp Nou, Província de Barcelona, Catalonia
1312 null
1313 Buenos Aires, Ciudad Autónoma de Buenos Aires
1314 Córdoba, Andalucía, España
1315 Stockport, Cheshire, England
1316 null
1317 Kroonstad, Fezile Dabi, Free State
1318 Pejë, Komuna e Pejës, Rrafshi i Dukagjinit, Rajoni i Pejës (03), 39000, Kosova
1319 No Idea
1320 null
1321 Port Harcourt, Rivers
1322 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
1323 Jamrock
1324 India
1325 Huddersfield, West Yorkshire, England
1326 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1327 Lagos, Lagos Island, Lagos
1328 Holmfirth, Yorkshire and the Humber, England, HD9 7DD, UK
1329 Ethiopian
1330 Deutschland, Europe
1331 Theatre of Dreams
1332 Manchester, Greater Manchester, North West England, England, UK
1333 Theatre of Dreams
1334 London, Greater London, England, UK
1335 Tasmania
1336 London, Greater London, England, UK
1337 Manchester United
1338 Kolkata, Hāora, West Bengal, 700021, India
1339 Tema, Tema Municipal, Greater Accra
1340 UK
1341 London, England
1342 Kampala, Central Region, 7063, Uganda
1343 Humber, Teignmouth, Devon, England
1344 Gili Villas, Jalan Bintang Laut, Lombok Utara, Kec. Ampenan, Nusa Tenggara Barat, 83352, Indonesia
1345 New Jersey
1346 Southend-on-Sea, East of England, England, UK
1347 ON
1348 Lagos, Lagos Island, Lagos, 71510, Nigeria
1349 Durham, County Durham, England
1350 Namibia
1351 Manchester, Lancashire, England
1352 Salford, Greater Manchester, North West England, England, UK
1353 United Kingdom
1354 Kingston, Surrey County, KINGSTON 14, Jamaica
1355 Manchester, Lancashire, England
1356 England, UK
1357 United States
1358 UK
1359 Hale, Altrincham, Cheshire, England
1360 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1361 Pakistan
1362 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1363 Earthquakes Way, San Jose, California, 95110
1364 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1365 United Kingdom
1366 The Octagon, Old Hunstanton, King's Lynn and West Norfolk, Norfolk, East of England, England, UK

1367 Holland, Missouri
1368 null
1369 Ldn
1370 Lekki, Ilaje, Ondo, Nigeria
1371 Facelook.Com
1372 Hell, Stjørdal, Nord-Trøndelag, 7502, Norge
1373 Sacramento, California
1374 Surat, Bharūch, Surat, Gujarat, 395001, India
1375 United Kingdom
1376 London, Greater London, England, UK
1377 Manchester, Lancashire, England
1378 null
1379 Canada
1380 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
1381 Kampala
1382 Jamaica
1383 Huddersfield, West Yorkshire, England
1384 St. Albert, Alberta, T8N 5C9, Canada
1385 Sioux Falls, South Dakota
1386 null
1387 Ibadan, Oyo
1388 Nigeria
1389 Halifax, Nova Scotia
1390 London, Greater London, England, UK
1391 London, England
1392 Kolkata, Hāora, West Bengal, 700021, India
1393 Matrix
1394 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
1395 Federal Capital Territory
1396 Tamworth, Staffordshire, West Midlands, England, UK
1397 Lagos, Lagos Island, Lagos
1398 254, Stadtbezirk 10 Moosach, München, OB, Bayern, 80992, Deutschland
1399 Tema, Tema Municipal, Greater Accra
1400 N, Pier Four Road North, Crawley, West Sussex, South East, England, RH6 0JW, UK
1401 Lagos, Lagos Island, Lagos
1402 Lagos, Lagos Island, Lagos, 71510, Nigeria
1403 London, England
1404 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
1405 Ghana
1406 null
1407 West Coast
1408 Indonesia
1409 Bournemouth, Dorset, England
1410 England, UK
1411 Warwickshire, England
1412 null
1413 Akweenyanga, Oshana
1414 Nederland
1415 Pásion
1416 Україна
1417 Chicago, Illinois
1418 Nigeria
1419 London, England
1420 null
1421 Cowshed
1422 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1423 Manchester, Lancashire, England
1424 Sheffield, Yorkshire and the Humber, England, UK
1425 Thoughts
1426 Bojonegoro, Jalan Gajah Mada, Sukorejo, Jawa Timur, 62118, Indonesia
1427 Manchester, Lancashire, England
1428 null
1429 United States
1430 Navi Mumbai, Greater Bombay, Maharashtra, 400614, India
1431 London, England
1432 دبي, دبي‎, الإمارات العربيّة المتّحدة
1433 United Kingdom
1434 Chancellors, Whitworth Lane, Fallowfield, Manchester, Greater Manchester, North West England, England, M14 6NN, UK
1435 Brighton, East Sussex, England
1436 Abidjan, Côte d’Ivoire
1437 The Towers
1438 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
1439 England
1440 Phalaborwa, Mopani District Municipality, Limpopo, 1390, South Africa
1441 Stamford Bridge, York, North Yorkshire, England
1442 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1443 London, England
1444 null
1445 New York
1446 Manchester, Greater Manchester, North West England, England, UK
1447 Sverige
1448 Kampala, Central Region, 7063, Uganda
1449 White Hart Lane
1450 Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, España
1451 Nigeria
1452 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
1453 Seoul
1454 Dubai, Buurhakaba بورحكب, Buur Hakaba بورحكب, Bay باي, Soomaaliya الصومال
1455 Manchester, Lancashire, England
1456 null
1457 Maidstone, Kent, England
1458 Sala de Ciencias de la Tierra y del Universo, Calle Juan Bautista Sacchetti, Jerónimos, Barrio Jerónimos, Retiro, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28009, España
1459 Brasil
1460 Nottinghamshire, East Midlands, England, UK
1461 Jacksonville, Florida
1462 London, Greater London, England, UK
1463 Rennes, 6e Arrondissement, Paris, Île-de-France
1464 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
1465 Don, Pak Thong Chai, Nakhon Ratchasima
1466 Keep Smiling Gift Shop, Khayaban e Aziz Bhatti Shaheed, DHA, ڪراچي Karachi, Karāchi District, سنڌ, 75500, ‏پاکستان‎
1467 MediaCityUK, Salford, Lancashire, England
1468 Kumasi, Ashanti Region, Ghana
1469 Huyton with Roby, Huyton, Liverpool, Merseyside, England
1470 Rim of the World Football Field, Meadowbrook Woods, San Bernardino County, California, United States of America
1471 Yorkshire, England
1472 Blackburn, Blackburn with Darwen, North West England, England, BB1 6HQ, UK
1473 Manchester, Lancashire, England
1474 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1475 Stock Exchange
1476 United States of America
1477 York, North Yorkshire, England
1478 UK
1479 York, North Yorkshire, England
1480 null
1481 Kumasi, Kumasi Metropolitan, Ashanti
1482 New Mills, Derbyshire, East Midlands, England, SK22 3BN, UK
1483 Abasani
1484 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
1485 South Africa
1486 Manchester, Greater Manchester, North West England, England, UK
1487 Manchester, Lancashire, England
1488 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1489 Greater Accra
1490 Kaduna, Nigeria
1491 Coventry, West Midlands, England
1492 null
1493 Manchester, Lancashire, England
1494 null
1495 Shower Ct, Carmel, Indiana, 46032
1496 null
1497 Africa, Caldas
1498 null
1499 null
1500 Northampton, Northamptonshire, East Midlands, England, UK
1501 233
1502 Nairobi, Kenya
1503 Abuja Rd, Kaduna, Kaduna North, Kaduna
1504 Vijon, La Châtre, Indre, Centre-Val de Loire, France métropolitaine, 36160, France
1505 Nigeria
1506 England, UK
1507 Accra, Accra Metropolis, Greater Accra
1508 London, Greater London, England, UK
1509 Africa, Caldas
1510 Halifax, Yorkshire and the Humber, England, HX1 1TH, UK
1511 Overri, Imo State
1512 Nigeria
1513 Nigeria
1514 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
1515 Oxford, Oxfordshire, England
1516 Nairobi, Kenya
1517 Nairobi
1518 Bulawayo Province, Zimbabwe
1519 Mombasa
1520 K'Ogelo Market, E1159, Apouche, Siaya, Kenya
1521 Abuja, Abuja Municipal, Federal Capital Territory
1522 Free State, South Africa
1523 Nigeria
1524 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1525 Over World
1526 Lagos, Lagos Island, Lagos, 71510, Nigeria
1527 Manchester, Lancashire, England
1528 Mo, Slijkstraat, Weesp, Noord-Holland, Nederland, 1381, Nederland
1529 Right, Tennessee
1530 Smotherfly Wide, Amber Valley, Derbyshire, East Midlands, England, NG16 6PN, UK
1531 India
1532 Indonesia
1533 Durham, North Carolina
1534 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
1535 Manchester, Lancashire, England
1536 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
1537 Old Trafford, Manchester, Lancashire, England
1538 Cairo, Alexander County, Illinois, 62914, United States of America
1539 Dar es Salaam, Kinondoni, Dar es Salaam
1540 Manchester, Carroll County, Maryland, United States of America
1541 Denby Street, Sheffield, South Yorkshire, England, S2 4
1542 India
1543 Old Trafford, Manchester, Lancashire, England
1544 Miami, Miami-Dade County, Florida, United States of America
1545 United Arab Emirates
1546 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1547 Worldwide
1548 Corporation of Chennai, Chennai district, Tamil Nadu, India
1549 Channel Islands
1550 Jupiter, Palm Beach County, Florida, United States of America
1551 Kathmandu, Bagmati
1552 Somerset, Somerset Island, MA-05, Bermuda
1553 Highlight
1554 Santa Cruz de Tenerife, Canarias, España
1555 Windhoek, Khomas
1556 London, Greater London, England, UK
1557 New York
1558 Ghana
1559 Huddersfield, West Yorkshire, England
1560 Dortmund, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 44135, Deutschland
1561 Kaduna, Kaduna North, Kaduna
1562 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1563 Manchester, Lancashire, England
1564 null
1565 Trafford, Pennsylvania
1566 Seeta, Mukono, Central Region, 495, Uganda
1567 Marrakech
1568 null
1569 USA
1570 null
1571 GP
1572 Croydon, London, Greater London, England, CR0 1SZ, UK
1573 Paulista, Pernambuco
1574 London, Greater London, England, UK
1575 Surrey, Whalley, Surrey, British Columbia
1576 Jacksonville, Duval County, Florida, United States of America
1577 Reading, Berkshire, England
1578 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK

1579 MediaCityUK, Salford, Lancashire, England
1580 Singapore, Central, 178957, Singapore
1581 London, England
1582 null
1583 Yorkshire, England
1584 Brads House, Howard Avenue, Stevens Point, Portage County, Wisconsin, 54481, United States of America
1585 Simpson, Arkansas
1586 Malaysia
1587 Manchester, Lancashire, England
1588 Holmfirth, Yorkshire and the Humber, England, HD9 7DD, UK
1589 Leeds, West Yorkshire, England
1590 Huddersfield, Yorkshire and the Humber, England, HD1 2AA, UK
1591 Huddersfield, West Yorkshire, England
1592 Bradford, Yorkshire and the Humber, England, UK
1593 Tottenham, London, England
1594 Bank Of Africa Kisementi, Cooper Road, Kisementi, Kololo, Central, Kampala, Central Region, 24144, Uganda
1595 Nigeria
1596 Cleckheaton, Yorkshire and the Humber, England, BD19 3NU, UK
1597 California
1598 null
1599 Penrith, Cumbria, England
1600 Dublin, County Dublin, Leinster, Ireland
1601 Dublin
1602 Toronto, Ontario, Canada
1603 Huddersfield, West Yorkshire, England
1604 East Midlands, England, UK
1605 South Yorkshire, England
1606 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1607 Manchester, Lancashire, England
1608 Banbury, Oxon, South East, England, OX16 0AA, UK
1609 City
1610 Manchester, Meriwether County, Georgia, 31816, United States of America
1611 Wales
1612 Manchester, Greater Manchester, North West England, England, UK
1613 Mendes House
1614 The London Stadium, Bridge 4, Stratford Marsh, Newham, London, Greater London, England, E20 2AD, UK
1615 Revally, Midjil, Mahbubnagar, Telangana
1616 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
1617 Have, Pouy-Roquelaure, Gers, Occitanie
1618 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1619 Maryland
1620 Birkenhead, North West England, England, CH41 6JB, UK
1621 Yorkshire Park, Leeds, Alabama, 35094
1622 England, UK
1623 London, England
1624 null
1625 Slaithwaite, Huddersfield, West Yorkshire, England
1626 Earth, Lamb County, Texas, 79031, United States of America
1627 Huddersfield, West Yorkshire, England
1628 null
1629 Johannesburg, Gauteng
1630 null
1631 Huddersfield, West Yorkshire, England
1632 Solihull, West Midlands Combined Authority, West Midlands, England, UK
1633 San Siro, Milano
1634 null
1635 Accra, Accra Metropolis, Greater Accra
1636 null
1637 Accra, Accra Metropolis, Greater Accra
1638 Manchester, Greater Manchester, North West England, England, UK
1639 West End, Nelson Mandela Bay, Eastern Cape
1640 Marine Corps League Memorial Highway, Round Top, Adams County, Pennsylvania, 17325-8988, United States of America
1641 Huddersfield, West Yorkshire, England
1642 Melchester, Wavering Lane West, Gillingham, North Dorset, Dorset, South West England, England, SP8 4NR, UK
1643 Handle, Mississippi
1644 null
1645 Huddersfield, West Yorkshire, England
1646 West Midlands, Moyses Croft, Sandwell, West Midlands Combined Authority, West Midlands, England, B16, UK
1647 United Kingdom
1648 Norge, Ytterbyvegen, Namsos, Nord-Trøndelag, 7810, Norge
1649 Nigeria
1650 Solihull, West Midlands Combined Authority, West Midlands, England, UK
1651 Twitter
1652 Stockport, Greater Manchester, North West England, England, UK
1653 Lost, Lahitte-Toupière, Hautes-Pyrénées, Occitanie
1654 Kaduna, Nigeria
1655 Ksi
1656 Theatre Royal, 5, Westgate Street, Bury St. Edmunds, St Edmundsbury, Suffolk, East of England, England, IP33 1QR, UK
1657 Limerick
1658 Stillwater, Oklahoma, United States of America
1659 Kleinmond, Overberg, Western Cape
1660 Kaiseraugst, Bezirk Rheinfelden, Aargau, 4303, Schweiz/Suisse/Svizzera/Svizra
1661 Mombasa
1662 Henley-on-Thames, South Oxfordshire, Oxon, South East, England, UK
1663 Sunyani, Brong Ahafo
1664 Zaria, Kaduna, Nigeria
1665 Zaria, Kaduna
1666 New World, Parkvale, Havelock North, Hastings District, Hawke's Bay, New Zealand/Aotearoa
1667 Soweto Hwy, Diepkloof, Johannesburg, Gauteng, 1862
1668 Mars, Le Vigan, Gard, Occitanie, France métropolitaine, 30120, France
1669 Manchester, Lancashire, England
1670 Perth, Perth and Kinross, Scotland, PH1, UK
1671 Manchester United
1672 Lebanon, Lebanon County, Pennsylvania, United States of America
1673 Lincoln, Lincolnshire, England
1674 null
1675 null
1676 Indonesia
1677 Lebanon
1678 Ireland
1679 London, England
1680 Manchester, Greater Manchester, North West England, England, UK
1681 Manchester, Lancashire, England
1682 ‏پاکستان‎
1683 Kaduna, Kaduna North, Kaduna
1684 Amsterdam, Centrum, Amsterdam, Noord-Holland, Nederland
1685 Planet Earth Water
1686 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
1687 England
1688 Nairobi, Kenya
1689 Norton, Chegutu, Mashonaland West
1690 Wolverhampton, West Midlands Combined Authority, West Midlands, England, UK
1691 Medan, Sumatera Utara
1692 Lagos, Lagos Island, Lagos, 71510, Nigeria
1693 Coventry, West Midlands, England
1694 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
1695 United Kingdom
1696 Ghana
1697 المملكة العربية السعودية
1698 null
1699 Stockton, California
1700 null
1701 Gki Sulsel
1702 ڪراچي Karachi, Karāchi District, سنڌ, ‏پاکستان‎
1703 Manchester, Lancashire, England
1704 Nairobi, Kenya
1705 Lagos, Lagos Island, Lagos
1706 Manchester, Greater Manchester, North West England, England, UK
1707 Earth, Texas
1708 null
1709 London, England
1710 null
1711 Manchester, Lancashire, England
1712 Manchester, Greater Manchester, North West England, England, UK
1713 Nigeria
1714 Uyo, Akwa Ibom, Nigeria
1715 Phoenix, Arizona
1716 Manchester, Greater Manchester, North West England, England, UK
1717 Indonesia
1718 Illinois, United States of America
1719 Tanzania
1720 ‏پاکستان‎
1721 null
1722 Roseville, Regional Municipality of Waterloo, Ontario, N2R0A4, Canada
1723 Tanzania
1724 null
1725 Tanzania
1726 Islington, London Borough of Islington, London, Greater London, England, N1, UK
1727 Dublin
1728 Beach House, King's Lynn and West Norfolk, Norfolk, East of England, England, PE31 7PS, UK
1729 Ogden, Utah
1730 Sverige
1731 Where
1732 England, UK
1733 null
1734 Harare, Harare Province, 0000, Zimbabwe
1735 World
1736 null
1737 London, England
1738 Africa
1739 York Street, Dublin 2, Dublin
1740 Dublin, County Dublin, Leinster, Ireland
1741 Lurgan, Leinster
1742 Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, España
1743 United States
1744 null
1745 South Africa
1746 Manchester, Greater Manchester, North West England, England, UK
1747 Nigeria, eThekwini, Kwazulu Natal
1748 Corporation of Chennai, Chennai district, Tamil Nadu, India
1749 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
1750 Manchester, Greater Manchester, North West England, England, UK
1751 Goole, North Humberside, England
1752 Chicago, Cook County, Illinois, United States of America
1753 Essex, Maryland
1754 Teater Tanah Airku, Taman Mini, Taman Mini Indonesia Indah (TMII), Cipayung, Jakarta Timur, Daerah Khusus Ibukota Jakarta, 13840, Indonesia
1755 Nairobi
1756 London, Greater London, England, UK
1757 Islamic Republic of Iran
1758 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
1759 Nairobi
1760 Moyale Airport, C80, Marsabit, Kenya
1761 Shropshire, England
1762 Somewhere, 93, Rue du Commerce, Grenelle, 15e, Paris, Île-de-France, France métropolitaine, 75015, France
1763 Liverpool, Merseyside, England
1764 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1765 United Kingdom
1766 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1767 United Kingdom
1768 Southend-on-Sea, East of England, England, UK
1769 Manchester, Lancashire, England
1770 null
1771 Miami, Florida
1772 Here, Općina Prozor, Hercegovačko-neretvanska županija/kanton, Federacija Bosne i Hercegovine, Bosna i Hercegovina / Босна и Херцеговина
1773 Lagos, Lagos Island, Lagos
1774 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
1775 Cloud 9
1776 Manchester, Greater Manchester, North West England, England, UK
1777 Williston Close, East Denton, Newcastle, Tyne and Wear, England, NE5 2
1778 null
1779 茨城県守谷市薬師台７
1780 Dortmund, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 44135, Deutschland

1781 England
1782 England, UK
1783 Accra, Accra Metropolis, Greater Accra
1784 Goa, India
1785 England
1786 null
1787 Old Trafford, Manchester, Lancashire, England
1788 Okun-Ajah Road, Mopo-Akinlade, Eti Osa, Lagos, Nigeria
1789 Accra, Accra Metropolis, Greater Accra
1790 Nairobi, Kenya
1791 Islington, London, England
1792 London, Greater London, England, UK
1793 George Town, Grand Cayman
1794 New Jersey, United States of America
1795 South East Asia
1796 Antwerpen, Vlaanderen, België - Belgique - Belgien
1797 United Kingdom
1798 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1799 England
1800 Nakuru, Kenya
1801 Accra, Accra Metropolis, Greater Accra
1802 London, Greater London, England, UK
1803 UK
1804 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1805 Karachi, Karāchi District, Sindh
1806 221b Baker Street, 20, Rue Monge, Faubourg Raines, Centre-Ville, Dijon, Côte-d'Or, Bourgogne-Franche-Comté, France métropolitaine, 21000, France
1807 Mumbai, Maharashtra
1808 MLK, Malaysia
1809 Italy
1810 United States of America
1811 Lagos, Lagos Island, Lagos
1812 Manchester, Greater Manchester, North West England, England, UK
1813 Accra, Accra Metropolis, Greater Accra
1814 null
1815 Bengaluru, Karnataka
1816 Heaven, Villiers Street, St Clement Danes, Covent Garden, City of Westminster, London, Greater London, England, WC2N 6NG, UK
1817 London, England
1818 Manchester, Greater Manchester, North West England, England, UK
1819 Westerose, Wetaskiwin County No 10, Alberta
1820 Zimbabwe
1821 Manchester, Lancashire, England
1822 Lagos, Lagos Island, Lagos, 71510, Nigeria
1823 Reading, Berkshire, England
1824 Pune, Maharashtra, 411001, India
1825 Wolverhampton, West Midlands, England
1826 null
1827 Manchester, Lancashire, England
1828 England, UK
1829 United Kingdom
1830 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1831 United Kingdom
1832 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1833 England
1834 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1835 United Kingdom
1836 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1837 United Kingdom
1838 England, UK
1839 United Kingdom
1840 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1841 United Kingdom
1842 England, UK
1843 United Kingdom
1844 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1845 Kathmandu, Bagmati
1846 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
1847 Manchester, Lancashire, England
1848 London, Greater London, England, UK
1849 Lagos Close, Rusholme, Manchester, Lancashire, England, M14 4
1850 Manchester, Greater Manchester, North West England, England, UK
1851 Nigeria
1852 Heaven, Villiers Street, St Clement Danes, Covent Garden, City of Westminster, London, Greater London, England, WC2N 6NG, UK
1853 Erehwon
1854 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
1855 Nice, Alpes-Maritimes, Provence-Alpes-Côte d'Azur
1856 Zimbabwe
1857 Manchester, Lancashire, England
1858 Manchester, Greater Manchester, North West England, England, UK
1859 IN
1860 null
1861 United Kingdom
1862 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1863 Wigan, Lancashire, England
1864 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
1865 West Coast
1866 England, UK
1867 Manchester, Lancashire, England
1868 Cardiff, Wales, CF, UK
1869 Venezuela
1870 Kota Surabaya, Ranai, Kepulauan Riau, Indonesia
1871 Africa
1872 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
1873 Global Net
1874 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1875 London, England
1876 Nairobi, Kenya
1877 Abuja, Abuja Municipal, Federal Capital Territory
1878 Guwahati, Kamrup, Assam, 781015, India
1879 Ghana
1880 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
1881 IN
1882 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1883 Nakuru
1884 Bradford, Yorkshire and the Humber, England, UK
1885 Los Angeles, California
1886 Ghana
1887 Port Harcourt, Rivers
1888 Bristol, City of Bristol, South West England, England, UK
1889 Bristol, Avon, England
1890 Jakarta, Gambir, Jakarta Pusat, Daerah Khusus Ibukota Jakarta, 10110, Indonesia
1891 Barnsley, South Yorkshire, England
1892 Europe
1893 Ig, Ljubljana
1894 Europe
1895 Jamaica
1896 null
1897 London, England
1898 London, Greater London, England, UK
1899 Pune, Maharashtra
1900 kd, Old Trail to Mt Arayat North Peak, Baluga Village, Pampanga, Central Luzon, 2011, Philippines
1901 Sheffield, South Yorkshire, England
1902 Mauritius
1903 Worldwide
1904 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
1905 Malaysia
1906 Liverpool, North West England, England, UK
1907 Ghana
1908 Danmark
1909 North Pole, Alaska
1910 กรุงเทพมหานคร, ประเทศไทย
1911 South East, England
1912 Manchester, Greater Manchester, North West England, England, UK
1913 Abuja, Abuja Municipal, Federal Capital Territory
1914 null
1915 Canberra, Australian Capital Territory
1916 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
1917 Nigeria
1918 Paris, Île-de-France, France métropolitaine, France
1919 Dakar
1920 Manchester, Greater Manchester, North West England, England, UK
1921 ณุ
1922 YouTube, 1000, Cherry Avenue, YouTube, San Bruno, San Mateo County, California, 94066, United States of America
1923 Ghana
1924 Chicago, Cook County, Illinois, United States of America
1925 Dodowa Road, Accra, Accra Metropolis, Greater Accra
1926 Cave, RM, LAZ, Italia
1927 Kaduna, Kaduna North, Kaduna
1928 null
1929 Manchester, Lancashire, England
1930 Austin, Travis County, Texas, United States of America
1931 Compound, Ehlanzeni District, Mpumalanga
1932 null
1933 Manchester United Methodist Church
1934 Nigeria
1935 Lagos, Lagos Island, Lagos
1936 Wheaton, DuPage County, Illinois, United States of America
1937 Lagos, Lagos Island, Lagos
1938 Banten, Indonesia
1939 Lagos, Lagos Island, Lagos
1940 null
1941 Portharcourt Zoo
1942 null
1943 Take, Lagos
1944 Manchester, Greater Manchester, North West England, England, UK
1945 Dubai
1946 Bergen, Hordaland, Norge
1947 Nairobi
1948 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
1949 Lagos, Lagos Island, Lagos
1950 Indonesia
1951 Accra, Accra Metropolis, Greater Accra
1952 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
1953 Eight Mile, Alabama
1954 Lagos, Lagos Island, Lagos, 71510, Nigeria
1955 Ibadan, Oyo
1956 Coventry, West Midlands Combined Authority, West Midlands, England, UK
1957 Greater Accra
1958 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
1959 United Kingdom
1960 Lagos, Lagos Island, Lagos, 71510, Nigeria
1961 United States
1962 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
1963 Old Trafford, Manchester, Lancashire, England
1964 null
1965 Lagos, Lagos Island, Lagos
1966 Kaduna, Nigeria
1967 Arkansas
1968 Nairobi, Kenya
1969 ST, Nordrhein-Westfalen
1970 Tamil Nadu, India
1971 Africa, Caldas
1972 Planet Earth, SR 14, Edinburg, Edinburg Township, Portage County, Ohio, United States of America
1973 Old Trafford, Manchester, Lancashire, England
1974 null
1975 United Kingdom
1976 Canada
1977 Nigeria
1978 Nigeria
1979 Abuja, Abuja Municipal, Federal Capital Territory
1980 Tamil Nadu, India
1981 Breaks, Virginia
1982 NYC, New York, United States of America
1983 London, England
1984 null
1985 United Kingdom
1986 null
1987 Guadalajara, Jalisco
1988 Mauritius
1989 Nairobi
1990 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
1991 United Kingdom
1992 Sonarpur, Sonarpur Station Road, Kolkata, Twenty-four Parganas, West Bengal, 700150, India
1993 Side Street, Clayton, Manchester, Lancashire, England, M11 4
1994 Burco برعو, توجدير Togdheer, جمهورية أرض الصومال Jamhuuriyadda Soomaaliland, Soomaaliya الصومال
1995 Maluku
1996 PJ, Selangor, 462000, Malaysia
1997 Mumbai, Maharashtra
1998 Garden City, Finney County, Kansas, United States of America

1999 Ghana
2000 Lagos, Lagos Island, Lagos, 71510, Nigeria
2001 Lagos, Lagos Island, Lagos
2002 Serang, Banten, Indonesia
2003 Orlando, Florida
2004 Sarawak, Malaysia
2005 Ireland
2006 Manchester, Greater Manchester, North West England, England, UK
2007 Twitter
2008 Cave, RM, LAZ, Italia
2009 United Kingdom
2010 Corporation of Chennai, Chennai district, Tamil Nadu, India
2011 United Kingdom
2012 Jakarta, Gambir, Jakarta Pusat, Daerah Khusus Ibukota Jakarta, 10110, Indonesia
2013 Sotogrande, Provincia de Ourense, Galicia
2014 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2015 Nigeria
2016 Sydney, NSW, Australia
2017 Redmond, Washington
2018 Manchester, Greater Manchester, North West England, England, UK
2019 Nyeri
2020 झापा जिल्ला, मेची अञ्चल, पुर्वाञ्चल विकास क्षेत्र, नेपाल
2021 Minna, Chanchaga, Niger
2022 Bengaluru, Bangalore Urban, Karnataka, 560001, India
2023 Right, Tennessee
2024 Cardiff, Wales, CF, UK
2025 null
2026 2nd, Upchurch, Swale, Kent, South East, England, UK
2027 Scotland
2028 Lagos, Lagos Island, Lagos, 71510, Nigeria
2029 Lagos, Lagos Island, Lagos
2030 England, UK
2031 East
2032 Southend-on-Sea, East of England, England, UK
2033 Manchester, Lancashire, England
2034 Hill Valley, Terrick Road, Whitchurch Urban, Shropshire, West Midlands, England, SY13 4LA, UK
2035 Bedfordshire, England
2036 Setapak, KL, 53000, Malaysia
2037 null
2038 UK
2039 Klang, Selangor
2040 Bojonegoro, Jalan Gajah Mada, Sukorejo, Jawa Timur, 62118, Indonesia
2041 Liverpool, Merseyside, England
2042 London, Greater London, England, UK
2043 Gki Sulsel
2044 Paraguay
2045 Benin City, Oredo, Edo
2046 Chesterfield, Derbyshire, East Midlands, England, UK
2047 Manchester, Lancashire, England
2048 Lagos, Lagos Island, Lagos, 71510, Nigeria
2049 Ciudad de Guatemala, Guatemala
2050 Toronto, Ontario, Canada
2051 Chesterfield, Derbyshire, England
2052 Manchester, Greater Manchester, North West England, England, UK
2053 Chesterfield, Derbyshire, England
2054 null
2055 Murrell, Ephrata, Pennsylvania
2056 Manchester, Greater Manchester, North West England, England, UK
2057 Manchester, Lancashire, England
2058 Chesterfield, Derbyshire, East Midlands, England, UK
2059 Lagos State, Lagos
2060 Sheffield, Yorkshire and the Humber, England, UK
2061 Canada
2062 Manchester, Greater Manchester, North West England, England, UK
2063 Tokyo東京
2064 Canada
2065 England
2066 Chemin de Fer de Dieppe au Havre, D 150, Valmont, Le Havre, Seine-Maritime, Normandie, France métropolitaine, 76540, France
2067 Abrego, Norte de Santander
2068 Nairobi, Kenya
2069 Proact Stadium
2070 Manchester, Greater Manchester, North West England, England, UK
2071 Île-de-France
2072 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2073 United Kingdom
2074 Zamfara, Nigeria
2075 Zamfara
2076 Zamfara, Nigeria
2077 Zamfara
2078 Kaduna, Nigeria
2079 Aberdeen, Aberdeenshire, Scotland
2080 Lagos, Lagos Island, Lagos, 71510, Nigeria
2081 Jamaica
2082 Lagos, Lagos Island, Lagos, 71510, Nigeria
2083 Nigeria
2084 Places, VDA, Italia
2085 02152
2086 Indonesia, Kalimantan Barat, Indonesia
2087 United Kingdom
2088 Quintana, Microrregião de Tupã, Mesorregião de Marília, SP, Região Sudeste, 17670000, Brasil
2089 London, England
2090 null
2091 Nigeria
2092 null
2093 Rio de Janeiro
2094 null
2095 Santos, São Paulo
2096 Sindelfingen, Landkreis Böblingen, Regierungsbezirk Stuttgart, Baden-Württemberg, Deutschland
2097 Fife, Scotland
2098 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2099 Manchester, Lancashire, England
2100 Ireland
2101 London, England
2102 null
2103 İn, Hozat, Tunceli
2104 Rochester, Monroe County, New York, 14614, United States of America
2105 Abeokuta, Abeokuta South, Ogun
2106 Lagos, Lagos Island, Lagos, 71510, Nigeria
2107 Dar es Salaam, Kinondoni, Dar es Salaam
2108 Melbourne, City of Melbourne, Greater Melbourne, Victoria, 3000, Australia
2109 null
2110 null
2111 Kampala
2112 Mordor, Bronowice Nowe, Mydlniki, Bronowice, Kraków, małopolskie, RP
2113 Manchester United
2114 Foxborough, Norfolk County, Massachusetts, 02035, United States of America
2115 El Morador, Mérida
2116 Salta, Municipio de Salta, Capital, SA, Argentina
2117 Lagos, Lagos Island, Lagos
2118 Cloud 9, Sierra Vista, Cochise County, Arizona, United States of America
2119 Dundee, Angus, Scotland
2120 Lagos, Lagos Island, Lagos, 71510, Nigeria
2121 Top, Daniawan, Patna, Bihar
2122 Nigeria
2123 Sulawesi Tengah
2124 null
2125 Nevers, Nièvre, Bourgogne-Franche-Comté
2126 Lagos, Lagos Island, Lagos, 71510, Nigeria
2127 Tanzania
2128 MY ROOM, Service Road, Maduravoyal, Corporation of Chennai, Thiruvallur district, Tamil Nadu, 600037, India
2129 GH
2130 Nigeria
2131 02152
2132 Manchester, Greater Manchester, North West England, England, UK
2133 Dublin city, Dublin, Leinster
2134 Manchester, Greater Manchester, North West England, England, UK
2135 Bénin
2136 Smotherfly Wide, Amber Valley, Derbyshire, East Midlands, England, NG16 6PN, UK
2137 Walthamstow, London, England
2138 Foxhall ED, Lurgan, County Longford, Leinster, Ireland
2139 Chicago, Illinois
2140 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2141 Selalu, Sichuan
2142 London, Greater London, England, UK
2143 South Western Crescent, Parkstone, Poole, Dorset, England, BH14 8
2144 Junipero, Laderas de San Miguel, General Escobedo, Nuevo León, México
2145 Berkshire, England
2146 England, UK
2147 Samsara, Bihta, Patna, Bihar
2148 Wirral, North West England, England, UK
2149 Littleborough, Lancashire, England
2150 Coonoor, The Nilgiris, The Nilgiris district, Tamil Nadu, 643101, India
2151 Takoradi, Sekondi-Takoradi, Shama Ahanta East Metropolitan, Western
2152 Excalibur Estate, Catford South, London Borough of Lewisham, London, Greater London, England, SE6, UK
2153 England
2154 null
2155 Accra, Accra Metropolis, Greater Accra
2156 Yogyakarta, Indonesia
2157 London, England
2158 England, UK
2159 England
2160 London, Greater London, England, UK
2161 Liberia
2162 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
2163 Osun State, Osun
2164 null
2165 Lagos, Lagos Island, Lagos
2166 null
2167 Lagos, Lagos Island, Lagos
2168 Manchester, Greater Manchester, North West England, England, UK
2169 null
2170 Semarang, Jawa Tengah, 50241, Indonesia
2171 Worldwide
2172 Scotland, UK
2173 Москва
2174 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2175 England
2176 Manchester, Greater Manchester, North West England, England, UK
2177 Jalingo, Taraba
2178 null
2179 Singapore, Bukal, Pagbilao, Quezon, Calabarzon
2180 Camden Town, London, Greater London, England, NW1 9PJ, UK
2181 South East, England
2182 Nigeria
2183 Nigeria
2184 London, Greater London, England, UK
2185 Stock Exchange
2186 Battersea, London Borough of Wandsworth, London, Greater London, England, SW11 3HW, UK
2187 Abuja, Abuja Municipal, Federal Capital Territory
2188 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
2189 Moving on
2190 South Wales, Erie County, New York, 14139, United States of America
2191 Jasmin, Nord-Ouest
2192 LDN, Maďarská, Bubeneč, Praha, okres Hlavní město Praha, Hlavní město Praha, Praha, 1, Česko
2193 Nerul, Navi Mumbai, Thane, Maharashtra
2194 Hale County, Alabama, United States of America
2195 Scotland
2196 Kapsabet, Nandi, Kenya
2197 Neptuno, Ciudad de La Habana
2198 Dublin, County Dublin, Leinster, Ireland
2199 Old Trafford, Manchester, Lancashire, England
2200 Ghana
2201 Kapsabet, Nandi
2202 بغداد, الكرخ, محافظة بغداد, العراق
2203 Wife's
2204 Nigeria
2205 Lagos, Lagos Island, Lagos
2206 Salford, Greater Manchester, North West England, England, UK
2207 Lagos, Lagos Island, Lagos
2208 null
2209 Abuja, Abuja Municipal, Federal Capital Territory
2210 null
2211 New Jersey
2212 New Jersey, United States of America
2213 Manchester, Lancashire, England
2214 Morogoro, Coastal, 6284, Tanzania
2215 United Kingdom
2216 New Jersey, United States of America
2217 Salvador, Bahia
2218 China, Nuevo León, México
2219 Hong Kong
2220 null
2221 Wia
2222 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
2223 Abuja
2224 नेपाल
2225 Ahmedabad, Gujarat
2226 Kumasi, Ashanti Region, Ghana

2227 Cardiff, South Glamorgan, Wales
2228 null
2229 Manchester, Lancashire, England
2230 null
2231 Nigeria
2232 null
2233 The Father
2234 Great Britain, Richmondshire, North Yorkshire, Yorkshire and the Humber, England, UK
2235 Worldwide
2236 World, Governor Drive, University City, San Diego, San Diego County, California, 92037, United States of America
2237 Here I Am
2238 Houston, Harris County, Texas, 77002, United States of America
2239 Benin City, Oredo, Edo
2240 Manchester, Greater Manchester, North West England, England, UK
2241 Stay Cool
2242 Kolkata, Hāora, West Bengal, 700021, India
2243 Manchester, Lancashire, England
2244 null
2245 Vasai, Palghar, Maharashtra
2246 Yogyakarta, Prawirodirjan, Gondomanan, Kota Yogyakarta, Daerah Istimewa Yogyakarta, 55122, Indonesia
2247 New Delhi, Connaught Place, New Delhi, Delhi
2248 Nigeria
2249 Salisbury, Wiltshire, England
2250 Lagos, Lagos Island, Lagos, 71510, Nigeria
2251 United Kingdom
2252 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2253 null
2254 null
2255 Thailand
2256 Yogyakarta, Indonesia
2257 Stamford Bridge, York, North Yorkshire, England
2258 Cibinong, Jawa Barat, 15315, Indonesia
2259 Celle, Niedersachsen
2260 City of Nottingham, East Midlands, England, UK
2261 Adamawa
2262 DKI JAKARTA, Jalan Pulo Gebang Indah Blok J, RW 04, Pulo Gebang, Cakung, Jakarta Timur, Daerah Khusus Ibukota Jakarta, 13910, Indonesia
2263 Graveyard, Saint Lucy
2264 London, Greater London, England, UK
2265 Old Trafford, Manchester, Lancashire, England
2266 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2267 There, Umrangso, Dima Hasao, Assam
2268 Dublin, County Dublin, Leinster, Ireland
2269 Germany
2270 Mandalay, မြန်မာ
2271 Jakarta Selatan, Kebayoran Baru, Jakarta, DKI Jakarta
2272 null
2273 Way, Mississippi
2274 Manchester, Greater Manchester, North West England, England, UK
2275 Ghana
2276 Carlisle, Cumbria, North West England, England, UK
2277 Old Trafford, Manchester, Lancashire, England
2278 California, United States of America
2279 Old Trafford, Manchester, Lancashire, England
2280 London, Greater London, England, UK
2281 Shah Alam, Seksyen 7, Shah Alam, Petaling, Selangor
2282 Nigeria
2283 Pokhara, Western Region
2284 Kumasi, Ashanti Region, Ghana
2285 US Virgin Islands
2286 Africa Lane, Maroko, Moba, Eti Osa, Lagos, Nigeria
2287 Mumbai, Maharashtra
2288 Manchester, Greater Manchester, North West England, England, UK
2289 Valle de la Pascua, Leonardo Infante, Guárico
2290 Indore, Madhya Pradesh, India
2291 Manchester, Lancashire, England
2292 ICT, ‏پاکستان‎
2293 Manchester, Lancashire, England
2294 ‏پاکستان‎
2295 Old Trafford, Manchester, Lancashire, England
2296 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
2297 Indonesia
2298 Manchester, Greater Manchester, North West England, England, UK
2299 Ghana
2300 Nairobi, Kenya
2301 Manchester, Lancashire, England
2302 Skipton, North Yorkshire, Yorkshire and the Humber, England, BD23 1DU, UK
2303 Int
2304 Uhuru Peak, Rombo, Kilimanjaro, Tanzania
2305 London, England
2306 null
2307 Manchester, Lancashire, England
2308 Lagos, Lagos Island, Lagos, 71510, Nigeria
2309 Lagos, Lagos Island, Lagos
2310 UK
2311 Manchester, Lancashire, England
2312 Lagos, Lagos Island, Lagos, 71510, Nigeria
2313 Buenos Aires, Ciudad Autónoma de Buenos Aires
2314 Manchester, Greater Manchester, North West England, England, UK
2315 Mumbai, Maharashtra
2316 UK
2317 United States
2318 Don Mueang, ถนนวิภาวดีรังสิต, หลักสี่, กรุงเทพมหานคร, เขตจตุจักร, กรุงเทพมหานคร, 10900, ประเทศไทย
2319 Manchester, Lancashire, England
2320 Kenya
2321 Ipswich, Suffolk, England
2322 Iceland, 141-145, High Street, Brompton, Gillingham, Medway, South East, England, ME7 1AQ, UK
2323 Enugu, Enugu North, Enugu
2324 null
2325 Plymouth, Devon, England
2326 Corporation of Chennai, Chennai district, Tamil Nadu, India
2327 Manchester, Lancashire, England
2328 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2329 Western Region, Western
2330 Mother Land, Sri R. Nanjundappa Road, Chelekere, Hennur, Bengaluru, Bangalore Urban, Karnataka, 560001, India
2331 Classified
2332 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
2333 Chicago, Illinois
2334 Bengaluru, Bangalore Urban, Karnataka, 560001, India
2335 Pretoria, Tshwane, Gauteng
2336 Birkenhead, North West England, England, CH41 6JB, UK
2337 UK
2338 null
2339 Hoopla
2340 Ireland
2341 Stirling Road, London, England, N17 9
2342 Swinton, Greater Manchester, North West England, England, M27 0WN, UK
2343 Nigeria
2344 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2345 null
2346 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
2347 Abuja, Abuja Municipal, Federal Capital Territory
2348 null
2349 Bénin
2350 Nigeria
2351 Eight Mile, Alabama
2352 Benin City, Oredo, Edo, Nigeria
2353 Byblos, Mont-Liban
2354 Benin City, Oredo, Edo, Nigeria
2355 India
2356 阪神高速14号松原線, 阿倍野区, 大阪市港区, 大阪府, 5500014, 日本
2357 Cambridge, Massachusetts
2358 UK
2359 Akure, Akure South, Ondo
2360 221b Baker Street, 20, Rue Monge, Faubourg Raines, Centre-Ville, Dijon, Côte-d'Or, Bourgogne-Franche-Comté, France métropolitaine, 21000, France
2361 London, England
2362 London, Greater London, England, UK
2363 Cardiff, South Glamorgan, Wales
2364 null
2365 Mawillian Road, Moneyneany, Magherafelt, County Londonderry, Northern Ireland, BT45 7
2366 Nigeria
2367 The Poolside
2368 Manchester, Greater Manchester, North West England, England, UK
2369 Göteborg
2370 Lagos, Lagos Island, Lagos, 71510, Nigeria
2371 The Trenches
2372 High and Mighty, Vicar Lane, Steander, Lovell Park, Leeds, Yorkshire and the Humber, England, LS2 7QY, UK
2373 GH
2374 دبي, دبي‎, الإمارات العربيّة المتّحدة
2375 San Siro, Milano
2376 null
2377 Cape Town, Western Cape
2378 Nigeria
2379 Indonesia
2380 Dallas, Dallas County, Texas, United States of America
2381 Surat, Gujarat
2382 Barcelona, BCN, CAT, España
2383 Sheffield, South Yorkshire, England
2384 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2385 Manchester, Lancashire, England
2386 Australia
2387 Port Elizabeth, Nelson Mandela Bay, Eastern Cape
2388 London, Greater London, England, UK
2389 Leeds, West Yorkshire, England
2390 Türkiye
2391 Abuja, Abuja Municipal, Federal Capital Territory
2392 กรุงเทพมหานคร, ประเทศไทย
2393 São Paulo
2394 Comfort Zone, 480, Spadina Avenue, Kensington Market, Old Toronto, Toronto, Ontario, M5S 2H1, Canada
2395 Budapest
2396 null
2397 Accra, Accra Metropolis, Greater Accra
2398 São Bernardo do Campo, Microrregião de São Paulo, RMSP, Mesorregião Metropolitana de São Paulo, SP, Região Sudeste, Brasil
2399 London, England
2400 null
2401 Penthouse
2402 Nigeria
2403 Manchester, Lancashire, England
2404 Quintana, Microrregião de Tupã, Mesorregião de Marília, SP, Região Sudeste, 17670000, Brasil
2405 Sir Matt Busby
2406 Sydney, NSW, Australia
2407 Beal Feirste, Belfast, City of Belfast, N Ireland
2408 Warwickshire, West Midlands, England, UK
2409 Greater Accra
2410 Lagos, Lagos Island, Lagos, 71510, Nigeria
2411 Nigeria
2412 Nigeria
2413 Ibadan, Oyo
2414 Indonesia
2415 Sydney, New South Wales
2416 Cardiff, Wales, CF, UK
2417 Northern Ireland
2418 Manchester, Greater Manchester, North West England, England, UK
2419 KE
2420 Nigeria
2421 London, England
2422 Ahmedabad, Ahmadabad, Gujarat, 380001, India
2423 UK
2424 Nairobi, Kenya
2425 UK
2426 Canary Wharf, West Plaza, Isle of Dogs, London Borough of Tower Hamlets, London, Greater London, England, E14 5AJ, UK
2427 Boutiliers Point, Halifax, Nova Scotia
2428 Portsmouth Road, Seething Wells, Surbiton, Kingston-upon-Thames, London, Greater London, England, KT10, UK
2429 Otta, Ogun
2430 Kuching, Kuching Division, Sarawak, 93XXX, Malaysia
2431 Pontypridd, Mid Glamorgan, Wales
2432 South Africa
2433 United Kingdom
2434 Somalia, Huambo, Angola
2435 Unknown
2436 null
2437 Right, Tennessee
2438 Raub, Pahang, Malaysia
2439 Nottingham, Nottinghamshire, England
2440 Manchester, Greater Manchester, North West England, England, UK
2441 UK
2442 Nigeria
2443 United Kingdom
2444 City of Nottingham, East Midlands, England, UK
2445 Rotunda, Olt
2446 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK

2447 Essex, Maryland
2448 Україна
2449 Game
2450 Colchester, Essex, East of England, England, UK
2451 United Kingdom
2452 London, Greater London, England, UK
2453 Damaturu, Yobe
2454 London, Greater London, England, UK
2455 London, England
2456 Manchester, Greater Manchester, North West England, England, UK
2457 Singapore
2458 London, Greater London, England, UK
2459 Neverland
2460 null
2461 Newcastle, New South Wales
2462 Boink!, Drottningholmsvägen, Riksby, Bromma stadsdelsområde, Sthlm, Stockholm, Landskapet Uppland, Stockholms län, Svealand, 22109, Sverige
2463 Fellows, California
2464 ...and kingdom come..., Devils Gullet Track, Devonport, Tasmania, 7310, Australia
2465 Field, Columbia-Shuswap, British Columbia
2466 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
2467 Accra, Accra Metropolis, Greater Accra
2468 Singapore, Central, 178957, Singapore
2469 Ldn
2470 Carrington Lane, Carrington, Trafford, Greater Manchester, North West England, England, M31 4AD, UK
2471 NG
2472 Essex, East of England, England, UK
2473 Carrington Lane, Urmston, Manchester, Lancashire, England, M33 5
2474 Scotland, UK
2475 Nigeria
2476 Tynemouth, Tyne and Wear, North East England, England, NE30 4DQ, UK
2477 Worldwide
2478 World, Governor Drive, University City, San Diego, San Diego County, California, 92037, United States of America
2479 Stamford Bridge, York, North Yorkshire, England
2480 London, Greater London, England, UK
2481 Victoria Island
2482 null
2483 Sydney, New South Wales
2484 Lagos, Lagos Island, Lagos, 71510, Nigeria
2485 Motherland
2486 Newbury, West Berkshire, South East, England, RG14 1DJ, UK
2487 Scotland
2488 Oshakati, Oshana Region, Namibia
2489 Dashţūţ, Banī Suwayf
2490 Amsterdam Road, Cubitt Town, London Borough of Tower Hamlets, London, Greater London, England, E14 3GQ, UK
2491 Stockheim
2492 Canton Exaltación, Beirut, Provincia de Yacuma, BNI, Bolivia
2493 Scotland
2494 London, Greater London, England, UK
2495 Northamptonshire, England
2496 Dublin, County Dublin, Leinster, Ireland
2497 United Kingdom
2498 Southend-on-Sea, East of England, England, UK
2499 Kumasi, Kumasi Metropolitan, Ashanti
2500 null
2501 Dublin
2502 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2503 Manchester, Lancashire, England
2504 London, Greater London, England, UK
2505 Manchester, Lancashire, England
2506 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
2507 चेन्नई, तमिल नाडु
2508 Manchester, Greater Manchester, North West England, England, UK
2509 London, England
2510 London, Greater London, England, UK
2511 London, England
2512 Manchester, Greater Manchester, North West England, England, UK
2513 United Kingdom
2514 Singapore, Central, 178957, Singapore
2515 Liverpool, Merseyside, England
2516 Corporation of Chennai, Chennai district, Tamil Nadu, India
2517 Belfast, County Antrim, Northern Ireland
2518 null
2519 Cape Town, Western Cape
2520 Mumbai, Greater Bombay, Maharashtra, 400001, India
2521 Stretford Road, Old Trafford, Manchester, Lancashire, England, M16 0
2522 Kul Circle South, Hilliard, Franklin County, Ohio, 43026, United States of America
2523 Pune, Maharashtra
2524 null
2525 Way, Mississippi
2526 null
2527 Cardiff, South Glamorgan, Wales
2528 Coburg, Oberfranken, Bayern, 96450, Deutschland
2529 Johannesburg, Gauteng
2530 Manchester, Greater Manchester, North West England, England, UK
2531 Accra, Accra Metropolis, Greater Accra
2532 null
2533 Ireland
2534 Broughton, Flintshire, Wales, CH4 0QN, UK
2535 Getting Off
2536 Mumbai, Greater Bombay, Maharashtra, 400001, India
2537 United Kingdom
2538 Manchester, Greater Manchester, North West England, England, UK
2539 United Kingdom
2540 Manchester, Greater Manchester, North West England, England, UK
2541 London, England
2542 null
2543 England
2544 null
2545 South Western Crescent, Parkstone, Poole, Dorset, England, BH14 8
2546 Melbourne, City of Melbourne, Greater Melbourne, Victoria, 3000, Australia
2547 Men City
2548 Glasgow City, Scotland, UK
2549 Sheffield, South Yorkshire, England
2550 London, Greater London, England, UK
2551 Canada
2552 İzmir, Ege Bölgesi, 35240, Türkiye
2553 England
2554 London, Greater London, England, UK
2555 Crawley, West Sussex, England
2556 Folkestone, Kent, South East, England, CT19 5JF, UK
2557 Manchester, Lancashire, England
2558 Nelson Street, New Islington, Collyhurst, Manchester, Greater Manchester, North West England, England, M40 8DP, UK
2559 Swaziland
2560 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
2561 Bāgh, Madhya Pradesh
2562 Dublin, County Dublin, Leinster, Ireland
2563 Darwin, Northern Territory
2564 Glasgow City, Scotland, UK
2565 Manhattan, New York
2566 Morogoro, Coastal, 6284, Tanzania
2567 Cheshire Ct, Manchester Township, New Jersey, 08759
2568 null
2569 South Africa
2570 Shillong, East Khasi Hills, Meghalaya, 793001, India
2571 Wide Street
2572 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2573 London, England
2574 null
2575 Doha, Al Doha
2576 สาทร, แขวงสีลม, เขตบางรัก, กรุงเทพมหานคร, 10500, ประเทศไทย
2577 Lagos, Lagos Island, Lagos
2578 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2579 Leeds, West Yorkshire, England
2580 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
2581 Nairobi
2582 null
2583 Nairobi
2584 Pune, Maharashtra, 411001, India
2585 Nigeria
2586 null
2587 Россия
2588 Outside the Box, 4, Werner-Heisenberg-Straße, Cramerton, Kriegshaber, Augsburg, Schwaben, Bayern, 86156, Deutschland
2589 OKH
2590 null
2591 Swakopmund, Erongo
2592 England, UK
2593 Manchester United
2594 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2595 World
2596 Natural Resources Canada Earth Sciences, 615, Booth Street, Little Italy, Centretown, Somerset, Ottawa, Ontario, K1R 7L2, Canada
2597 United Kingdom
2598 Lagos, Lagos Island, Lagos, 71510, Nigeria
2599 Global, Ehlanzeni, Mpumalanga
2600 Manchester, Greater Manchester, North West England, England, UK
2601 Nigeria
2602 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2603 New York
2604 null
2605 In Living
2606 null
2607 United Kingdom
2608 Lagos, Lagos Island, Lagos, 71510, Nigeria
2609 Nigeria
2610 Yola, Jama'Are, Bauchi, Nigeria
2611 Chennai, Tamil Nadu
2612 null
2613 Kano Cres, Abuja, Abuja Municipal, Federal Capital Territory
2614 Lagos, Lagos Island, Lagos, 71510, Nigeria
2615 Birmingham, West Midlands, England
2616 null
2617 UT
2618 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2619 Bermuda Triangle
2620 Lagos, Lagos Island, Lagos, 71510, Nigeria
2621 Singapore
2622 Singapore, Central, 178957, Singapore
2623 Kampala
2624 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2625 Ilorin St, Abuja, Abuja Municipal, Federal Capital Territory
2626 Ilorin Street, Surulere, Itire, Surulere, Lagos, 101212, Nigeria
2627 United Kingdom
2628 Lagos, Lagos Island, Lagos, 71510, Nigeria
2629 Ongwediva, Oshana
2630 My World, 105, Calle 19, Centro financiero de San Isidro, San Isidro, Lima, AN ISIDRO 15036, Perú
2631 Kampala
2632 null
2633 Manchester, Lancashire, England
2634 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
2635 Kano
2636 Nairobi, Kenya
2637 England
2638 Mumbai, Greater Bombay, Maharashtra, 400001, India
2639 Maluku
2640 اسلام آباد, ICT, 44000, ‏پاکستان‎
2641 Nairobi
2642 Auckland, 1010, New Zealand/Aotearoa
2643 Namibia
2644 San Francisco, Agusan del Sur, Caraga, Philippines
2645 Lower Road, Kingsdon, Somerton, Somerset, England, TA11 7
2646 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2647 Perth, Western Australia
2648 Anfield, Anfield Road, Walton, Liverpool, North West England, England, L4 0TH, UK
2649 Manchester, Lancashire, England
2650 Doha, الدوحة, Ad Dawhah, ‏قطر‎
2651 Moscow
2652 England, Holland, Sprockhövel, Ennepe-Ruhr-Kreis, Regierungsbezirk Arnsberg, Nordrhein-Westfalen, 45549, Deutschland
2653 Baghdad
2654 New York Yacht Club, 37, West 44th Street, Diamond District, Manhattan Community Board 5, New York County, NYC, New York, 10036, United States of America
2655 Scotland
2656 St. Albert, Alberta, T8N 5C9, Canada
2657 London, England
2658 Milky Way, Sesel
2659 United Kingdom

2660 Guwahati, Kamrup, Assam, 781015, India
2661 Chennai, Tamil Nadu
2662 null
2663 United Kingdom
2664 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
2665 Venezuela
2666 null
2667 Palembang, Sumatera Selatan
2668 Selangor, Malaysia
2669 Csa
2670 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2671 香港香港
2672 null
2673 Jakarta Selatan, Kebayoran Baru, Jakarta, DKI Jakarta
2674 null
2675 Indonesia
2676 London, Greater London, England, UK
2677 Not
2678 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2679 United Kingdom
2680 The West Coast, Old Strathcona, Edmonton, Alberta, T6E3Z4, Canada
2681 Suko Manunggal, Surabaya, Jawa Timur
2682 Africa, Villa Unión, Córdoba, Departamento Capital, Cba., 5010, Argentina
2683 Chicago, Illinois
2684 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2685 E, Nordrhein-Westfalen
2686 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
2687 Mumbai, Maharashtra
2688 Valais/Wallis, Schweiz/Suisse/Svizzera/Svizra
2689 Chattanooga, Tennessee
2690 UK
2691 Jelapang, Ipoh, Kinta, Perak
2692 Manchester United, Tavarekere Main Road, Prestige Acropolis, Adugodi, Bengaluru, Bangalore Urban, Karnataka, 560001, India
2693 Raleigh, North Carolina
2694 Monmouth County, New Jersey, United States of America
2695 United Kingdom
2696 Springfield, Sangamon County, Illinois, United States of America
2697 JHB
2698 Kedah, Malaysia
2699 Edinburgh, Midlothian, Scotland
2700 19, 環球大廈 World-Wide House, 中環 Central District, 香港, 中西區 Central and Western District, 香港島 Hong Kong Island, HK, 中国
2701 Couch Rd, Gillies, Ontario, P0T
2702 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
2703 Richmond, Virginia
2704 Manchester, Greater Manchester, North West England, England, UK
2705 Charleston, South Carolina
2706 Tampa, FL, 610, Polk Street, Ridgewood Park, Tampa Heights, Tampa, Hillsborough County, Florida, 33602, United States of America
2707 Manchester, Lancashire, England
2708 NYC, New York, United States of America
2709 Cherry Hill, New Jersey
2710 Hyderabad Chefs, Outer Ring Road, P R Layout, Kaadubeesanahalli, Bengaluru, Bangalore Urban, Karnataka, 560001, India
2711 South, Kentucky
2712 Granite City, Conference Center Drive, East Peoria, Tazewell County, Illinois, 61611, United States of America
2713 N1 7
2714 Kolkata, Hāora, West Bengal, 700021, India
2715 Tangerang, Banten
2716 Sydney, NSW, Australia
2717 Seattle, Washington
2718 Lagos, Lagos Island, Lagos, 71510, Nigeria
2719 616th Ave, Madison Lake, Minnesota, 56063
2720 Manchester, Greater Manchester, North West England, England, UK
2721 Canterbury, Kent, England
2722 Seattle, King County, Washington, United States of America
2723 Canterbury, Kent, England
2724 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2725 Manchester, Lancashire, England
2726 East Midlands, England, UK
2727 Nottingham, Nottinghamshire, England
2728 New York Yacht Club, 37, West 44th Street, Diamond District, Manhattan Community Board 5, New York County, NYC, New York, 10036, United States of America
2729 United Kingdom
2730 Jakarta, Gambir, Jakarta Pusat, Daerah Khusus Ibukota Jakarta, 10110, Indonesia
2731 Nigeria
2732 ڪراچي Karachi, Karāchi District, سنڌ, ‏پاکستان‎
2733 England
2734 Montgomery, Montgomery County, Alabama, United States of America
2735 Northampton, Northamptonshire, England
2736 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2737 Reading, Berkshire, England
2738 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
2739 Singapore
2740 Nigeria
2741 Lagos, Lagos Island, Lagos
2742 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2743 London, England
2744 null
2745 Scotland
2746 Nigeria
2747 United Kingdom
2748 Lagos, Lagos Island, Lagos, 71510, Nigeria
2749 South Carolina
2750 null
2751 Atlanta, Georgia
2752 Mountain Momma XXC, Bath County, Virginia, United States of America
2753 Canton, Michigan
2754 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2755 United Kingdom
2756 Manchester, Greater Manchester, North West England, England, UK
2757 United Kingdom
2758 Corporation of Chennai, Chennai district, Tamil Nadu, India
2759 Årdalstangen, Årdal, Sogn og Fjordane
2760 Corporation of Chennai, Chennai district, Tamil Nadu, India
2761 Abuja, Abuja Municipal, Federal Capital Territory
2762 Cuttack, Odisha, 753001, India
2763 Lebanon
2764 Tasikmalaya, Jawa Barat, 46181, Indonesia
2765 Manchester, Lancashire, England
2766 Droga Męczenników Rotundy, Rotunda, Osiedle Zamczysko, Zamość, lubelskie, 22-400, RP
2767 null
2768 null
2769 ME
2770 Birkenhead, North West England, England, CH41 6JB, UK
2771 Kano
2772 United States of America
2773 Ireland
2774 London, Greater London, England, UK
2775 Essex, Maryland
2776 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2777 Lagos, Lagos Island, Lagos
2778 St. Lucia, Umkhanyakude District Municipality, KwaZulu-Natal, 3936, South Africa
2779 Kota Belud, Division Pantai Barat Utara, Sabah
2780 Canada
2781 Europe
2782 Greater Manchester, North West England, England, UK
2783 Ma's Place
2784 United States of America
2785 Anything
2786 Manhattan, NYC, New York, 83, United States of America
2787 Nigeria
2788 Manaus, Microrregião de Manaus, Mesorregião Centro Amazonense, AM, Região Norte, 69000-000, Brasil
2789 United Kingdom
2790 null
2791 TO
2792 Glasgow City, Scotland, UK
2793 United Kingdom
2794 United States of America
2795 Lagos, Lagos Island, Lagos
2796 null
2797 Football Pitch
2798 London, Prince Faisal bin Fahed Road, العقربية, الخبر, المنطقة الشرقية, 34433, السعودية
2799 null
2800 Leicester, East Midlands, England, LE1 5YA, UK
2801 Mumbai, Maharashtra
2802 Mumbai, Greater Bombay, Maharashtra, 400001, India
2803 Malaysia
2804 Nigeria
2805 Bandung Kota, Sumur Bandung, Bandung, Jawa Barat
2806 Liverpool, North West England, England, UK
2807 La
2808 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2809 England
2810 MCR, Worcester Place, Jericho, Oxford, Oxon, South East, England, OX1 1HP, UK
2811 Wilmington, North Carolina
2812 null
2813 East Grinstead, West Sussex, England
2814 London, Greater London, England, UK
2815 Bengaluru, Karnataka
2816 Madurai, Madurai district, Tamil Nadu, India
2817 London, England
2818 Lagos, Lagos Island, Lagos, 71510, Nigeria
2819 Ghana
2820 Irlanda, Los Domínicos, Las Condes, Provincia de Santiago, Región Metropolitana de Santiago, 7550000, Chile
2821 Fucking, Tarsdorf, Braunau am Inn, Oberösterreich
2822 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
2823 United Kingdom
2824 Winterfell, Barranmühle, Schipkau, Landkreis Oberspreewald-Lausitz, Brandenburg, 01994, Deutschland
2825 California
2826 Manchester, Greater Manchester, North West England, England, UK
2827 England
2828 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2829 United Kingdom
2830 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2831 United Kingdom
2832 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2833 United Kingdom
2834 England, UK
2835 England
2836 Chelsea, Royal Borough of Kensington and Chelsea, London, Greater London, England, SW3 5EE, UK
2837 United Kingdom
2838 null
2839 Sukodono, East Java
2840 阪神高速14号松原線, 阿倍野区, 大阪市港区, 大阪府, 5500014, 日本
2841 Ireland
2842 null
2843 United Kingdom
2844 Henley-on-Thames, South Oxfordshire, Oxon, South East, England, UK
2845 Lagos, Lagos Island, Lagos
2846 St Helens, North West England, England, UK
2847 United Kingdom
2848 null
2849 Lagos, Lagos Island, Lagos
2850 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2851 United Kingdom
2852 England, UK
2853 England
2854 Fort Worth, Tarrant County, Texas, United States of America
2855 Lagos, Lagos Island, Lagos
2856 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2857 Martial, Centre
2858 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2859 Stamford Bridge, York, North Yorkshire, England
2860 null
2861 Benin City, Oredo, Edo
2862 Chester, Cheshire West and Chester, North West England, England, CH1 2ET, UK
2863 Leeds, West Yorkshire, England
2864 London, Greater London, England, UK

2865 Manchester, Lancashire, England
2866 London, Greater London, England, UK
2867 Lagos, Lagos Island, Lagos
2868 Paradise, Clark County, Nevada, United States of America
2869 London, England
2870 null
2871 Ghana
2872 Gainsborough, Lincolnshire, East Midlands, England, DN21 2AJ, UK
2873 Nigeria
2874 Eastbourne, East Sussex, South East, England, UK
2875 Nilópolis, Rio de Janeiro
2876 Manchester, Greater Manchester, North West England, England, UK
2877 Kano
2878 London, Greater London, England, UK
2879 Toronto, Ontario
2880 United States of America
2881 Lagos, Lagos Island, Lagos
2882 null
2883 Ikeja, Lagos
2884 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
2885 India
2886 West Yorkshire, M62, East Bierley, Kirklees, Yorkshire and the Humber, England, BD19 4AZ, UK
2887 Dubai
2888 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
2889 West
2890 Kent, South East, England, UK
2891 null
2892 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
2893 Manchester, Lancashire, England
2894 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
2895 UK
2896 Unknown, The Bahamas
2897 Gloucestershire, England
2898 null
2899 Sky
2900 Denver, Denver County, Colorado, United States of America
2901 Coventry Ln, Manchester, California, 95459
2902 Yateley, Hart, Hampshire, South East, England, UK
2903 Location, West Virginia
2904 null
2905 Hawkshead Drive, Middleton, Manchester, Lancashire, England, M24 4
2906 Magodo, Tana River, Kenya
2907 United Kingdom
2908 Stockport, Greater Manchester, North West England, England, UK
2909 Moe's Tavern
2910 København, Københavns Kommune, Region Hovedstaden, 1357, Danmark
2911 Ethiopia
2912 CFC, Commercial Way, Bells Gardens Estate, Peckham, London Borough of Southwark, London, Greater London, England, SE15, UK
2913 Newcastle, New South Wales
2914 null
2915 Nigeria
2916 England, UK
2917 Lokoja, Kogi
2918 Lagos, Lagos Island, Lagos, 71510, Nigeria
2919 Tanzania
2920 Ogun, Nigeria
2921 There There
2922 England, UK
2923 NE Ave, Madison, Florida, 32340
2924 Manchester, Greater Manchester, North West England, England, UK
2925 Heaven
2926 null
2927 Brno, Brno-město, Jihomoravský kraj
2928 Manchester, Greater Manchester, North West England, England, UK
2929 Le Drivet, Pomeys, Rhône, Auvergne-Rhône-Alpes
2930 null
2931 Langley, Slough, Berkshire, England
2932 Tema, Greater Accra Region, TM3 8AA, Ghana
2933 South Africa
2934 null
2935 Kuching, Division Kuching, Sarawak
2936 London, Greater London, England, UK
2937 Perak, Temerloh, Pahang
2938 Exeter Close, Thorpe Bay, Shoeburyness, Southend-on-Sea, East of England, England, SS3 9SQ, UK
2939 Lagos, Lagos Island, Lagos
2940 London, Greater London, England, UK
2941 Jakarta Barat, Kembangan, Jakarta, DKI Jakarta
2942 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2943 Ghana
2944 Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur, France métropolitaine, 13000, France
2945 United Kingdom
2946 Somewhere, 93, Rue du Commerce, Grenelle, 15e, Paris, Île-de-France, France métropolitaine, 75015, France
2947 06593
2948 Kenya
2949 Unknown
2950 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
2951 Lagos, Lagos Island, Lagos
2952 Friendzone, Carrera 6, San Cristóbal, Bogotá, Bogotá Distrito Capital, 111711, Colombia
2953 Berlin
2954 East London, Buffalo City Metropolitan Municipality, Eastern Cape, 5201, South Africa
2955 London, England
2956 Nigeria
2957 Hackney, Missouri
2958 null
2959 null
2960 Le Lair, Avranches, Manche, Normandie, France métropolitaine, 50730, France
2961 Cheshire, Connecticut
2962 null
2963 Manchester, Lancashire, England
2964 Sin City, 2, Posener Straße, Lierenfeld, Stadtbezirk 8, Düsseldorf, Regierungsbezirk Düsseldorf, Nordrhein-Westfalen, 40231, Deutschland
2965 Nigeria
2966 Chorley, Lancs, North West England, England, UK
2967 London, England
2968 null
2969 Glasgow, Lanarkshire, Scotland
2970 Bortianor, Ga South, Greater Accra Region, AA10 4AA, Ghana
2971 Ghana
2972 Leeds, Yorkshire and the Humber, England, UK
2973 Lagos, Lagos Island, Lagos
2974 Greystones, County Wicklow, Leinster, A63 YE86, Ireland
2975 Wilmslow, Cheshire, England
2976 null
2977 Manchester, Lancashire, England
2978 Salford, Greater Manchester, North West England, England, UK
2979 Stretford Road, Old Trafford, Manchester, Lancashire, England, M16 0
2980 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2981 Ghana
2982 Nigeria
2983 Lagos, Lagos Island, Lagos
2984 Singapore, Central, 178957, Singapore
2985 Lagos, Lagos Island, Lagos
2986 Manchester, Greater Manchester, North West England, England, UK
2987 Lagos, Lagos Island, Lagos
2988 Lagos, Lagos Island, Lagos, 71510, Nigeria
2989 Ghana
2990 null
2991 Nigeria
2992 Rochester, South East, England, UK
2993 Nairobi
2994 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
2995 Abuja, Abuja Municipal, Federal Capital Territory
2996 Gandhinagar, Gujarat, 382011, India
2997 Katsina
2998 null
2999 Lagos, Lagos Island, Lagos
3000 Kuwait, La Convención, Cusco, Perú
3001 United Kingdom
3002 Philip Billard Municipal Airport, Northeast Lamr Avenue, Topeka, Shawnee County, Kansas, 66616, United States of America
3003 North London, Greater London, England
3004 Manchester, Greater Manchester, North West England, England, UK
3005 Football Pitch
3006 Manchester, Greater Manchester, North West England, England, UK
3007 Cape Town, Western Cape
3008 null
3009 République Togolaise
3010 null
3011 Painted Desert
3012 Manchester, Greater Manchester, North West England, England, UK
3013 Newcastle, New South Wales
3014 null
3015 Bangalore, Bengaluru, Karnataka
3016 null
3017 Berlin
3018 Sheffield, Yorkshire and the Humber, England, UK
3019 London Road, Nottingham, Nottinghamshire, England, NG1 1
3020 NYC, New York, United States of America
3021 null
3022 New Delhi, Delhi, India
3023 London, England
3024 London, 14, проспект Вернадского, Проспект Вернадского, район Проспект Вернадского, Западный административный округ, Москва, ЦФО, 119415, РФ
3025 England
3026 Toronto, Ontario, Canada
3027 Unknown
3028 Scotland, UK
3029 Vestmannaeyjar, Vestmannaeyjabær, Suðurland
3030 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
3031 UR
3032 Ambassade du Nigéria, Boulevard de la République, Indénié, Le Plateau, Abidjan, 01 BP 10605 ABIDJAN 01, Côte d’Ivoire
3033 Worldwide
3034 Scotland, UK
3035 Mogadisho, Banaadir
3036 null
3037 Accra, Accra Metropolis, Greater Accra
3038 Lagos, Lagos Island, Lagos, 71510, Nigeria
3039 03205
3040 Nigeria
3041 Lagos, Lagos Island, Lagos
3042 Texas, United States of America
3043 Northern Ireland
3044 Gili Villas, Jalan Bintang Laut, Lombok Utara, Kec. Ampenan, Nusa Tenggara Barat, 83352, Indonesia
3045 Harare
3046 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3047 London, England
3048 Dublin, County Dublin, Leinster, Ireland
3049 Lonely Mountain
3050 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
3051 Glossop, Derbyshire, England
3052 Takoradi, Western Region, Ghana
3053 Manchester, Lancashire, England
3054 Lagos, Lagos Island, Lagos, 71510, Nigeria
3055 Semarang Selatan, Semarang, Jawa Tengah
3056 Nairobi, Kenya
3057 Cincinnati, Ohio
3058 Jamaica
3059 Kaboja, Kampala, Busiro, Wakiso
3060 East Legon, Accra, Accra Metropolitan, Greater Accra Region, BOX LG25, Ghana
3061 Nigeria Clos, Nairobi
3062 Patna, Bihar, 800001, India
3063 Houston, Texas
3064 Sumatera Barat, Indonesia
3065 United Kingdom
3066 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3067 UK
3068 null
3069 S Memory Ln, Peru, Indiana, 46970
3070 England, UK
3071 The Poolside
3072 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3073 Madagascar
3074 Bortianor, Ga South, Greater Accra Region, AA10 4AA, Ghana
3075 Nairobi
3076 Belfast, County Antrim, Northern Ireland, BT1 5GS, UK
3077 Limavady, County Londonderry, Northern Ireland
3078 Kabul, بهسود, ننگرهار, 1002, افغانستان
3079 Ghana
3080 Orem, Utah County, Utah, United States of America
3081 Lagos, Lagos Island, Lagos
3082 Nairobi, Kenya
3083 UK
3084 Manchester, Greater Manchester, North West England, England, UK
3085 Roam, Manoharpur, Pashchimi Singhbhum, Jharkhand
3086 Manchester, Greater Manchester, North West England, England, UK

3087 Netherlands
3088 null
3089 Kuwait
3090 Richmond, London, Greater London, England, TW9 1DY, UK
3091 England
3092 Kenya
3093 null
3094 Manchester Pond Dam, Attleboro, Bristol County, Massachusetts, 02703, United States of America
3095 Barreiro, Setúbal
3096 St Austell, Cornwall, South West England, England, PL25 4TS, UK
3097 Manchester, Lancashire, England
3098 null
3099 Manchester, Lancashire, England
3100 null
3101 Nairobi
3102 LV, Colonia Hacienda del Parque, Cuautitlán Izcalli, Estado de México, 54769, México
3103 India
3104 Albania, La Guajira, Colombia
3105 Data Stream
3106 null
3107 Lagos, Lagos Island, Lagos
3108 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
3109 Liverpool, Merseyside, England
3110 null
3111 Amalfi Coast
3112 Falmouth, Cornwall, South West England, England, TR11 3AT, UK
3113 Mumbai, Maharashtra
3114 Lagos, Lagos Island, Lagos, 71510, Nigeria
3115 Burton, Lincoln, Lincolnshire, England
3116 World War Memorial, Shahid Minar Rd, Jagannath Hall, DU, jigatola, ঢাকা, ঢাকা বিভাগ, 1000, বাংলাদেশ
3117 Lagos, Lagos Island, Lagos
3118 Brighton, Brighton and Hove, South East, England, UK
3119 DKR
3120 Bedford, East of England, England, MK40 1SU, UK
3121 null
3122 Kakamega, Kenya
3123 Cfa
3124 จังหวัดนครราชสีมา, ประเทศไทย
3125 Manchester, Lancashire, England
3126 Sydney, NSW, Australia
3127 Carrow Road
3128 England, UK
3129 Edinburgh, Midlothian, Scotland
3130 null
3131 Mombasa
3132 Paris, Île-de-France, France métropolitaine, France
3133 Newcastle upon Tyne, Tyne and Wear, England
3134 Москва, Центральный административный округ, Москва, ЦФО, РФ
3135 01417
3136 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3137 Reading, Berkshire, England
3138 Lagos, Lagos Island, Lagos, 71510, Nigeria
3139 Superbie, Saint-Sève, Gironde, Nouvelle-Aquitaine
3140 Zagreb, Grad Zagreb, Hrvatska
3141 Birmingham, West Midlands, England
3142 Kashmir, Taylorsville, Salt Lake County, Utah, 84123, United States of America
3143 Ghana
3144 null
3145 Era Banten
3146 首都高速3号渋谷線, 南青山6, 港区, 東京都, 106-0032, 日本
3147 New Villas, London, England, N17 0
3148 Malaysia
3149 Metropolis
3150 null
3151 USA
3152 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3153 United Kingdom
3154 Nairobi, Kenya
3155 Stamford Bridge, York, North Yorkshire, England
3156 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
3157 İn, Hozat, Tunceli
3158 Liverpool, North West England, England, UK
3159 United Arab Emirates
3160 null
3161 Manchester, Lancashire, England
3162 Bengaluru, Bangalore Urban, Karnataka, 560001, India
3163 Kampala
3164 UK
3165 Scotland
3166 Lusaka, Lusaka Province, Zambia
3167 Rosyth, Dunfermline, Fife, Scotland
3168 254, Stadtbezirk 10 Moosach, München, OB, Bayern, 80992, Deutschland
3169 next
3170 Cork, County Cork, Munster, T12 PR83, Ireland
3171 Nairobi
3172 Widnes, Halton, North West England, England, WA8 6BT, UK
3173 Lagos, Lagos Island, Lagos
3174 null
3175 Akure, Akure South, Ondo
3176 Lagos, Lagos Island, Lagos, 71510, Nigeria
3177 Norfolk, Virginia
3178 null
3179 Bradford, West Yorkshire, England
3180 Hastings, East Sussex, South East, England, UK
3181 Pretoria, Tshwane, Gauteng
3182 null
3183 Dublin city, Dublin, Leinster
3184 North West England, England, UK
3185 Flying High
3186 null
3187 0786
3188 Here, Općina Prozor, Hercegovačko-neretvanska županija/kanton, Federacija Bosne i Hercegovine, Bosna i Hercegovina / Босна и Херцеговина
3189 Lagos, Lagos Island, Lagos
3190 Nigeria
3191 Sebokeng, Sedibeng, Gauteng
3192 London, Greater London, England, UK
3193 Dublin city, Dublin, Leinster
3194 Kumasi, Ashanti Region, Ghana
3195 Brussels
3196 Lehigh Valley, Pennsylvania Turnpike Northeast Extension, Crackersport, Lehigh County, Pennsylvania, 18069, United States of America
3197 Milano
3198 Global, 81, Barber Greene Road, Don Mills, North York, Toronto, Ontario, M3C 2C4, Canada
3199 Kampala
3200 Twitter, 1355, Market Street, Civic Center, SF, California, 94114, United States of America
3201 Mumbai, Maharashtra
3202 England, UK
3203 Mogadishu, Banaadir
3204 Vanderbijlpark, Sedibeng District Municipality, Gauteng, 1911, South Africa
3205 Barnsley, South Yorkshire, England
3206 null
3207 Leeds Street, Liverpool, Merseyside, England, L3 2
3208 null
3209 Nigeria
3210 Nigeria
3211 La Hantes
3212 Liverpool, North West England, England, UK
3213 Nigeria
3214 Indonesia
3215 London Road, Bromley, Kent, England, BR1 1
3216 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
3217 Nairobi
3218 England, UK
3219 Abuja, Abuja Municipal, Federal Capital Territory
3220 Nakuru, Kenya
3221 Burton, Lincoln, Lincolnshire, England
3222 Hartlepool, North East England, England, TS24, UK
3223 Abuja, Abuja Municipal, Federal Capital Territory
3224 Kumasi, Ashanti Region, Ghana
3225 Houston, Texas
3226 Nigeria
3227 null
3228 Nigeria
3229 United Kingdom
3230 Hertfordshire, East of England, England, UK
3231 France
3232 Mauritius
3233 Warsaw, Woj. Mazowieckie
3234 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3235 Zamanda, Nola, Sangha-Mbaéré
3236 England, UK
3237 Orem, Utah
3238 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3239 Cape Town, Western Cape
3240 Carrickfergus, County Antrim, Northern Ireland, BT38 8JJ, UK
3241 Aqaba, Al Aqaba Governorate
3242 Ireland
3243 Gangtok, East District, Sikkim
3244 Gahri Lakes, Gwaskara, Hawul, Borno, Nigeria
3245 South Staffordshire, England
3246 Lagos, Lagos Island, Lagos, 71510, Nigeria
3247 Lagos, Lagos Island, Lagos
3248 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
3249 West
3250 Manchester, Greater Manchester, North West England, England, UK
3251 United Kingdom
3252 مصر
3253 Anfield, Gordon, New Brunswick
3254 Global, 81, Barber Greene Road, Don Mills, North York, Toronto, Ontario, M3C 2C4, Canada
3255 Where
3256 Wigan, Greater Manchester, North West England, England, UK
3257 Bengaluru, Karnataka
3258 null
3259 Worldwide
3260 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
3261 Limuru, Kiambu
3262 London, Greater London, England, UK
3263 Olympus
3264 Lurgan Avenue, Brook Green, London Borough of Hammersmith and Fulham, London, Greater London, England, W6 8LH, UK
3265 null
3266 Pokhara, Pokhara Lekhnath Metropolitan, कास्की, गण्डकी अञ्चल, पश्चिमाञ्चल विकास क्षेत्र, 3, नेपाल
3267 Pace
3268 Prior Lake, Scott County, Minnesota, 55372, United States of America
3269 Manchester United
3270 null
3271 Lagos, Lagos Island, Lagos
3272 Jambi, Indonesia
3273 Nice, Alpes-Maritimes, Provence-Alpes-Côte d'Azur
3274 null
3275 Lagos, Lagos Island, Lagos
3276 Welwyn Garden City, Hertfordshire, East of England, England, AL8 6TP, UK
3277 Ghāziābād, Uttar Pradesh
3278 Lagos, Lagos Island, Lagos, 71510, Nigeria
3279 Forest Way, Manchester Township, New Jersey, 08759
3280 dammam, المجمعة, منطقة الرياض, السعودية
3281 United Kingdom
3282 Gbg, Göteborg, Västra Götalands län, Götaland, 41106, Sverige
3283 Solihull, West Midlands, England
3284 My house, Giurgiu, 87043, România
3285 England
3286 The Foxes, James City County, Virginia, 23186, United States of America
3287 Muddle Go Nowhere
3288 Ikoyi, Ori Ire, Oyo, Nigeria
3289 Indonesia
3290 België - Belgique - Belgien
3291 Suspenders
3292 null
3293 Manchester Ln, Birmingham, Alabama, 35243
3294 Manchester, Greater Manchester, North West England, England, UK
3295 Lekki, Ondo
3296 Dallas, Dallas County, Texas, United States of America
3297 Accra, Accra Metropolis, Greater Accra
3298 Cusano Milanino, MI, LOM, 20095, Italia
3299 England
3300 North Carolina, United States of America
3301 Nigeria
3302 null
3303 United Kingdom
3304 Giannino, 26, Rue du Marché aux Fromages - Kaasmarkt, Quartier du Centre - Centrumwijk, BXL, Ville de Bruxelles - Stad Brussel, Brussel-Hoofdstad - Bruxelles-Capitale, Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest, 1000, België - Belgique - Belgien
3305 Abuja, Abuja Municipal, Federal Capital Territory
3306 England, UK
3307 Ireland
3308 Eufaula, McIntosh County, Oklahoma, 74432, United States of America
3309 Atlanta, Georgia
3310 Lekki, Ilaje, Ondo, Nigeria

3311 Kuala Terengganu, Terengganu
3312 null
3313 Don Mueang, Bangkok
3314 City of London, Greater London, England, UK
3315 Liverpool, Merseyside, England
3316 Kumasi, Ashanti Region, Ghana
3317 England
3318 Lagos, Lagos Island, Lagos, 71510, Nigeria
3319 Serang, Banten
3320 Deutschland, Europe
3321 Heaven
3322 The Hills, NSW, Australia
3323 Nigeria
3324 null
3325 Shah Alam, Seksyen 7, Shah Alam, Petaling, Selangor
3326 null
3327 Exeter, Devon, England
3328 Lagos, Lagos Island, Lagos, 71510, Nigeria
3329 I.T. World
3330 United States of America
3331 Orem, Utah
3332 Navi Mumbai, Greater Bombay, Maharashtra, 400614, India
3333 Abuja, Abuja Municipal, Federal Capital Territory
3334 null
3335 Lag, Bình Thuận
3336 Lagos, Lagos Island, Lagos, 71510, Nigeria
3337 Kolkata, Calcutta, West Bengal
3338 झापा जिल्ला, मेची अञ्चल, पुर्वाञ्चल विकास क्षेत्र, नेपाल
3339 Indonesia
3340 Centre of the Universe, Lyonville, Shire of Hepburn, Grampians, Victoria, Australia
3341 Indonesia
3342 Manchester, Greater Manchester, North West England, England, UK
3343 Lagos, Lagos Island, Lagos
3344 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3345 Johor Bahru, Johor
3346 Lagos, Lagos Island, Lagos, 71510, Nigeria
3347 Malaysia
3348 null
3349 Jakarta, DKI Jakarta
3350 null
3351 Data Stream
3352 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3353 Manchester, Lancashire, England
3354 Bristol, City of Bristol, South West England, England, UK
3355 Bristol, Avon, England
3356 ঢাকা, ঢাকা বিভাগ, 12, বাংলাদেশ
3357 Glasgow, Lanarkshire, Scotland
3358 null
3359 Portsmouth, Hampshire, England
3360 Manchester United, Tavarekere Main Road, Prestige Acropolis, Adugodi, Bengaluru, Bangalore Urban, Karnataka, 560001, India
3361 Global, Ehlanzeni, Mpumalanga
3362 Sandy Shores, Danville City, Virginia, 24541, United States of America
3363 Edelweiss, Shawnee, Kansas
3364 القاهرة, محافظة القاهرة, مصر
3365 Cape Town, Western Cape
3366 London, Greater London, England, UK
3367 India
3368 null
3369 null
3370 Time Square, Downtown Edmonton, Edmonton, Alberta, Canada
3371 Héré, Département de la Creuse, Limousin
3372 Akure, Akure South, Ondo, Nigeria
3373 null
3374 Mumbai, Greater Bombay, Maharashtra, 400001, India
3375 St John's, Newfoundland and Labrador
3376 Le Canada, Sahurs, Rouen, Seine-Maritime, Normandie, France métropolitaine, 76113, France
3377 Abuja
3378 null
3379 Bangkok, Phra Nakhon, Bangkok
3380 Ilorin, Ilorin East, Kwara, 240212, Nigeria
3381 null
3382 بغداد, الكرخ, محافظة بغداد, العراق
3383 Malaysia
3384 Ampang, Selangor, 6, Malaysia
3385 Lekki Peninsula, Lagos
3386 Bauchi, Nigeria
3387 Accra, Accra Metropolis, Greater Accra
3388 null
3389 Accra, Accra Metropolis, Greater Accra
3390 नेपाल
3391 Thugs Mantion Pub
3392 Melwood, Edgar County, Illinois, 61932, United States of America
3393 Medellín, Antioquia
3394 Bengaluru, Bangalore Urban, Karnataka, 560001, India
3395 null
3396 नेपाल
3397 India
3398 Old Delhi Gurgaon Road, Dundahera, Sector 21, Rangpuri, New Delhi, Gurugram, Delhi, 122016, India
3399 Los Angeles, California
3400 Mumbai-Pune Expressway, Kalamboli, Panvel, Greater Bombay, Maharashtra, 410206, India
3401 Aurangabad, Maharashtra
3402 null
3403 Lagos, Lagos Island, Lagos
3404 Shepherds Bush, Wantirna South, City of Knox, Greater Melbourne, Victoria, 3150, Australia
3405 Worldwide
3406 Orem, Utah County, Utah, United States of America
3407 Owerri, Owerri Municipal, Imo
3408 Mumbai, Greater Bombay, Maharashtra, 400001, India
3409 Glasgow, Lanarkshire, Scotland
3410 Nairobi, Kenya
3411 Kolkata, Calcutta, West Bengal
3412 null
3413 Malaysia
3414 null
3415 Bristol, Avon, England
3416 null
3417 United Kingdom
3418 Manchester, Greater Manchester, North West England, England, UK
3419 Leeds, West Yorkshire, England
3420 Boston, Suffolk, Massachusetts, United States of America
3421 137
3422 London, Greater London, England, UK
3423 Kenya
3424 BA, Região Nordeste, Brasil
3425 Accra, Accra Metropolis, Greater Accra
3426 Inside, 23, Sankt-Pöltener-Straße, Feuerbach-Mitte, Feuerbach, Stuttgart, Regierungsbezirk Stuttgart, Baden-Württemberg, 70469, Deutschland
3427 Karachi, Karāchi District, Sindh
3428 Glasgow City, Scotland, UK
3429 Johannesburg, Gauteng
3430 Navi Mumbai, Greater Bombay, Maharashtra, 400614, India
3431 South Africa
3432 null
3433 Glasgow, Lanarkshire, Scotland
3434 London, Greater London, England, UK
3435 United Kingdom
3436 Bristol, City of Bristol, South West England, England, UK
3437 Jakarta, DKI Jakarta
3438 India
3439 Phoenix, Arizona
3440 Jerantut, Pahang, Malaysia
3441 Vancouver, British Columbia
3442 England, UK
3443 Soweto, Orlando West, Johannesburg, Gauteng
3444 Liverpool, North West England, England, UK
3445 London Ln, Croydon, Utah, 84018
3446 Ormskirk Road, Chapel House, West Lancashire, Lancs, North West England, England, WN8 8TR, UK
3447 Skylab
3448 千代田区, 東京都, 日本
3449 Stay Cool
3450 Lagos, Lagos Island, Lagos, 71510, Nigeria
3451 Glasgow, Lanarkshire, Scotland
3452 null
3453 Old Trafford, Manchester, Lancashire, England
3454 South Wales, Erie County, New York, 14139, United States of America
3455 Manly Close, Nottingham, Nottinghamshire, England, NG5 9
3456 National Environment Agency (Central Region), 4545, Jalan Bukit Merah, Bukit Merah, Singapore, Central, 159466, Singapore
3457 Nevers, Nièvre, Bourgogne-Franche-Comté
3458 Global, 81, Barber Greene Road, Don Mills, North York, Toronto, Ontario, M3C 2C4, Canada
3459 Yogyakarta, Daerah Istimewa Yogyakarta
3460 Manchester, Greater Manchester, North West England, England, UK
3461 Setapak, Kuala Lumpur, Wilayah Persekutuan
3462 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3463 London, England
3464 Hillingdon, London, Greater London, England, UK
3465 Nottingham, Nottinghamshire, England
3466 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3467 Galaxy, Columbia, South Carolina
3468 Liverpool, North West England, England, UK
3469 Ibadan, Oyo
3470 London, Greater London, England, UK
3471 England
3472 London Borough of Hammersmith and Fulham, London, Greater London, England, SW6, UK
3473 London Road, Southampton, Hampshire, England, SO15 2
3474 Ireland
3475 Winterfell
3476 null
3477 Muscat
3478 Jamaica
3479 Tardeo, Mumbai Central, Mumbai, Maharashtra
3480 Dundee, Saline Township, Washtenaw County, Michigan, 48176, United States of America
3481 Lagos, Lagos Island, Lagos
3482 Appleby, Brigg Road, British Steel Ltd, New Frodingham, Scunthorpe, North Lincolnshire, Yorkshire and the Humber, England, DN16 1AP, UK
3483 London, England
3484 null
3485 Island, Ohio
3486 Manchester, Greater Manchester, North West England, England, UK
3487 England
3488 Centro, Tabasco, México
3489 Orem, Utah
3490 Oslo, 26, Norge
3491 Cavan
3492 Corporation of Chennai, Chennai district, Tamil Nadu, India
3493 Accra, Accra Metropolis, Greater Accra
3494 null
3495 London, England
3496 null
3497 United Kingdom
3498 ประเทศไทย
3499 Chelsea, London, England
3500 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3501 United Kingdom
3502 Lagos, Lagos Island, Lagos, 71510, Nigeria
3503 Nigeria
3504 Bogota, Bergen County, New Jersey, 07603, United States of America
3505 Ici
3506 null
3507 Wales
3508 Wakanda Park, Menomonie, Dunn County, Wisconsin, 54751, United States of America
3509 Gaza Province, Gaza
3510 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
3511 Gki Sulsel
3512 جدة, Al Matar st. شارع المطار, جدة التاريخية, جدّة, منطقة مكة المكرمة, 22234, السعودية
3513 null
3514 Narok, Kenya
3515 null
3516 null
3517 Lagos, Lagos Island, Lagos
3518 日本
3519 Surabaya, Jawa Timur
3520 Houston, Harris County, Texas, 77002, United States of America
3521 Atlanta, Georgia
3522 Nigeria
3523 Essex, Maryland
3524 Mombasa, Kenya
3525 Cole, Texas
3526 England, UK
3527 Mombasa
3528 Orem, Utah County, Utah, United States of America
3529 Abuja, Abuja Municipal, Federal Capital Territory
3530 BKI, Obere Langgasse, Speyer, Rheinland-Pfalz, 67346, Deutschland
3531 C17
3532 Ashaiman, Greater Accra Region, TM3 8AA, Ghana
3533 02152
3534 Brong-Ahafo Region, Ghana
3535 England, Naledi, Dr Ruth Segomotsi Mompati, North West
3536 Brasil
3537 Tanzania
3538 Gdańsk, pomorskie, RP

3539 null
3540 PRK, Malaysia
3541 Singapore
3542 Singapore, Central, 178957, Singapore
3543 World
3544 Brunei Darussalam
3545 Carlisle, Cumbria, England
3546 Manchester, Greater Manchester, North West England, England, UK
3547 Makassar, Sulawesi Selatan
3548 Kashmir, Taylorsville, Salt Lake County, Utah, 84123, United States of America
3549 Kannur, Kerala
3550 Lagos, Lagos Island, Lagos, 71510, Nigeria
3551 Uganda
3552 null
3553 Mumbai, Maharashtra
3554 Norwich, Norfolk, East of England, England, UK
3555 Mayobridge, Newry, County Down, Northern Ireland
3556 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
3557 България
3558 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
3559 徳島県板野郡板野町大坂関東
3560 Oswaldtwistle, Lancs, North West England, England, BB5 3JP, UK
3561 Jamaica
3562 Cardiff, Wales, CF, UK
3563 Planet Earth Water
3564 Lagos, Lagos Island, Lagos, 71510, Nigeria
3565 Malaysia
3566 PENALTY BOX, O'Hare Commercial Arrivals, O'Hare, Chicago, Cook County, Illinois, 60018, United States of America
3567 KE
3568 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
3569 Dodowa Road, Accra, Accra Metropolis, Greater Accra
3570 Mombasa, Kenya
3571 Koraput, Odisha
3572 ولاية البحر الأحمر, السودان
3573 Accra, Accra Metropolis, Greater Accra
3574 Oyala, Wele-Nzas, Región Continental, Guinea Ecuatorial
3575 T & t
3576 Manchester, Greater Manchester, North West England, England, UK
3577 null
3578 null
3579 Egypt
3580 North Charleston, Charleston County, South Carolina, United States of America
3581 United Kingdom
3582 الإمارات العربيّة المتّحدة
3583 Planet, Arizona
3584 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
3585 Tebing Tinggi, Serdang Bedagai, Sumatera Utara
3586 Lagos, Lagos Island, Lagos, 71510, Nigeria
3587 Egypt
3588 Tema, Greater Accra Region, TM3 8AA, Ghana
3589 Manchester, Lancashire, England
3590 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
3591 The Moon, Alabama
3592 null
3593 Somewhere
3594 Manchester, Greater Manchester, North West England, England, UK
3595 Stamford Bridge, York, North Yorkshire, England
3596 Setia Alam, Klang, Selangor, 41050, Malaysia
3597 Elizabeth St, Markham, Ontario, L3P
3598 null
3599 Jepara, Jawa Tengah
3600 Shah Alam, Selangor, 40000, Malaysia
3601 Old Trafford, Manchester, Lancashire, England
3602 Washington, District of Columbia, United States of America
3603 Bangkok, Phra Nakhon, Bangkok
3604 University of Lagos, Akinpelu Adesola Road, Bariga, Shomolu, Lagos, YABA, Nigeria
3605 Botswana
3606 null
3607 New Delhi, Connaught Place, New Delhi, Delhi
3608 Kampala, Central Region, 7063, Uganda
3609 Nairobi
3610 หัวหิน, จังหวัดประจวบคีรีขันธ์, 77110, ประเทศไทย
3611 Chester, Cheshire, England
3612 London, Greater London, England, UK
3613 Lebanon
3614 East London, Buffalo City Metropolitan Municipality, Eastern Cape, 5201, South Africa
3615 Westside, Georgia
3616 London, Greater London, England, UK
3617 Portsmouth, Hampshire, England
3618 Eldoret, Uasin Gishu, 30100, Kenya
3619 Abuja, Abuja Municipal, Federal Capital Territory
3620 Nigeria
3621 London, England
3622 null
3623 อำเภอท่ามะกา จังหวัดกาญจนบุรี
3624 Lagos, Lagos Island, Lagos, 71510, Nigeria
3625 Germany
3626 Orchid Residence Suratthani, 666/5, ถนนหน้าเมือง, สุราษฎร์ธานี, จังหวัดสุราษฎร์ธานี, 84000, ประเทศไทย
3627 Nigeria
3628 Kuala Lumpur, Jalan Pekeliling KLIA, Kampung Baru Lanjut, Salak, Sepang, Selangor, 71760, Malaysia
3629 Lusaka
3630 null
3631 Old Trafford, Manchester, Lancashire, England
3632 ประเทศไทย
3633 England
3634 กรุงเทพมหานคร, ประเทศไทย
3635 Kolkata, Calcutta, West Bengal
3636 null
3637 Mumbai, Maharashtra
3638 Manchester, Greater Manchester, North West England, England, UK
3639 Jalan Gajah 1, FELDA Simpang Wa Ha, Sedili Kechil, Kota Tinggi, 81907, Johor
3640 Malaysia
3641 End St, Stretford, Sedibeng, Gauteng, 1984
3642 null
3643 Nigeria
3644 Global, 81, Barber Greene Road, Don Mills, North York, Toronto, Ontario, M3C 2C4, Canada
3645 Temerloh, Pahang
3646 Delhi Darbar Dsm City Center, Mtendeni Street, City Centre, Kisutu, Dar es Salaam, Coastal, 3918, Tanzania
3647 Polokwane, Capricorn, Limpopo
3648 Popeyes, Annapolis Road, Severn, Anne Arundel County, Maryland, 20794, United States of America
3649 日本
3650 Bayamón, Puerto Rico, United States of America
3651 Wēb, Oromiya Region
3652 Tottenham, London Borough of Haringey, London, Greater London, England, N17 9TR, UK
3653 Esposende, Braga
3654 Ampang, Selangor, 6, Malaysia
3655 UAE
3656 null
3657 Salford, Lancashire, England
3658 Ploče, Dubrovačko-neretvanska županija, 20340, Hrvatska
3659 Dulu, Godda, Jharkhand
3660 Sabah, Malaysia
3661 MK
3662 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3663 Türkiye
3664 Estados Unidos, Becerril, Cesar, Colombia
3665 Arusha
3666 กรุงเทพมหานคร, ประเทศไทย
3667 Casablanca
3668 Umujyi wa Kigali, Rwanda
3669 Karimun, Kepulauan Riau
3670 Follows Camp, Los Angeles County, California, United States of America
3671 null
3672 Midrand, City of Johannesburg Metropolitan Municipality, Gauteng, 1682, South Africa
3673 Zambia, eThekwini, Kwazulu Natal
3674 Manchester, Greater Manchester, North West England, England, UK
3675 Jogja
3676 Manchester, Greater Manchester, North West England, England, UK
3677 The Other Room
3678 null
3679 Los Angeles, California
3680 Libreville, Estuaire, 2646, Gabon
3681 London, England
3682 India
3683 Thailand
3684 Philippines
3685 Kota Kinabalu, Division Pantai Barat Utara, Sabah
3686 North, Topping Lane, Yiewsley, Hillingdon, London, Greater London, England, UB8 2TL, UK
3687 New Delhi World
3688 Manchester, Greater Manchester, North West England, England, UK
3689 Chennai, Tamil Nadu
3690 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3691 Nigeria
3692 null
3693 Manchester, Lancashire, England
3694 Mombasa, Kenya
3695 India
3696 Montevideo, Uruguay
3697 Free State
3698 Dallas, Dallas County, Texas, United States of America
3699 Amakom Aps
3700 Seremban, NSN, 70000, Malaysia
3701 Lagos, Lagos Island, Lagos
3702 Bavaria, Matthias-Pschorr-Straße, Bezirksteil St. Paul, Stadtbezirk 02 Ludwigsvorstadt-Isarvorstadt, München, OB, Bayern, 80336, Deutschland
3703 Gombe
3704 Africa Lane, Maroko, Moba, Eti Osa, Lagos, Nigeria
3705 Dar es Salaam, Kinondoni, Dar es Salaam
3706 Kumasi, Ashanti Region, Ghana
3707 Holland, Nordrhein-Westfalen
3708 Ghana
3709 Wollongong, New South Wales
3710 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
3711 Nigeria
3712 Surabaya, Jawa Timur, 60174, Indonesia
3713 Tamil Nadu
3714 Ottawa County, Kansas, United States of America
3715 Pennsylvania
3716 Nairobi, Kenya
3717 San Siro, Milano
3718 Virginia, United States of America
3719 Manchester, Lancashire, England
3720 null
3721 Lancashire, England
3722 Україна
3723 Manchester, Lancashire, England
3724 Sandton, Randburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2128, South Africa
3725 Ghana
3726 null
3727 New York
3728 India
3729 Nigeria
3730 null
3731 Manchester United Methodist Church
3732 Kapsabet, Nandi, Kenya
3733 Crib
3734 Arsenal, Gillespie Road, Finsbury Park, London Borough of Islington, London, Greater London, England, N5 1LP, UK
3735 Manchester, Lancashire, England
3736 Natural Resources Canada Earth Sciences, 615, Booth Street, Little Italy, Centretown, Somerset, Ottawa, Ontario, K1R 7L2, Canada
3737 Queens, New York
3738 null
3739 Lagos, Lagos Island, Lagos
3740 Nigeria
3741 Lagos, Lagos Island, Lagos
3742 Inside, 23, Sankt-Pöltener-Straße, Feuerbach-Mitte, Feuerbach, Stuttgart, Regierungsbezirk Stuttgart, Baden-Württemberg, 70469, Deutschland
3743 San Siro, Milano
3744 null
3745 Accra, Accra Metropolis, Greater Accra
3746 null
3747 Developer
3748 A la Place, Labarrère, Castelnau d'Auzan Labarrère, Condom, Gers, Occitanie, France métropolitaine, 32250, France
3749 Port Harcourt, Rivers
3750 Hertfordshire, East of England, England, UK
3751 London, England
3752 England, UK

3753 London, England
3754 London, Greater London, England, UK
3755 London, England
3756 London, Greater London, England, UK
3757 Manchester, Lancashire, England
3758 Space, Exmouth Market, Finsbury, London Borough of Islington, London, Greater London, England, EC1, UK
3759 Lagos, Lagos Island, Lagos
3760 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
3761 Ayamonte, Huelva, Andalucía
3762 Nigeria
3763 Roma
3764 City of London, Greater London, England, UK
3765 Gmail
3766 Nigeria
3767 Dar es Salaam, Kinondoni, Dar es Salaam
3768 Bristol, City of Bristol, South West England, England, UK
3769 Polokwane, Capricorn, Limpopo
3770 Köln, Regierungsbezirk Köln, Nordrhein-Westfalen, 50667, Deutschland
3771 Singapore
3772 London, Greater London, England, UK
3773 Padanapalam, Kannur, Kerala
3774 Warri, Warri South, Delta, Nigeria
3775 Leeds, West Yorkshire, England
3776 Nigeria
3777 Lungi St, Abuja, Abuja Municipal, Federal Capital Territory
3778 London, Greater London, England, UK
3779 Cheshire, England
3780 Lagos, Lagos Island, Lagos, 71510, Nigeria
3781 Bergen, Hordaland
3782 Lagos, Lagos Island, Lagos, 71510, Nigeria
3783 Manchester, Lancashire, England
3784 My World, 105, Calle 19, Centro financiero de San Isidro, San Isidro, Lima, AN ISIDRO 15036, Perú
3785 Lagos, Lagos Island, Lagos
3786 null
3787 Héré, Département de la Creuse, Limousin
3788 Depression, Wilsonville, Macoupin County, Illinois, 62093, United States of America
3789 Indonesia
3790 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
3791 Kampala
3792 Osogbo, Olorunda, Osun, Nigeria
3793 Cape Town, Western Cape
3794 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
3795 Brighton, East Sussex, England
3796 null
3797 Lagos, Lagos Island, Lagos
3798 Enugu, Enugu North, Enugu, 400.0, Nigeria
3799 Lagos, Lagos Island, Lagos
3800 London, Greater London, England, UK
3801 With God
3802 SIC, Italia
3803 Tottenham, New Tecumseth, Ontario
3804 London, Greater London, England, UK
3805 South Africa
3806 Lagos, Lagos Island, Lagos, 71510, Nigeria
3807 Mumbai, Maharashtra
3808 null
3809 null
3810 Kenya
3811 Chesterfield, Derbyshire, England
3812 Proact Stadium, 1866, Sheffield Road, Whittington Moor, Chesterfield, Derbyshire, East Midlands, England, S41 8NZ, UK
3813 Manchester, Lancashire, England
3814 null
3815 Accra, Accra Metropolis, Greater Accra
3816 Gombe, Nigeria
3817 Lagos, Lagos Island, Lagos
3818 Greater Manchester, North West England, England, UK
3819 East Street, South Stifford, Grays, Essex, England, RM20 4
3820 Dar es Salaam, Coastal, Tanzania
3821 Madrid, Comunidad de Madrid
3822 Manchester, Greater Manchester, North West England, England, UK
3823 Göd, Dunakeszi Járás, Pest
3824 Virginia Museum of Fine Arts, 200, North Boulevard, Devil's Triangle, Museum District, Richmond, Richmond City, Virginia, 23220, United States of America
3825 Bauchi
3826 null
3827 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
3828 233, Stadtbezirk 10 Moosach, München, OB, Bayern, 80992, Deutschland
3829 Drexel University
3830 London, Greater London, England, UK
3831 Home and Away
3832 Nairobi, Kenya
3833 Manchester, Lancashire, England
3834 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3835 Nairobi
3836 Temple City, Los Angeles County, California, 91780, United States of America
3837 Blantyre, Southern Region
3838 null
3839 Straume, Vaksdal, Hordaland
3840 Lagos, Lagos Island, Lagos, 71510, Nigeria
3841 Jakarta, DKI Jakarta
3842 Calabar, Calabar Municipal, Cross River, Nigeria
3843 Anambra
3844 Manchester, Greater Manchester, North West England, England, UK
3845 Coimbatore, Tamil Nadu
3846 Nigeria
3847 Cape Town, Western Cape
3848 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
3849 Héré, Département de la Creuse, Limousin
3850 UTP, Persiaran Desa Kediaman, Seri Iskandar, PRK, 31750, Malaysia
3851 Trafford, Pennsylvania
3852 Reso: Out of this world, 1, Bismarckstraße, St. Johanner Markt, Sankt Johann, Bezirk Mitte, Saarbrücken, Regionalverband Saarbrücken, Saarland, 66111, Deutschland
3853 Nowhere, Oklahoma
3854 Loading, Endeavour Hills, City of Casey, Greater Melbourne, Victoria, 3802, Australia
3855 null
3856 Mumbai, Greater Bombay, Maharashtra, 400001, India
3857 OR
3858 Mumbai, Greater Bombay, Maharashtra, 400001, India
3859 Sylhet
3860 Anfield, Anfield Road, Walton, Liverpool, North West England, England, L4 0TH, UK
3861 Kelantan
3862 Manchester, Greater Manchester, North West England, England, UK
3863 Gucci
3864 杉並区, 東京都, 日本
3865 中华人民共和国
3866 null
3867 Gki Sulsel
3868 مدينة نصر, القاهرة, محافظة القاهرة, 11774, مصر
3869 Too Far North
3870 الإسكندرية, 21519, مصر
3871 West Lafayette, Indiana
3872 Anfield, Anfield Road, Walton, Liverpool, North West England, England, L4 0TH, UK
3873 Ipoh, Kinta, Perak
3874 Chicago Deep Dish Pizza, 3012, 17 Avenue SE, Southview, Calgary, Alberta, T2A 0Y8, Canada
3875 Singapore
3876 Pretoria, City of Tshwane Metropolitan Municipality, Gauteng, 0002, South Africa
3877 Melbourne, Victoria
3878 Corporation of Chennai, Chennai district, Tamil Nadu, India
3879 Nuneaton, Warwickshire, England
3880 null
3881 Johan Cruijff Court
3882 United States of America
3883 Ondo Rd, Akure, Akure South, Ondo
3884 Aurangābād, Aurangabad, Bihar, India
3885 Manchester, Lancashire, England
3886 Billericay, Essex, East of England, England, CM12 0AD, UK
3887 Cheerio
3888 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
3889 London, England
3890 NYC, New York, United States of America
3891 Thohoyandou, Vhembe, Limpopo
3892 null
3893 Kota Kinabalu, Division Pantai Barat Utara, Sabah
3894 Kaduna, Nigeria
3895 City, Cowbridge, South Glamorgan, Wales
3896 Pune, Maharashtra, 411001, India
3897 Jersey City, New Jersey
3898 Polperro, Cornwall, South West England, England, PL13 2RF, UK
3899 null
3900 Manchester, Greater Manchester, North West England, England, UK
3901 Andover, Hampshire, England
3902 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
3903 Adenta, Greater Accra
3904 London, Greater London, England, UK
3905 null
3906 null
3907 Chicago, Illinois
3908 null
3909 Puerto Rico, Caquetá
3910 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3911 UK
3912 Lagos, Lagos Island, Lagos, 71510, Nigeria
3913 United Kingdom
3914 Coventry, West Midlands Combined Authority, West Midlands, England, UK
3915 Coventry, West Midlands, England
3916 Down Over There Avenue, Wickenburg, Maricopa County, Arizona, AZ 85390, United States of America
3917 Manchester, Lancashire, England
3918 null
3919 Nigeria
3920 Nigeria
3921 Manchester, Lancashire, England
3922 Leeds, Yorkshire and the Humber, England, UK
3923 Main Avenue, Enfield, Middlesex, England, EN1 1
3924 Manchester, Greater Manchester, North West England, England, UK
3925 Hyderabad, Fateh Maidan, Hyderabad, Telangana
3926 Dublin, County Dublin, Leinster, Ireland
3927 Upton Park, Greater London, England
3928 null
3929 Bristol, Avon, England
3930 Seine-Saint-Denis, Île-de-France, France métropolitaine, France
3931 Oldtrafford
3932 Grove Street, Texas Township, Wayne County, Pennsylvania, 18431, United States of America
3933 Marseille, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur
3934 Kaduna, Nigeria
3935 Nice, Alpes-Maritimes, Provence-Alpes-Côte d'Azur
3936 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3937 Nigeria
3938 England, UK
3939 England
3940 Montréal, Montréal (06), Québec, Canada
3941 Malta
3942 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
3943 South East, England
3944 Nigeria
3945 Manchester, Lancashire, England
3946 Greater Accra Region, Ghana
3947 Vestfossen, Øvre Eiker, Buskerud
3948 Manchester, Greater Manchester, North West England, England, UK
3949 Northern Ireland
3950 Glenwood, Sydney, Blacktown, NSW, 2768, Australia
3951 KE
3952 Manchester, Greater Manchester, North West England, England, UK
3953 Gombe
3954 Sporting Way, Kansas City, Wyandotte County, Kansas, 66111-1953, United States of America
3955 Nilópolis, Rio de Janeiro
3956 Penang International Airport, Jalan Bayan Lepas, Bukit Gedung, Sungai Tiram, Bayan Lepas, PNG, 11900, Malaysia

3957 Michigan
3958 Lower Westside Route, PNB Ville Subdivision, Prieto Compound, Baguio, Benguet, Cordillera Administrative Region, 2600, Philippines
3959 Success, Missouri
3960 Manchester, Greater Manchester, North West England, England, UK
3961 Atlanta, Georgia
3962 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
3963 Klärastrasse, 4247, Grindel, Solothurn
3964 England, UK
3965 London, England
3966 Boston, Lincolnshire, East Midlands, England, UK
3967 Ghana
3968 Ghana
3969 Eire
3970 Manchester, Greater Manchester, North West England, England, UK
3971 Lagos, Lagos Island, Lagos
3972 Norge, Ytterbyvegen, Namsos, Nord-Trøndelag, 7810, Norge
3973 Engeland
3974 West Oxfordshire, Oxon, South East, England, UK
3975 Manchester, Lancashire, England
3976 London, Greater London, England, UK
3977 Lagos, Lagos Island, Lagos
3978 Winter Park, Orange County, Florida, 32789, United States of America
3979 Quito
3980 Calle Santiago Bernabéu, Chamartín, Madrid, Área metropolitana de Madrid y Corredor del Henares, Comunidad de Madrid, 28020, España
3981 Chicago, Illinois
3982 Lagos, Lagos Island, Lagos, 71510, Nigeria
3983 Nottingham, Nottinghamshire, England
3984 Cardiff, Wales, CF, UK
3985 Botswana
3986 木葉, 部田見木葉線, 玉東町, 玉名郡, 熊本県, 日本
3987 Somewhere
3988 null
3989 Toronto, Ontario
3990 Lagos, Lagos Island, Lagos, 71510, Nigeria
3991 Cardiff, South Glamorgan, Wales
3992 Sydney, NSW, Australia
3993 Ici
3994 Lappeenranta, Lappeenrannan seutukunta, Etelä-Karjala, Etelä-Suomi, Manner-Suomi, Suomi
3995 Stockport, Cheshire, England
3996 Lagos, Lagos Island, Lagos, 71510, Nigeria
3997 Dar es Salaam, Kinondoni, Dar es Salaam
3998 null
3999 Chelsea, London, England
4000 Nigeria
4001 Boulevard, Utah
4002 Lagos, Lagos Island, Lagos, 71510, Nigeria
4003 Manchester, Lancashire, England
4004 Manchester, Greater Manchester, North West England, England, UK
4005 Gurgaon, Sector 29, Gurgaon, Haryana
4006 London, Greater London, England, UK
4007 Manchester, Lancashire, England
4008 UK
4009 South Africa
4010 Teignmouth, Devon, South West England, England, TQ14 8AJ, UK
4011 New Delhi, Connaught Place, New Delhi, Delhi
4012 Manchester, Greater Manchester, North West England, England, UK
4013 Lagos, Lagos Island, Lagos
4014 Polokwane, Capricorn District Municipality, Limpopo, 0700, South Africa
4015 Liverpool, Merseyside, England
4016 Hale County, Alabama, United States of America
4017 England
4018 null
4019 Ghana, Kano
4020 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
4021 Limerick
4022 London, Greater London, England, UK
4023 United Kingdom
4024 null
4025 Lagos, Lagos Island, Lagos
4026 London, Greater London, England, UK
4027 Warrington, Cheshire, England
4028 Tiber Park - Kingsley United FC, Coltart Road, Edge Hill, Liverpool, North West England, England, L8, UK
4029 Ghana
4030 null
4031 Bristol, Avon, England
4032 Joži, Dobeles novads, Zemgale, LV-3145, Latvija
4033 Sverige
4034 null
4035 Pretoria, Tshwane, Gauteng
4036 South Africa
4037 null
4038 Limerick, County Limerick, Munster, V94 A9NX, Ireland
4039 Free State
4040 null
4041 Premier League Shop
4042 Lagos, Lagos Island, Lagos, 71510, Nigeria
4043 London, England
4044 Kenya
4045 Lot, Occitanie
4046 London, Greater London, England, UK
4047 Durban, eThekwini, Kwazulu Natal
4048 Broadway, Fieldston, Bronx County, NYC, New York, 10471, United States of America
4049 Kingston
4050 Newcastleton, Scottish Borders, Scotland, TD9 0QU, UK
4051 Stratford, London, England
4052 null
4053 Ghana
4054 null
4055 Manchester, Lancashire, England
4056 London, Greater London, England, UK
4057 Sleaford, Lincolnshire, England
4058 Chelsea Football Club, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
4059 Ghana
4060 Le Lair, Avranches, Manche, Normandie, France métropolitaine, 50730, France
4061 East
4062 Canada
4063 USA
4064 Kluang, Muar, Johor, 86000, Malaysia
4065 Manchester, Lancashire, England
4066 Valsād, Valsad, Gujarat, India
4067 United Kingdom
4068 null
4069 Cia
4070 Manchester, Greater Manchester, North West England, England, UK
4071 Chicago, Illinois
4072 London, Greater London, England, UK
4073 Miranda, Falcón
4074 Manchester, Greater Manchester, North West England, England, UK
4075 Huddersfield, West Yorkshire, England
4076 London, Greater London, England, UK
4077 Lagos, Lagos Island, Lagos
4078 Dark, Hughs, Luzerne County, Pennsylvania, 18634, United States of America
4079 null
4080 Maryland, United States of America
4081 Grenfell Ct, London, Ontario, N5X
4082 Flint, Flintshire, Wales, CH6 5AJ, UK
4083 Ghana
4084 Essex Road, Vincent, East London, East London, Buffalo City Metropolitan Municipality, Eastern Cape, 5247, South Africa
4085 Cape Town, Western Cape
4086 null
4087 England
4088 Zaria, Kaduna, Nigeria
4089 Jacksonville, Florida
4090 Lusaka, Lusaka Province, Zambia
4091 England
4092 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
4093 Mumbai, Maharashtra
4094 Planet Earth, SR 14, Edinburg, Edinburg Township, Portage County, Ohio, United States of America
4095 Old Trafford, Manchester, Lancashire, England
4096 Manchester, Greater Manchester, North West England, England, UK
4097 Riding, Pangkalan Lapam, Ogan Komering Ilir, Sumatera Selatan
4098 Nairobi, Kenya
4099 Manchester, Lancashire, England
4100 PRK, Malaysia
4101 null
4102 Hyderabad, Telangana, India
4103 Earth, Texas
4104 Manchester, Greater Manchester, North West England, England, UK
4105 Chemin Grenier, Savanne
4106 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4107 New Delhi, Connaught Place, New Delhi, Delhi
4108 No Mans Land, Knox County, Maine, United States of America
4109 Lagos, Lagos Island, Lagos
4110 null
4111 Kenya
4112 Lion City, សង្កាត់កាកាប, ខណ្ឌពោធិ៍សែនជ័យ, រាជធានីភ្នំពេញ, ព្រះរាជាណាចក្រ​កម្ពុជា
4113 Dunboy, Bantry, Cork
4114 Partington, Greater Manchester, North West England, England, M31 4PY, UK
4115 Nottingham, Nottinghamshire, England
4116 Malaysia
4117 UK
4118 Қазақстан
4119 Dubai
4120 Malaysia
4121 Swansea, West Glamorgan, Wales
4122 Saint Martins, Batchworth, Three Rivers, Hertfordshire, East of England, England, HA6 2AT, UK
4123 Corners, Missouri
4124 East Kilbride, South Lanarkshire, Scotland, UK
4125 Owerri, Owerri Municipal, Imo
4126 Wakefield, Yorkshire and the Humber, England, UK
4127 England
4128 Shore Road, Ballyvanen, Lower Ballinderry, County Antrim, Northern Ireland, BT29 4LZ, UK
4129 United States
4130 St James' Park, Barrack Road, Grainger Town, Newcastle upon Tyne, Tyne and Wear, North East England, England, NE1 4ST, UK
4131 World
4132 null
4133 Manchester, Lancashire, England
4134 Barcelona, BCN, CAT, España
4135 Manchester, Lancashire, England
4136 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
4137 Cape Town, Western Cape
4138 Nigeria
4139 Seattle, Washington
4140 null
4141 Dublin
4142 Chicago, Cook County, Illinois, United States of America
4143 Mars, Pennsylvania
4144 Bogor, Jalan Tol Jagorawi, Sukatani, Jawa Barat, 452, Indonesia
4145 Dublin
4146 London, Greater London, England, UK
4147 Astro World
4148 ڪراچي Karachi, Karāchi District, سنڌ, ‏پاکستان‎
4149 Stockport, Cheshire, England
4150 Uganda
4151 Southside, Alabama
4152 Olsztyn, warmińsko-mazurskie, RP
4153 London, England
4154 فیصل آباد, Faisalābād District, پنجاب, 38000, ‏پاکستان‎
4155 University of East Anglia
4156 Nigeria
4157 London, England
4158 null
4159 Nairobi
4160 РФ
4161 Manchester, Lancashire, England
4162 Tottenham, London Borough of Haringey, London, Greater London, England, N17 9TR, UK
4163 Manuta, Niassa
4164 Manchester, Greater Manchester, North West England, England, UK
4165 Lagos, Lagos Island, Lagos
4166 null
4167 Accra, Accra Metropolis, Greater Accra
4168 Manchester United, Tavarekere Main Road, Prestige Acropolis, Adugodi, Bengaluru, Bangalore Urban, Karnataka, 560001, India
4169 Kaduna, Kaduna North, Kaduna
4170 Liverpool, North West England, England, UK
4171 Lima, Provincia de Lima
4172 NYC, New York, United States of America
4173 Pilani, Jhunjhunu, Rajasthan
4174 Singapore, Central, 178957, Singapore
4175 Manchester, Lancashire, England
4176 Lagos, Lagos Island, Lagos, 71510, Nigeria

4177 Welling, Kent, England
4178 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
4179 เมืองวิทยา
4180 South Africa
4181 Zimbabwe
4182 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
4183 Tangerang Selatan, Ciputat, Tangerang, Banten
4184 Eastern Region, Ghana
4185 London, England
4186 Deutschland, Europe
4187 Gotham, Wisconsin
4188 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4189 Bangor, County Down, Northern Ireland
4190 Manchester, Greater Manchester, North West England, England, UK
4191 Labuan, Wilayah Persekutuan
4192 Foxhall ED, Lurgan, County Longford, Leinster, Ireland
4193 Manchester, Lancashire, England
4194 Bengaluru, Bangalore Urban, Karnataka, 560001, India
4195 Gaborone
4196 Manchester, Greater Manchester, North West England, England, UK
4197 King Williams Town, Grand Kru
4198 Österreich
4199 Glasgow Rd, Bastrop, Louisiana, 71220
4200 Paris, Île-de-France, France métropolitaine, France
4201 Yogyakarta, Daerah Istimewa Yogyakarta
4202 Indonesia
4203 England
4204 null
4205 Pietermaritzburg, uMgungundlovu, Kwazulu Natal
4206 null
4207 Singapore
4208 null
4209 null
4210 Malta
4211 Corsham, Wiltshire, England
4212 null
4213 Nigeria
4214 Côte d’Ivoire
4215 null
4216 San Jose Diridon, Laurel Grove Lane, Plant 51, Buena Vista, San José, Santa Clara County, California, 95110, United States of America
4217 Lancashire, England
4218 木葉, 部田見木葉線, 玉東町, 玉名郡, 熊本県, 日本
4219 Old Trafford, Manchester, Lancashire, England
4220 Manchester, Greater Manchester, North West England, England, UK
4221 Ayam Bandung
4222 Singaraja, Bali, 81113, Indonesia
4223 Pakistan
4224 South Sudan
4225 Manchester, Lancashire, England
4226 New Delhi, Delhi, India
4227 Nigeria
4228 Manchester, Greater Manchester, North West England, England, UK
4229 Indonesia
4230 North Andover, Essex, Massachusetts, United States of America
4231 South
4232 LA, Los Angeles County, California, United States of America
4233 Vieux Carre, New Orleans, Louisiana
4234 Malaysia
4235 Nairobi
4236 Liverpool, North West England, England, UK
4237 Durban, eThekwini, Kwazulu Natal
4238 Anfield, Anfield Road, Walton, Liverpool, North West England, England, L4 0TH, UK
4239 Melbourne, Derby, Derbyshire, England
4240 Milwaukee, Milwaukee County, Wisconsin, United States of America
4241 Dallas, Texas
4242 España
4243 London, England
4244 Mombasa, Kenya
4245 Abuja, Abuja Municipal, Federal Capital Territory
4246 Cork Street, St. James's, Mayfair, City of Westminster, London, Greater London, England, W1S 1PY, UK
4247 Manchester, Lancashire, England
4248 Milwaukee, Milwaukee County, Wisconsin, United States of America
4249 Miami, Florida
4250 Lebanon, Lebanon County, Pennsylvania, United States of America
4251 England
4252 Manchester, Greater Manchester, North West England, England, UK
4253 Kuching, Division Kuching, Sarawak
4254 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
4255 null
4256 Stamford Bridge, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
4257 Matuu, Machakos
4258 London, Greater London, England, UK
4259 Weymouth, Dorset, England
4260 Corporation of Chennai, Chennai district, Tamil Nadu, India
4261 Perak, Temerloh, Pahang
4262 Mississauga, Algoma District, Ontario, Canada
4263 Blue Moon, Kentucky
4264 Mombasa, Kenya
4265 Cuba
4266 Nice, Alpes-Maritimes, Provence-Alpes-Côte d'Azur, France métropolitaine, France
4267 Egypt
4268 ‏البحرين‎
4269 Kenya
4270 Nigeria
4271 Lagos, Lagos Island, Lagos
4272 Ayr, South Ayrshire, Scotland, KA7 2BA, UK
4273 United Kingdom
4274 Cardiff, Wales, CF, UK
4275 United States
4276 null
4277 South East, England
4278 Paris, Île-de-France, France métropolitaine, France
4279 Kochi, Ernakulam, Kerala
4280 BH, Microrregião Belo Horizonte, Região Metropolitana de Belo Horizonte, Mesorregião Metropolitana de Belo Horizonte, MG, Região Sudeste, Brasil
4281 Manchester, Lancashire, England
4282 Whitley Bay, Tyne and Wear, North East England, England, NE26 2RA, UK
4283 São José dos Pinhais, Paraná
4284 null
4285 Houzz
4286 Mumbai, Greater Bombay, Maharashtra, 400001, India
4287 Hale, Altrincham, Cheshire, England
4288 NSN, Malaysia
4289 Bottomless Pit
4290 Trondheim, Sør-Trøndelag, 7011, Norge
4291 London, England
4292 Sthlm, Stockholm, Landskapet Uppland, Stockholms län, Svealand, 11129, Sverige
4293 Hubli City, Karnātaka
4294 Gold Coast, Gold Coast City, QLD, 4217, Australia
4295 Driehoek, Provincie Oost-Vlaanderen
4296 null
4297 null
4298 Sverige
4299 United Kingdom
4300 Tiber Park - Kingsley United FC, Coltart Road, Edge Hill, Liverpool, North West England, England, L8, UK
4301 Selangor Darul Ehsan
4302 Kuala Lumpur, Gorontalo, Indonesia
4303 Cape Town St, Cosmo City, Johannesburg, Gauteng, 2188
4304 Ife, Ife Central, Osun, Nigeria
4305 Manchester, Lancashire, England
4306 Joži, Dobeles novads, Zemgale, LV-3145, Latvija
4307 Nairobi
4308 null
4309 Rihāna, Himachal Pradesh
4310 England, UK
4311 Kenya
4312 Liverpool, North West England, England, UK
4313 Menari
4314 پنجاب, ‏پاکستان‎
4315 Kampala
4316 Leeds, Yorkshire and the Humber, England, UK
4317 Alsace
4318 New Delhi, Delhi, India
4319 Town Plaza
4320 Kampung Tengah, K Pasu;Kbg Pasu, Kedah, 06100, Malaysia
4321 Seychelles
4322 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
4323 Pasir Mas, Kelantan
4324 null
4325 Fantini, Provincia di Cosenza
4326 Manchester, Greater Manchester, North West England, England, UK
4327 Nairobi
4328 Canada, Welkenraedt, Verviers, Liège, Wallonie, 4840, België - Belgique - Belgien
4329 Malaysia
4330 Kota Bharu, Kelantan, 15990, Malaysia
4331 Manchester, Lancashire, England
4332 Singapore, Central, 178957, Singapore
4333 India
4334 Malaysia
4335 Georgetown, Timur Laut, Pulau Pinang
4336 Gombak, Selangor, 53100, Malaysia
4337 Anfield, Gordon, New Brunswick
4338 null
4339 Singapore
4340 K&L, Künzeller Straße, Neuenberg, Fulda, Landkreis Fulda, Regierungsbezirk Kassel, Hessen, 36043, Deutschland, Europe
4341 South St, Geluk SH, Bloemfontein, Mangaung, Free State, 9301
4342 Malaysia
4343 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
4344 Malaysia
4345 Nairobi
4346 null
4347 Manuta, Niassa
4348 Gata de Gorgos, Marina Alta, Alicante/Alacant, Comunitat Valenciana, España
4349 Selangor
4350 null
4351 Menai Bridge, Gwynedd, Wales
4352 Putra Nilai, Jalan Square Utama, Nilai, NSN, 71800, Malaysia
4353 Makurdi, Benue
4354 Ina Boi, Kec. Oebobo, Kupang, Nusa Tenggara Timur, 85226, Indonesia
4355 Doha, Al Doha
4356 59, Донецьк, Кіровський район, Донецька міська рада, Донецька область, 83000-83490, Україна
4357 Upside Down
4358 South Africa
4359 England, Arkansas
4360 Île-de-France, France métropolitaine, France
4361 Parit Raja, Batu Pahat, Johor
4362 City of Edinburgh, Scotland, UK
4363 Milano
4364 Swansea, West Glamorgan, Wales, SA1 3ES, UK
4365 Indonesia
4366 Aarhus, Aarhus Kommune, Region Midtjylland, 8000, Danmark
4367 Johannesburg, Gauteng
4368 Semarang, Jawa Tengah, 50241, Indonesia
4369 Dar es Salaam, Kinondoni, Dar es Salaam
4370 ‏پاکستان‎
4371 Manchester, Lancashire, England
4372 Coulsdon, London, Greater London, England, CR5 2NF, UK
4373 Oldham, Lancashire, England
4374 Sydney, NSW, Australia
4375 Anfield
4376 Hyderabad, Telangana, India
4377 null
4378 Côte d’Ivoire
4379 Grahamstown, Sarah Baartman, Eastern Cape
4380 LDN, Maďarská, Bubeneč, Praha, okres Hlavní město Praha, Hlavní město Praha, Praha, 1, Česko
4381 El Sharkia
4382 null
4383 Bekasi, Bekasi Selatan, Bekasi, Jawa Barat
4384 Solo, Sulawesi Utara, Indonesia
4385 London, England
4386 India
4387 Abuja, Abuja Municipal, Federal Capital Territory
4388 Le Paris, Place Gabriel Péri, Les Grandes Crèles, Vierzon, Cher, Centre-Val de Loire, France métropolitaine, 18100, France
4389 Charlotte, North Carolina
4390 Limerick, County Limerick, Munster, V94 A9NX, Ireland
4391 Sverige
4392 null
4393 San Siro, Milano
4394 Ireland
4395 Wales
4396 বাংলাদেশ
4397 Barrow-in-Furness, Cumbria, England
4398 Terre Haute, Vigo County, Indiana, United States of America
4399 Stockport, Cheshire, England
4400 Katsina, Nigeria
4401 Northern Ireland

4402 New Delhi, Delhi, India
4403 Ibadan, Oyo
4404 Indore, Madhya Pradesh, India
4405 Belfast, County Antrim, Northern Ireland
4406 Stratton, Cornwall, South West England, England, EX23 9DN, UK
4407 Alternate Universe
4408 London, Greater London, England, UK
4409 København, Hovedstaden
4410 Manchester, Greater Manchester, North West England, England, UK
4411 Kingdom of Saudi Arabia
4412 null
4413 Oxford, Oxfordshire, England
4414 Nigeria
4415 Cowes, Isle of Wight, England
4416 Tamale, Northern Region, P.O. BOX 232, Ghana
4417 Anfield, Liverpool, Merseyside, England
4418 null
4419 Manchester, Lancashire, England
4420 Kent, South East, England, UK
4421 Manchester, Lancashire, England
4422 Mumbai, Greater Bombay, Maharashtra, 400001, India
4423 London, England
4424 null
4425 Kenya
4426 Nigeria
4427 Kingdom, Illinois
4428 null
4429 World
4430 London, Greater London, England, UK
4431 Surrey, Whalley, Surrey, British Columbia
4432 null
4433 Manchester, Lancashire, England
4434 Liverpool, North West England, England, UK
4435 Lagos, Lagos Island, Lagos
4436 Lagos, Lagos Island, Lagos, 71510, Nigeria
4437 Brackley, Northamptonshire, England
4438 Lagos, Lagos Island, Lagos, 71510, Nigeria
4439 England, Naledi, Dr Ruth Segomotsi Mompati, North West
4440 Dichemso Road, Ashtown, Kumasi, Ashanti Region, Ghana
4441 Cape Town, Western Cape
4442 Manchester, Greater Manchester, North West England, England, UK
4443 Cork
4444 null
4445 Minna, Chanchaga, Niger
4446 Porthmadog, Gwynedd, Wales, LL49 9AR, UK
4447 Águilas, Murcia, Región de Murcia
4448 Lagos, Lagos Island, Lagos, 71510, Nigeria
4449 Lagos, Lagos Island, Lagos
4450 Navi Mumbai, Greater Bombay, Maharashtra, 400614, India
4451 Ireland
4452 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
4453 Coleraine, County Londonderry, Northern Ireland
4454 England, UK
4455 Downtown, Pennsylvania
4456 Bengaluru, Bangalore Urban, Karnataka, 560001, India
4457 Manchester, Lancashire, England
4458 null
4459 Uganda
4460 null
4461 Manchester, Lancashire, England
4462 नेपाल
4463 Manchester, Lancashire, England
4464 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4465 Matrix
4466 null
4467 Lilongwe, Central Region
4468 Manchester, Greater Manchester, North West England, England, UK
4469 null
4470 South Shore, Blyth, Northumberland, North East England, England, UK
4471 Manchester, Lancashire, England
4472 Dream Land, Poblacion West, Cebu City, Cebu, Central Visayas, 6032, Philippines
4473 United Kingdom
4474 Suomi
4475 Dar es Salaam, Kinondoni, Dar es Salaam
4476 null
4477 Singapore
4478 Balikpapan, Kalimantan Timur, 76128, Indonesia
4479 Abuja, Abuja Municipal, Federal Capital Territory
4480 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
4481 Lagos, Lagos Island, Lagos
4482 Mumbai, Greater Bombay, Maharashtra, 400001, India
4483 Taraba State
4484 null
4485 Lagos, Lagos Island, Lagos
4486 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
4487 Decflex
4488 Kidlington, Oxon, South East, England, OX5, UK
4489 Manchester, Lancashire, England
4490 Location, Tucker County, West Virginia, United States of America
4491 Ghana
4492 null
4493 Bedford, Bedfordshire, England
4494 Lekki, Ibeju Lekki, Lagos, Nigeria
4495 Ghana
4496 Nigeria
4497 Manchester, Lancashire, England
4498 Kottayam, Kerala, 686001, India
4499 Aydın, Efeler, Aydın
4500 Nigeria
4501 Home and Away
4502 Lagos, Lagos Island, Lagos, 71510, Nigeria
4503 Gidi, Dari, Hazaribagh, Jharkhand
4504 Lagos, Lagos Island, Lagos, 71510, Nigeria
4505 Nyc
4506 Salford, Greater Manchester, North West England, England, UK
4507 Kajang, Hulu Langat, Selangor
4508 Stanford, Lincoln County, Kentucky, United States of America
4509 Kathmandu, Bagmati
4510 null
4511 Belfast, County Antrim, Northern Ireland
4512 Ibadan, Ibadan North West, Oyo, 23402, Nigeria
4513 Ibadan, Oyo
4514 Manchester, Greater Manchester, North West England, England, UK
4515 Bristol, Avon, England
4516 Manchester, Greater Manchester, North West England, England, UK
4517 Malaysia
4518 Home & Away, The Crescent, Holme Head, Currock, Carlisle, Cumbria, North West England, England, CA1 1QN, UK
4519 Guayaquil
4520 Ampang, Selangor, 6, Malaysia
4521 Felgueiras, Porto
4522 Nigeria
4523 England
4524 Indonesia
4525 Sokoto
4526 Somolu, Abule Ijesha, Shomolu, Lagos, YABA, Nigeria
4527 House of Cards
4528 Pulau Manis, Batam, Kepulauan Riau, Indonesia
4529 England
4530 Caernarfon, Gwynedd, Wales, LL, UK
4531 Leicester, Leicestershire, England
4532 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
4533 Lagos, Lagos Island, Lagos
4534 Dublin, County Dublin, Leinster, Ireland
4535 Cork
4536 Damansara, NKVE, PJU3, Mutiara Damansara, PJ, Selangor, 47820, Malaysia
4537 Abuja, Abuja Municipal, Federal Capital Territory
4538 Sokoto, Nigeria
4539 Nairobi
4540 Yola, Hong, Adamawa, Nigeria
4541 Heaven
4542 Manchester, Greater Manchester, North West England, England, UK
4543 Manchester, Lancashire, England
4544 Ballhof, 5, Ballhofstraße, Kreuzkirchenviertel, Mitte, Hannover, Region Hannover, Niedersachsen, 30159, Deutschland
4545 Gaborone
4546 Cimetière de Bruxelles - Begraafplaats van Brussel, Evere, Brussel-Hoofdstad - Bruxelles-Capitale, Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest, 1140, België - Belgique - Belgien
4547 Chelsea, London, England
4548 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4549 UAE
4550 Ikeja, Lagos, 100281, Nigeria
4551 Harare
4552 Indonesia
4553 The Sky
4554 Manchester, Greater Manchester, North West England, England, UK
4555 Mohd Suhaimi
4556 Leicester, East Midlands, England, LE1 5YA, UK
4557 Njarðvík, Reykjanesbær, Reykjanes
4558 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
4559 Liverpool
4560 England, UK
4561 Cork
4562 Chandigarh, District of Chandigarh, Union Territory of Chandīgarh, 160022, India
4563 Nancy, Meurthe-et-Moselle, Grand Est
4564 Liverpool, North West England, England, UK
4565 Belfast, County Antrim, Northern Ireland
4566 Hyderabad, Telangana, India
4567 Leicester, Leicestershire, England
4568 Makurdi North, Markurdi, Benue, Nigeria
4569 Malawi
4570 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4571 Dhaka
4572 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
4573 Glasgow, Lanarkshire, Scotland
4574 Новосибирск, городской округ Новосибирск, Новосибирская область, СФО, 630000, РФ
4575 Manchester, Lancashire, England
4576 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4577 Randalstown, Antrim, County Antrim, Northern Ireland
4578 Chicago, Cook County, Illinois, United States of America
4579 Be
4580 Wexford, County Wexford, Leinster, Y35 WY93, Ireland
4581 United Kingdom
4582 Singapore, Better Living Subdivision, Don Bosco, Parañaque, Metro Manila, 1700, Philippines
4583 Manchester, Lancashire, England
4584 Johore Strait, Jalan Persiaran Senibong, Kampung Setanggi, Johor Bahru, Johor, 80400, Malaysia
4585 Kaduna, Kaduna North, Kaduna
4586 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4587 Glossop, Derbyshire, England
4588 Manchester, Greater Manchester, North West England, England, UK
4589 Bengaluru, Karnataka
4590 Holy Heart of Mary High School, Bonaventure Avenue, Georgestown, St. John's, Newfoundland and Labrador, A1C 5P9, Canada
4591 Pilani, Jhunjhunu, Rajasthan
4592 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
4593 Manchester, Lancashire, England
4594 ประเทศไทย
4595 Manchester, Lancashire, England
4596 null
4597 Manchester, Lancashire, England
4598 London, Greater London, England, UK
4599 Rochdale, Lancashire, England
4600 null
4601 Manchester, Lancashire, England
4602 Murcia, Área Metropolitana de Murcia, Murcia, España
4603 India
4604 Manchester, Greater Manchester, North West England, England, UK
4605 Blackburn, Lancashire, England
4606 Suomi
4607 New York
4608 Deutschland, Europe
4609 36000
4610 Stade Bonal, Rue de Chambrier, Ferme des Gouttes, Montbéliard, Doubs, Bourgogne-Franche-Comté, France métropolitaine, 25200, France
4611 Liverpool, Merseyside, England
4612 Surulere, Oyo, Nigeria

4613 Humerus
4614 null
4615 Tgg
4616 ประเทศไทย
4617 Nigeria
4618 Schweiz/Suisse/Svizzera/Svizra
4619 Belgium
4620 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4621 France
4622 null
4623 Россия
4624 Plymouth, South West England, England, PL1 1HH, UK
4625 Panaji, North Goa, Goa
4626 Gombe, Nigeria
4627 Sepang, Selangor
4628 Durban, eThekwini Metropolitan Municipality, KwaZulu-Natal, 4057, South Africa
4629 Waterford
4630 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
4631 USA
4632 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4633 Space
4634 null
4635 Accra, Accra Metropolis, Greater Accra
4636 London, Greater London, England, UK
4637 Pahang
4638 null
4639 Haret El Shah, Karmouz East, Karmouz, Alexandria
4640 Kuala Lumpur, Jalan Pekeliling KLIA, Kampung Baru Lanjut, Salak, Sepang, Selangor, 71760, Malaysia
4641 Manchester, Lancashire, England
4642 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
4643 Meh, Barun, Aurangabad, Bihar
4644 null
4645 Old Trafford, Manchester, Lancashire, England
4646 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4647 Malaysia
4648 UPM, Jalan Maklumat, Seri Serdang, MARDI Serdang, Selangor, 43400, Malaysia
4649 Malaysia
4650 Stretford End, Railway Road, Wharfside, Trafford, Greater Manchester, North West England, England, M32 0RZ, UK
4651 null
4652 Jalan Hulu Kelang 27/46, Taman Alam Indah, Sekysen 27, Subang Jaya, Selangor, 47600, Malaysia
4653 Malaysia
4654 Dundee, Dundee City, Scotland, DD1 4DG, UK
4655 Pontian, Johor
4656 My house, Giurgiu, 87043, România
4657 Southside, Alabama
4658 Lagos, Lagos Island, Lagos, 71510, Nigeria
4659 Hawa
4660 null
4661 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
4662 Johore Strait, Jalan Persiaran Senibong, Kampung Setanggi, Johor Bahru, Johor, 80400, Malaysia
4663 Com, Asson, Pyrénées-Atlantiques, Nouvelle-Aquitaine
4664 Kaduna, Nigeria
4665 Kampala
4666 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
4667 Украина
4668 Harare, Harare Province, 0000, Zimbabwe
4669 Botswana
4670 محمد الفذ, صلاح الدين, العراق
4671 United Kingdom
4672 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4673 Old Trafford, Manchester, Lancashire, England
4674 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4675 Jannah, Maysan
4676 Chelsea, Royal Borough of Kensington and Chelsea, London, Greater London, England, SW3 5EE, UK
4677 Pretoria, Tshwane, Gauteng
4678 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
4679 Lagos, Lagos Island, Lagos
4680 MUFC Ticketing and Membership Services, Bridgewater Canal Towpath, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0SZ, UK
4681 Accra, Accra Metropolis, Greater Accra
4682 null
4683 Hale, Altrincham, Cheshire, England
4684 null
4685 Manchester, Maryland
4686 Bekasi, Jawa Barat, 17136, Indonesia
4687 Manchester, Lancashire, England
4688 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
4689 null
4690 London, Greater London, England, UK
4691 Abuja, Abuja Municipal, Federal Capital Territory
4692 Barcelona, BCN, CAT, España
4693 Leeds, West Yorkshire, England
4694 City of Edinburgh, Scotland, UK
4695 Minneapolis, Minnesota
4696 64, Cottbus, Brandenburg, 03054, Deutschland
4697 United Kingdom
4698 Lagos, Lagos Island, Lagos, 71510, Nigeria
4699 Indonesia
4700 Bristol, City of Bristol, South West England, England, UK
4701 Kamar, Ghaznī
4702 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
4703 茨城県守谷市薬師台７
4704 null
4705 كويت
4706 Yorkshire and the Humber, England, UK
4707 Mafikeng, Ngaka Modiri Molema, North West
4708 Gombak, Selangor, 53100, Malaysia
4709 United Kingdom
4710 Nairobi, Kenya
4711 Old Trafford, Manchester, Lancashire, England
4712 Swansea, West Glamorgan, Wales, SA1 3ES, UK
4713 Kandi, Murshidabad, West Bengal
4714 Lagos, Lagos Island, Lagos, 71510, Nigeria
4715 Zimbabwe
4716 null
4717 Lagos, Lagos Island, Lagos
4718 null
4719 Somewhere
4720 Rwanda
4721 Birmingham, West Midlands, England
4722 null
4723 United Kingdom
4724 Ghana
4725 Ghana
4726 Zanzibar, Tanzania
4727 Ikeja, Lagos
4728 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
4729 Lagos, Lagos Island, Lagos
4730 Kenya
4731 Stockport, Cheshire, England
4732 London, Greater London, England, UK
4733 Lagos, Lagos Island, Lagos
4734 Mumbai, Greater Bombay, Maharashtra, 400001, India
4735 Tomorrow
4736 Nairobi, Kenya
4737 Nairobi
4738 Lagos, Lagos Island, Lagos, 71510, Nigeria
4739 Lagos, Lagos Island, Lagos
4740 Manchester, Greater Manchester, North West England, England, UK
4741 Straight, Oklahoma
4742 Sydney, NSW, Australia
4743 Australia
4744 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4745 Accra, Accra Metropolis, Greater Accra
4746 null
4747 Melbourne, Victoria
4748 UK
4749 Jinja
4750 Bengaluru, Bangalore Urban, Karnataka, 560001, India
4751 Somewhere
4752 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
4753 Accra, Accra Metropolis, Greater Accra
4754 Manchester, Greater Manchester, North West England, England, UK
4755 Somewhere
4756 Owerri, Owerri Municipal, Imo, Nigeria
4757 Tanzania
4758 España
4759 Leeds, West Yorkshire, England
4760 España
4761 Nairobi
4762 London, Greater London, England, UK
4763 Lekki, Lagos
4764 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4765 Gaborone
4766 Pennsylvania, United States of America
4767 Gaborone
4768 Cardiff, Wales, CF, UK
4769 Kediri, East Java
4770 Lekki, Ilaje, Ondo, Nigeria
4771 null
4772 Gaborone, South-East District, 09267, Botswana
4773 Dublin city, Dublin, Leinster
4774 Cardiff, Wales, CF, UK
4775 Ghana
4776 null
4777 London, England
4778 Ulcombe, Kent, South East, England, ME17 1DZ, UK
4779 Johannesburg, Gauteng
4780 Nigeria
4781 London, England
4782 Harare, Harare Province, 0000, Zimbabwe
4783 Ibadan St, Lagos, Ifo, Ogun
4784 Luweero, Central Region, Uganda
4785 Kenya
4786 null
4787 Lagos, Lagos Island, Lagos
4788 null
4789 Canopy
4790 Mumbai, Greater Bombay, Maharashtra, 400001, India
4791 Ghana
4792 Lagos, Lagos Island, Lagos, 71510, Nigeria
4793 Indonesia
4794 Adenta Dodowa Road, Adenta, Oyibi, Adenta, Greater Accra Region, PMB 107 MD, Ghana
4795 Nigeria
4796 Nakuru, Kenya
4797 United Kingdom
4798 Lagos, Lagos Island, Lagos, 71510, Nigeria
4799 Around the World
4800 null
4801 Montpellier, Hérault, Occitanie
4802 Singapore, Central, 178957, Singapore
4803 Nigeria
4804 null
4805 Zimbabwe
4806 上海市, 黄浦区, 上海市, 200010, 中国
4807 Kaduna, Kaduna North, Kaduna
4808 Nairobi, Kenya
4809 Zwaneville, West Rand, Gauteng, 1750
4810 null
4811 Bekasi, Bekasi Selatan, Bekasi, Jawa Barat
4812 null
4813 Nigeria
4814 Emirates Stadium, 75, Drayton Park, Finsbury Park, London Borough of Islington, London, Greater London, England, N5 1BU, UK
4815 Ogun State, Ogun
4816 Manchester, Greater Manchester, North West England, England, UK
4817 Nigeria
4818 Chemin de Fer de Dieppe au Havre, D 150, Valmont, Le Havre, Seine-Maritime, Normandie, France métropolitaine, 76540, France
4819 London, England
4820 null
4821 Lagos, Lagos Island, Lagos
4822 Bengaluru, Bangalore Urban, Karnataka, 560001, India
4823 South Wales
4824 Chelsea Football Club, Hilary Close, Walham Green, London Borough of Hammersmith and Fulham, London, Greater London, England, SW6 1DU, UK
4825 Vashi, Navi Mumbai, Thane, Maharashtra
4826 Lion's Den, 18010, East 181st Avenue, Dinwiddie, Lake County, Indiana, 46341, United States of America
4827 Tokoza, Ekurhuleni, Gauteng
4828 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
4829 Newlands West, eThekwini, Kwazulu Natal
4830 null
4831 Min, Tibet Autonomous Region
4832 null
4833 Karachi, Karāchi District, Sindh
4834 Nairobi, Kenya
4835 Abuja, Abuja Municipal, Federal Capital Territory
4836 null
4837 Abuja
4838 Uniport, Physics department, Kubiri, Makerere, Kawempe, Kampala, Central Region, P.O. BOX 36152 KAMPALA, Uganda
4839 London, England

4840 Kampala, Central Region, 7063, Uganda
4841 Nigeria
4842 SP, Microrregião de São Paulo, RMSP, Mesorregião Metropolitana de São Paulo, SP, Região Sudeste, Brasil
4843 South Africa
4844 Kampala, Central Region, 7063, Uganda
4845 Paris, Île-de-France
4846 Bloem, Swartland Ward 12, Swartland Local Municipality, West Coast District Municipality, Western Cape, South Africa
4847 Bloemfontein, Mangaung, Free State
4848 null
4849 null
4850 Warszawa, mazowieckie, RP
4851 Nigeria
4852 Emperor, Irvine Groves, El Camino Real, Irvine, Orange County, California, 92604, United States of America
4853 Manchester, Lancashire, England
4854 ڪراچي Karachi, Karāchi District, سنڌ, ‏پاکستان‎
4855 Everywhere Branch
4856 UK
4857 Everywhere Branch
4858 Portarlington, County Laois, Leinster, R32 HR67, Ireland
4859 Swinton, Manchester, Lancashire, England
4860 Magyarország
4861 Valsad, Gujarat
4862 County Wicklow, Leinster, Ireland
4863 Canary Wharf, London, England
4864 Nigeria
4865 Kisumu
4866 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
4867 England
4868 New Zealand/Aotearoa
4869 Norton, Chegutu, Mashonaland West
4870 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4871 Åsgård, Tromsø, Troms
4872 My house, Giurgiu, 87043, România
4873 Ghana
4874 null
4875 Benin City, Oredo, Edo
4876 null
4877 Dashţūţ, Banī Suwayf
4878 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
4879 New Accounts Era
4880 Parit Buntar, PRK, 14300, Malaysia
4881 null
4882 null
4883 Manchester, Lancashire, England
4884 Awka, Awka South, Anambra, Nigeria
4885 Portsmouth, Hampshire, England
4886 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
4887 Indonesia
4888 kd, Old Trail to Mt Arayat North Peak, Baluga Village, Pampanga, Central Luzon, 2011, Philippines
4889 Nairobi
4890 Nigeria
4891 Dakar
4892 Jakarta, Gambir, Jakarta Pusat, Daerah Khusus Ibukota Jakarta, 10110, Indonesia
4893 Outlook, Saskatchewan
4894 Manchester, Greater Manchester, North West England, England, UK
4895 Cape Town, Western Cape
4896 null
4897 Napoli
4898 Cape Town, City of Cape Town, Western Cape, 8001, South Africa
4899 Bophuthatswana
4900 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4901 Newcastle, Tyne and Wear, England
4902 Ghana
4903 A Capital
4904 null
4905 Manchester, Lancashire, England
4906 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
4907 Bristol, Avon, England
4908 Senai, Muar, Johor, 81400, Malaysia
4909 Accra, Accra Metropolis, Greater Accra
4910 Bolton, Greater Manchester, North West England, England, UK
4911 Águilas, Murcia, Región de Murcia
4912 İstanbul, Fatih, İstanbul, Marmara Bölgesi, 34126, Türkiye
4913 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
4914 null
4915 null
4916 Rochdale, Greater Manchester, North West England, England, UK
4917 Manchester, Lancashire, England
4918 null
4919 Lagos, Lagos Island, Lagos
4920 België - Belgique - Belgien
4921 Australia
4922 Liverpool, North West England, England, UK
4923 UK
4924 Swimming Pool, Jawaharlal Nehru Road, Cantonments, Accra, Accra Metropolitan, Greater Accra Region, NE2 8AH, Ghana
4925 68397
4926 Planet Earth, SR 14, Edinburg, Edinburg Township, Portage County, Ohio, United States of America
4927 India
4928 Newcastle upon Tyne, Tyne and Wear, North East England, England, UK
4929 Newcastle upon Tyne, Tyne and Wear, England
4930 Bloemfontein, Mangaung Metropolitan Municipality, Free State, 9301, South Africa
4931 Don Mueang, Bangkok
4932 Diff, EN 206, Fafe, Braga, Ave, Norte, 4820-121, Portugal
4933 Bulawayo
4934 SHED, 52-12-20, PAKA, Rajamahendravaram, East Godavari, Andhra Pradesh, 533105, India
4935 Ireland
4936 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
4937 Pakistan
4938 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
4939 Made in South
4940 Manchester, Greater Manchester, North West England, England, UK
4941 UK
4942 Diepkloof, Soweto, City of Johannesburg Metropolitan Municipality, Gauteng, 1864, South Africa
4943 Northampton, Northamptonshire, England
4944 Cave, RM, LAZ, Italia
4945 Moston, Manchester, Lancashire, England
4946 null
4947 East
4948 Up North, Pashan-Bavdhan Road, Anupam Park, Chandani Chauk, Pune, Maharashtra, 411001, India
4949 null
4950 Atlanta, Fulton County, Georgia, United States of America
4951 Johannesburg, Gauteng
4952 Sao Paulo, Rahue Alto, Osorno, Provincia de Osorno, X Región de Los Lagos, 5301065, Chile
4953 Abuja, Abuja Municipal, Federal Capital Territory
4954 null
4955 Perak, Temerloh, Pahang
4956 PRK, Malaysia
4957 UK
4958 Edo, Nigeria
4959 Cloud 9
4960 null
4961 Sharjah
4962 Gloucester, Gloucestershire, South West England, England, UK
4963 Nairobi
4964 Salford, Greater Manchester, North West England, England, UK
4965 null
4966 TGG, 10, De Diepte, Noord, 's-Hertogenbosch, Noord-Brabant, Nederland, 5233 XR, Nederland
4967 Colchester, Essex, England
4968 null
4969 Mira Loma, California
4970 Manchester, Greater Manchester, North West England, England, UK
4971 Atlanta, Georgia
4972 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
4973 Nigeria
4974 Sydney, NSW, Australia
4975 DTH World
4976 Calabar, Calabar Municipal, Cross River, Nigeria
4977 Kuils River, Cape Town, Western Cape
4978 Home & Away, The Crescent, Holme Head, Currock, Carlisle, Cumbria, North West England, England, CA1 1QN, UK
4979 Nairobi
4980 254, Stadtbezirk 10 Moosach, München, OB, Bayern, 80992, Deutschland
4981 England
4982 Abuja, Municipal Area Council, Federal Capital Territory, 900001, Nigeria
4983 Takoradi, Sekondi-Takoradi, Shama Ahanta East Metropolitan, Western
4984 null
4985 Theatre of Dreams
4986 ‏پاکستان‎
4987 Bangkok, Phra Nakhon, Bangkok
4988 Jericho, New York, 11753, United States of America
4989 Old Trafford, Manchester, Lancashire, England
4990 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
4991 Cheshunt, Waltham Cross, Hertfordshire, England
4992 Warszawa, mazowieckie, RP
4993 United Kingdom
4994 Bortianor, Ga South, Greater Accra Region, AA10 4AA, Ghana
4995 Manchester, Lancashire, England
4996 null
4997 Kuala Lumpur, Pusat Bandaraya, Kuala Lumpur, Wilayah Persekutuan
4998 Kuala Lumpur, Jalan Pekeliling KLIA, Kampung Baru Lanjut, Salak, Sepang, Selangor, 71760, Malaysia
4999 Christ

In [ ]:
for i in range(10000,20000):
    
    try:
        # configure this based upon your input CSV file
        place, lat, lng = geocode(MUp['location'][i],i)
        if(place!='null'):
            MUp['geocode'][i]=place
            MUp['lat'][i]=lat
            MUp['lon'][i]=lng
            MUp['co'][i]=True
        print(i,place)
    except BaseException as e:
        print(e)

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

10000 Lagos, Lagos Island, Lagos
10001 null
10002 BC
10003 null
10004 Yemen
10005 Manhattan Beach, Duval County, Florida, 32227, United States of America
10006 BC
10007 null
10008 Worldwide
10009 Manchester, Greater Manchester, North West England, England, UK
10010 null
10011 null
10012 Moncton, New Brunswick
10013 Vila da Penha, Zona Norte do Rio de Janeiro, Rio de Janeiro, Microrregião Rio de Janeiro, Região Metropolitana do Rio de Janeiro, RJ, Região Sudeste, Brasil
10014 null
10015 Manchester, UK
10016 UT
10017 Miami, Miami-Dade County, Florida, United States of America
10018 null
10019 Indonesia
10020 Singapore
10021 Jamaica
10022 null
10023 null
10024 United Kingdom
10025 Nigeria
10026 null
10027 null
10028 Toronto, Ontario
10029 รังสิต, อำเภอธัญบุรี, จังหวัดปทุมธานี, 12130, ประเทศไทย
10030 null
10031 Johannesburg, South Africa
10032 Manchester, Lancashire, England
10033 London, Greater London, England, UK
10034 null
10035 null
10036 Memphis, Tennessee
10037 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
10038 null
10039 US-62, United States
10040 Calabar
10041 null
10042 null
10043 null
10044 Nigeria
10045 null
10046 null
10047 null
10048 Sydney, New South Wales
10049 MUFC Ticketing and Membership Services, Bridgewater Canal Towpath, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0SZ, UK
10050 null
10051 null
10052 Norwich, Norfolk, England
10053 null
10054 null
10055 null
10056 United States
10057 London, Greater London, England, UK
10058 null
10059 Cape Town, South Africa
10060 Sir Matt Busby
10061 null
10062 null
10063 Rock Springs, WY 82901, USA
10064 Karachi, Karāchi District, Sindh
10065 United States of America
10066 null
10067 Jakarta, Indonesia
10068 Mankunia, Vansda, Navsari, Gujarat
10069 London, Greater London, England, UK
10070 null
10071 Algeria
10072 null
10073 The World, Pennsylvania Avenue Northwest, Penn Quarter, Washington, District of Columbia, 20004, United States of America
10074 null
10075 15532 SW Pacific Hwy #304, Tigard, OR 97224, USA
10076 United Kingdom
10077 Atlanta, Fulton County, Georgia, United States of America
10078 null
10079 Manchester, UK
10080 Penzance, Cornwall, England
10081 London, Greater London, England, UK
10082 Old, Thornhill, BC
10083 Manchester, UK
10084 Manchester, Lancashire, England
10085 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10086 BC
10087 Perak, Malaysia
10088 null
10089 Manchester, Greater Manchester, North West England, England, UK
10090 null
10091 Galway, Ireland
10092 Lagos, Lagos Island, Lagos
10093 Nigeria
10094 BC
10095 null
10096 Ghana
10097 Newcastle upon Tyne, Tyne and Wear, North East England, England, UK
10098 null
10099 1301 E Broward Blvd #330, Fort Lauderdale, FL 33301, USA
10100 London, England
10101 null
10102 null
10103 null
10104 Hale, Altrincham, Cheshire, England
10105 null
10106 null
10107 Accra, Ghana
10108 null
10109 Kuala Lumpur, Gorontalo, Indonesia
10110 null
10111 2455 NE Interstate 410 Loop #150, San Antonio, TX 78217, USA
10112 England
10113 Everything Everywhere, Chadwick Street, Steander, Hunslet, Leeds, Yorkshire and the Humber, England, LS9 8NB, UK
10114 null
10115 Essex, UK
10116 Greater Manchester, England
10117 Nigeria
10118 null
10119 null
10120 null
10121 Manchester, Greater Manchester, North West England, England, UK
10122 null
10123 null
10124 Temple, Texas
10125 Sthlm, Stockholm, Landskapet Uppland, Stockholms län, Svealand, 11129, Sverige
10126 null
10127 Earth, TX 79031, USA
10128 United Kingdom
10129 UK
10130 null
10131 Manchester, UK
10132 London, England
10133 Manchester, Greater Manchester, North West England, England, UK
10134 null
10135 United Kingdom
10136 England, Naledi, Dr Ruth Segomotsi Mompati, North West
10137 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
10138 null
10139 null
10140 Bath, Avon, England
10141 Salford, Greater Manchester, North West England, England, UK
10142 null
10143 United Kingdom
10144 Your Local
10145 Down Over There Avenue, Wickenburg, Maricopa County, Arizona, AZ 85390, United States of America
10146 null
10147 null
10148 Zamfara
10149 Oslo, 26, Norge
10150 null
10151 null
10152 Benin City, Oredo, Edo
10153 Manchester, Greater Manchester, North West England, England, UK
10154 null
10155 null
10156 null
10157 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10158 null
10159 Kidderminster, UK
10160 Kidderminster, Worcestershire, England
10161 Ho, Volta Region, Ghana
10162 null
10163 Indonesia
10164 Garden
10165 England, UK
10166 null
10167 null
10168 Made, Central Java
10169 Manchester, Greater Manchester, North West England, England, UK
10170 null
10171 2020 Broadway, New York, NY 10023, USA
10172 United Kingdom
10173 Manchester, Greater Manchester, North West England, England, UK
10174 null
10175 null
10176 New York
10177 Manchester, Greater Manchester, North West England, England, UK
10178 Manchester Lane, Nanaimo, BC
10179 null
10180 Earth, Texas
10181 null
10182 Lago St, Kelowna, BC
10183 Liverpool, NY, USA
10184 Manchester, Lancashire, England
10185 Colombia, Siete de Agosto, Barrios Unidos, Bogotá, Bogotá Distrito Capital, 111021, Colombia
10186 Lago St, Kelowna, BC
10187 null
10188 ON
10189 Nigeria
10190 Chelsea Rd, Courtenay, BC
10191 Rawang, Selangor, Malaysia
10192 Ikoyi
10193 Southend-on-Sea, East of England, England, UK
10194 BC
10195 London, UK
10196 Kano
10197 null
10198 BC
10199 Manchester, UK
10200 Ldn
10201 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10202 null
10203 Hall Only, Flower St, Woodbury, Exeter EX5 1LX, UK
10204 Littleborough, Lancashire, England
10205 Manchester, Greater Manchester, North West England, England, UK
10206 null
10207 null
10208 Bracknell, Berkshire, England
10209 Great Britain, Richmondshire, North Yorkshire, Yorkshire and the Humber, England, UK
10210 null
10211 Botswana
10212 Abuja, Abuja Municipal, Federal Capital Territory
10213 Manchester, Greater Manchester, North West England, England, UK
10214 null
10215 Salford, UK
10216 Zamfara
10217 null
10218 null
10219 null
10220 London, England
10221 Nigeria Road, Charlton, Greenwich, London, Greater London, England, SE7 7BS, UK
10222 null
10223 Zamfara, Nigeria
10224 Manchester, Lancashire, England
10225 Manchester, Greater Manchester, North West England, England, UK
10226 null
10227 London, UK
10228 United Kingdom
10229 St. Albert, Alberta, T8N 5C9, Canada
10230 null
10231 null
10232 Asankrangwa
10233 Chelsea, Royal Borough of Kensington and Chelsea, London, Greater London, England, SW3 5EE, UK
10234 null
10235 United Kingdom
10236 Ghana
10237 null
10238 null
10239 South Jakarta, South Jakarta City, Jakarta, Indonesia
10240 Accra, Accra Metropolis, Greater Accra
10241 Nairobi, Kenya
10242 null
10243 351 S Studio Dr, Lake Buena Vista, FL 32830, USA
10244 Kaduna, Kaduna North, Kaduna
10245 Viamão, Microrregião de Porto Alegre, Região Metropolitana de Porto Alegre, Mesorregião Metropolitana de Porto Alegre, RS, Região Sul, Brasil
10246 null
10247 null
10248 Don, Pak Thong Chai, Nakhon Ratchasima
10249 Manchester, Greater Manchester, North West England, England, UK
10250 null
10251 Lagos, Nigeria
10252 Sokoto
10253 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10254 null
10255 null
10256 35498
10257 Heaven, Villiers Street, St Clement Danes, Covent Garden, City of Westminster, London, Greater London, England, WC2N 6NG, UK
10258 null
10259 Abuja, Nigeria
10260 Kilimanjaro
10261 Scotland, UK
10262 null
10263 Manchester, UK
10264 Durban, eThekwini, Kwazulu Natal
10265 Worldwide, Crescent Road, Crumpsall, Manchester, Greater Manchester, North West England, England, M8 5EJ, UK
10266 null
10267 Ibadan, Nigeria
10268 Sheffield, South Yorkshire, England
10269 Lagos, Lagos Island, Lagos, 71510, Nigeria
10270 null
10271 null
10272 02152
10273 England, UK
10274 null
10275 Port Harcourt International Airport (PHC), Kaicon Express Way, Port Harcourt, Nigeria
10276 Kampala
10277 Lahore, Rue du Faubourg Saint-Denis, St-Vincent-de-Paul, 10e, Paris, Île-de-France, France métropolitaine, 75010, France
10278 null
10279 null
10280 Lagos, Lagos Island, Lagos

10281 Manchester, Greater Manchester, North West England, England, UK
10282 null
10283 null
10284 Glasgow, Lanarkshire, Scotland
10285 Gloucestershire, South West England, England, UK
10286 null
10287 Accra, Ghana
10288 England
10289 Stoke-on-Trent, West Midlands, England, ST1 4NP, UK
10290 Uganda Passage, Whaletown, BC
10291 null
10292 Old Trafford, Manchester, Lancashire, England
10293 London, Greater London, England, UK
10294 2, Burns Lake, BC
10295 null
10296 Ife, Ife Central, Osun
10297 Johannesburg, City of Johannesburg Metropolitan Municipality, Gauteng, 2001, South Africa
10298 City Pk, Kelowna, BC
10299 null
10300 UK
10301 null
10302 BC
10303 Blessington, Co. Wicklow, Ireland
10304 Johannesburg, Gauteng
10305 Luton, East of England, England, UK
10306 8 Mule Deer Dr, Osoyoos, BC
10307 null
10308 Luton, Bedfordshire, England
10309 null
10310 England Rd, Courtenay, BC
10311 null
10312 Việt Nam
10313 La Antigua, Veracruz de Ignacio de la Llave, México
10314 Keta Restarea, Sayward, BC
10315 Viamão, RS, Brazil
10316 Nigeria
10317 South Dublin, County Dublin, Leinster, Ireland
10318 null
10319 Manchester, UK
10320 United Kingdom
10321 Ituporanga, Microrregião de Ituporanga, Mesorregião do Vale do Itajaí, SC, Região Sul, Brasil
10322 null
10323 null
10324 Lagos, Lagos Island, Lagos
10325 Mombasa, Kenya
10326 null
10327 null
10328 United States
10329 Manchester, Greater Manchester, North West England, England, UK
10330 null
10331 null
10332 Milwaukee, Wisconsin
10333 Lagos, Lagos Island, Lagos, 71510, Nigeria
10334 null
10335 Lagos, Nigeria
10336 Lagos, Lagos Island, Lagos
10337 World, Governor Drive, University City, San Diego, San Diego County, California, 92037, United States of America
10338 null
10339 null
10340 Earth, Texas
10341 Manchester, Greater Manchester, North West England, England, UK
10342 null
10343 Nigeria
10344 Le Défends, Jouques, Bouches-du-Rhône, Provence-Alpes-Côte d'Azur
10345 Orlando, Orange County, Florida, United States of America
10346 null
10347 Lagos, Nigeria
10348 Sénégal
10349 The West Coast, Old Strathcona, Edmonton, Alberta, T6E3Z4, Canada
10350 null
10351 6700 McKennon Blvd, Fort Smith, AR 72903, USA
10352 Tema, Tema Municipal, Greater Accra
10353 Montclair, Remembrance Drive, Fort York, Old Toronto, Toronto, Ontario, M6K 3C3, Canada
10354 null
10355 Enugu, Nigeria
10356 Everywhere Branch
10357 Essex, East of England, England, UK
10358 null
10359 Manchester, UK
10360 Pouilly-sur-Loire, Nièvre, Bourgogne-Franche-Comté
10361 Manchester, Greater Manchester, North West England, England, UK
10362 null
10363 null
10364 Manchester, Lancashire, England
10365 null
10366 null
10367 Kapsabet, Kenya
10368 Minna, Chanchaga, Niger
10369 Paradise, Clark County, Nevada, United States of America
10370 null
10371 222 E Main St, North Manchester, IN 46962, USA
10372 Adelaide, South Australia
10373 Lancashire, New Castle County, Delaware, 19803:19809:19810, United States of America
10374 null
10375 Lagos, Nigeria
10376 Wales
10377 Manchester, Greater Manchester, North West England, England, UK
10378 null
10379 United Kingdom
10380 Lowe St, Glenavy, Waitaki Bridge, 9493
10381 NYC, New York, United States of America
10382 null
10383 null
10384 Belfast, County Antrim, Northern Ireland
10385 The Hills, NSW, Australia
10386 null
10387 Nairobi, Kenya
10388 Delhi, Connaught Place, New Delhi, Delhi
10389 Manchester, Greater Manchester, North West England, England, UK
10390 null
10391 Leeds, AL, USA
10392 Worldwide
10393 null
10394 null
10395 null
10396 Финска
10397 Sthlm, Stockholm, Landskapet Uppland, Stockholms län, Svealand, 11129, Sverige
10398 null
10399 null
10400 Glasgow, Lanarkshire, Scotland
10401 Indianapolis, Marion County, Indiana, 46204, United States of America
10402 null
10403 Cambuslang, Glasgow G72, UK
10404 Manchester, Lancashire, England
10405 London, Greater London, England, UK
10406 null
10407 null
10408 Lagos, Lagos Island, Lagos
10409 London, Greater London, England, UK
10410 BC
10411 Tokyo, Japan
10412 Treasure Island, Florida
10413 World Citizen Drive, Hampden, Carnbee, Tobago, Trinidad and Tobago
10414 Cloud Way, West Kelowna, BC
10415 Cambuslang, Glasgow G72, UK
10416 Karachi, Karāchi District, Sindh
10417 Nairobi, Kenya
10418 BC
10419 2455 NE Interstate 410 Loop #150, San Antonio, TX 78217, USA
10420 Nigeria
10421 London, Greater London, England, UK
10422 of Rd, Atlin, BC
10423 Manchester, UK
10424 Bristol, Avon, England
10425 Mombasa, Kenya
10426 Cornwall Rd, Shawnigan Lake, BC
10427 null
10428 Bradford, West Yorkshire, England
10429 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10430 Hamber Provincial Park, BC
10431 null
10432 02152
10433 England, UK
10434 England Rd, Courtenay, BC
10435 Manchester, UK
10436 Old Trafford, Manchester, Lancashire, England
10437 England, UK
10438 null
10439 null
10440 ME
10441 Zimbabwe
10442 null
10443 Indonesia
10444 England
10445 MY ROOM, Service Road, Maduravoyal, Corporation of Chennai, Thiruvallur district, Tamil Nadu, 600037, India
10446 null
10447 null
10448 Manchester, Lancashire, England
10449 London, Greater London, England, UK
10450 null
10451 null
10452 Birmingham, West Midlands, England
10453 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10454 null
10455 Manchester, UK
10456 Virginia
10457 Zimbabwe
10458 null
10459 Liverpool, NY, USA
10460 Cardiff, South Glamorgan, Wales
10461 Ireland
10462 null
10463 300 N McLean Blvd, Wichita, KS 67203, USA
10464 Nairobi
10465 Ripponden, Yorkshire and the Humber, England, HX6, UK
10466 null
10467 Santiago, Santiago Metropolitan Region, Chile
10468 Cairo
10469 Birmingham, West Midlands Combined Authority, West Midlands, England, UK
10470 null
10471 null
10472 Chennai, Tamil Nadu
10473 Accra, Accra Metropolitan, Greater Accra Region, 0302, Ghana
10474 null
10475 null
10476 South Valley, New Mexico
10477 Sentrum, Oslo, 0161, Norge
10478 null
10479 null
10480 Lambeth, London, Ontario
10481 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
10482 null
10483 Glasgow, UK
10484 Scotland
10485 Glasgow City, Scotland, UK
10486 null
10487 Bournemouth, UK
10488 High, Arkansas
10489 Heywood, Greater Manchester, North West England, England, OL10 4PD, UK
10490 null
10491 1866 Sheffield Rd, Chesterfield S41 8NZ, UK
10492 Manchester, Lancashire, England
10493 null
10494 null
10495 Derby, UK
10496 Old Trafford, Manchester, Lancashire, England
10497 Ghana
10498 null
10499 Paradise, NV, USA
10500 In My Room
10501 Old Trafford, Munich Tunnel, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0RA, UK
10502 null
10503 null
10504 Carrington Lane, Urmston, Manchester, Lancashire, England, M33 5
10505 Manchester, Greater Manchester, North West England, England, UK
10506 null
10507 Lagos, Nigeria
10508 Bangladesh
10509 Christianssand Brygghus, 9, Tollbodgata, Gravane, Kvadraturen, Kristiansand, Vest-Agder, 4611, Norge
10510 null
10511 Preston, UK
10512 South Africa
10513 Pacific Quay, Yorkhill, Stobcross, Glasgow City, Scotland, G46, UK
10514 null
10515 null
10516 null
10517 Shower, Newport, Nenagh, County Tipperary, Munster, Ireland
10518 null
10519 Old Trafford Cres, Uitzicht, Cape Town, 7570, South Africa
10520 Park Your Brain
10521 Dublin, County Dublin, Leinster, Ireland
10522 null
10523 null
10524 Lagos, Lagos Island, Lagos
10525 Dublin, County Dublin, Leinster, Ireland
10526 The Rd, Spallumcheen, BC
10527 null
10528 Accra, Accra Metropolis, Greater Accra
10529 Manchester, Greater Manchester, North West England, England, UK
10530 BC
10531 Nairobi, Kenya
10532 Manchester, Lancashire, England
10533 null
10534 BC
10535 Old Trafford Cres, Uitzicht, Cape Town, 7570, South Africa
10536 London, England
10537 BXL, Brussel-Hoofdstad - Bruxelles-Capitale, Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest, 1000, België - Belgique - Belgien
10538 Kenya Pl, Saanich, BC
10539 England, UK
10540 Nyali, Mombasa
10541 London, Greater London, England, UK
10542 Fin Island, BC
10543 null
10544 Richards Bay, uThungulu, Kwazulu Natal
10545 Manchester, Greater Manchester, North West England, England, UK
10546 Atlin, BC
10547 null
10548 Rihāna, Himachal Pradesh

10549 Sir Matt Busby Way, Wharfside, Trafford, Greater Manchester, North West England, England, M16 0SZ, UK
10550 Mund Rd, Tatalrose, BC
10551 South Staffs, Lynn Ln, Shenstone, Lichfield WS14 0ED, UK
10552 Nevada
10553 Antigua, San Antonio, Bexar County, Texas, 78259, United States of America
10554 null
10555 Alcala de Henares, Madrid, Spain
10556 Old Trafford, Manchester, Lancashire, England
10557 South Wales, Erie County, New York, 14139, United States of America
10558 null
10559 null
10560 Lagos, Lagos Island, Lagos
10561 Nairobi, Kenya
10562 null
10563 Chennai, Tamil Nadu, India
10564 Stoke-on-Trent, Staffordshire, England
10565 Gotham, Richland County, Wisconsin, 53540, United States of America
10566 null
10567 null
10568 Chennai, Tamil Nadu
10569 null
10570 null
10571 null
10572 Manchester, Lancashire, England
10573 Sukodono, Jawa Timur, Indonesia
10574 null
10575 Lagos, Nigeria
10576 Ghana
10577 Manchester, Greater Manchester, North West England, England, UK
10578 null
10579 null
10580 Kumasi, Kumasi Metropolitan, Ashanti
10581 Ends, Davenport Road, Yorkville, Old Toronto, Toronto, Ontario, M5R 2H6, Canada
10582 null
10583 2455 NE Interstate 410 Loop #150, San Antonio, TX 78217, USA
10584 England
10585 South Shields, Tyne and Wear, North East England, England, NE33 1NF, UK
10586 null
10587 Lebanon
10588 Insha Allah
10589 null
10590 null
10591 null
10592 Durban, eThekwini, Kwazulu Natal
10593 Lagos, Lagos Island, Lagos, 71510, Nigeria
10594 null
10595 Manchester, UK
10596 Ibrox, Glasgow, Lanarkshire, Scotland
10597 null
10598 null
10599 United Arab Emirates
10600 Manchester, Lancashire, England
10601 Україна
10602 null
10603 Islamabad, Pakistan
10604 United Kingdom
10605 Manchester, Greater Manchester, North West England, England, UK
10606 null
10607 null
10608 East Leon, New York
10609 Việt Nam
10610 null
10611 Manchester, UK
10612 Lagos, Lagos Island, Lagos
10613 Temecula, Riverside County, California, United States of America
10614 null
10615 Dublin, Ireland
10616 Indonesia
10617 null
10618 null
10619 null
10620 United Kingdom
10621 Juventus Stadium, Via Druento, Le Vallette, Circoscrizione 5, Torino, TO, PIE, 10144, Italia
10622 null
10623 United States
10624 Kapsabet, Nandi
10625 Nairobi, Kenya
10626 null
10627 Trondheim, Norway
10628 Lorong Johor, Kawasan 13, Pelabuhan Klang, Klang, 42000, Selangor
10629 Midlands Province, Zimbabwe
10630 null
10631 null
10632 Lagos, Lagos Island, Lagos
10633 Lagos, Lagos Island, Lagos, 71510, Nigeria
10634 null
10635 null
10636 United Kingdom
10637 Lagos, Lagos Island, Lagos, 71510, Nigeria
10638 null
10639 null
10640 United Kingdom
10641 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10642 null
10643 null
10644 Bracknell, Berkshire, England
10645 فیصل آباد, Faisalābād District, پنجاب, 38000, ‏پاکستان‎
10646 null
10647 null
10648 Riyadh
10649 Manchester, Greater Manchester, North West England, England, UK
10650 BC
10651 Dar es Salaam, Tanzania
10652 Kaboja, Kampala, Busiro, Wakiso
10653 Port Harcourt, Port-Harcourt, Rivers, 500211, Nigeria
10654 null
10655 null
10656 England
10657 null
10658 null
10659 null
10660 null
10661 null
10662 null
10663 null
10664 Nigeria
10665 Nigeria
10666 null
10667 null
10668 Kampala
10669 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10670 null
10671 null
10672 Italia
10673 Camden Town, London, Greater London, England, NW1 9PJ, UK
10674 null
10675 null
10676 Emirates Stadium
10677 null
10678 null
10679 England, UK
10680 Liverpool St, Pittsburgh, Pennsylvania, 15233
10681 United Kingdom, دبي, دبي‎, الإمارات العربيّة المتّحدة
10682 null
10683 Corby, UK
10684 Swindon, Wiltshire, England
10685 Paris, Île-de-France, France métropolitaine, France
10686 null
10687 null
10688 null
10689 null
10690 null
10691 null
10692 null
10693 London, Greater London, England, UK
10694 null
10695 null
10696 null
10697 null
10698 null
10699 null
10700 null
10701 null
10702 null
10703 null
10704 null
10705 null
10706 null
10707 null
10708 null
10709 null
10710 null
10711 null
10712 null
10713 null
10714 null
10715 null
10716 null
10717 null
10718 Lago St, Kelowna, BC
10719 null
10720 null
10721 null
10722 null
10723 null
10724 null
10725 null
10726 null
10727 null
10728 null
10729 null
10730 null

In [13]:
U1=MUn.iloc[0:5000]
U1.to_csv("MUn-1.csv",index=False,sep=',')

In [7]:
print(arcgis.geocode('manchester'))

Manchester, Lancashire, England

In [8]:
print(nominatim.geocode('manchester'))

Manchester, Greater Manchester, North West England, England, UK

In [9]:
print(googlev3.geocode('manchester'))

Manchester, UK

In [10]:
print(databc.geocode('manchester'))

Manchester Lane, Nanaimo, BC

In [18]:
MUp1=pd.read_csv(open('MUp-1.csv','rU'),sep=',')
MCp1=pd.read_csv(open('MCp-1.csv','rU'),sep=',')

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 'U' mode is deprecated
  """Entry point for launching an IPython kernel.
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 'U' mode is deprecated

In [18]:
U=MUn[MUn['co']==True]
U=U.reset_index(drop=True)

U.shape

(4555, 14)

In [25]:
U=MUp1[MUp1['co']==True]
C=MCp1[MCp1['co']==True]

In [47]:
C=C.reset_index(drop=True)
C

,user,text,location,followers_count,friends_count,created_at,token_stop_lower,sentiment,geocode,lat,lon,co
0,Artezgroup,@MobikeUK Are you closed today? Can’t find a s...,Bolton,1206.0,630,Tue Nov 14 12:45:24 +0000 2017,"['@mobikeuk', 'closed', 'today', 'find', 'sing...",0.009524,"Bolton, Lancashire, England",53.578450,-2.426670,True
1,TabDesk,Liverpool vs. Manchester City English Premier ...,London,30.0,24,Tue Nov 14 12:45:01 +0000 2017,"['liverpool', 'vs', 'manchester', 'city', 'eng...",0.090909,"London, Greater London, England, UK",51.507322,-0.127647,True
2,UnitedJord,RT @RedReveal: Sports Direct | More Manchester...,"England, United Kingdom",162.0,109,Tue Nov 14 12:44:01 +0000 2017,"['@redreveal', 'sports', 'direct', 'manchester...",0.100000,"England, UK",52.355518,-1.174320,True
3,Nawtynigsy,RT @gmpolice: A few weeks ago @greatermcr laun...,Manchester,152.0,840,Tue Nov 14 12:42:29 +0000 2017,"['@gmpolice', 'weeks', 'ago', '@greatermcr', '...",0.452778,"Manchester, Lancashire, England",53.479590,-2.248740,True
4,s9tmt,RT @gmpolice: A few weeks ago @greatermcr laun...,manchester,4266.0,935,Tue Nov 14 12:41:56 +0000 2017,"['@gmpolice', 'weeks', 'ago', '@greatermcr', '...",0.452778,"Manchester, Greater Manchester, North West Eng...",53.479130,-2.244101,True
5,tallstew,RT @MundialMag: It's Manchester City and Wolve...,Altrincham,190.0,187,Tue Nov 14 12:36:59 +0000 2017,"['@mundialmag', ""it's"", 'manchester', 'city', ...",0.500000,"Altrincham, UK",53.386905,-2.348898,True
6,gmpolice,A few weeks ago @greatermcr launched the big c...,Greater Manchester,558652.0,600,Tue Nov 14 12:36:33 +0000 2017,"['weeks', 'ago', '@greatermcr', 'launched', 'b...",0.383333,"Greater Manchester, England",53.515148,-2.284242,True
7,BridgewaterConf,Unique Wedding Venue in Manchester city centre...,Manchester,1548.0,1870,Tue Nov 14 12:35:08 +0000 2017,"['unique', 'wedding', 'venue', 'manchester', '...",0.375000,"Manchester, Greater Manchester, North West Eng...",53.479130,-2.244101,True
8,koluwasegun_,RT @City_Watch: New York City FC have entered ...,"Lagos, Nigeria.",3117.0,2129,Tue Nov 14 12:32:30 +0000 2017,"['@city_watch', 'new', 'york', 'city', 'fc', '...",0.136364,"Lagos, Lagos Island, Lagos",6.454710,3.388760,True
9,ManCity_stall,Official MANCHESTER CITY F.C. Glassware\n\nhtt...,"Manchester, England",3101.0,1878,Tue Nov 14 12:31:07 +0000 2017,"['official', 'manchester', 'city', 'f', 'c', '...",0.200000,"Manchester, Greater Manchester, North West Eng...",53.479130,-2.244101,True
10,emelrizwani,When Premier League football clubs get their s...,"London, England",898.0,614,Tue Nov 14 12:30:26 +0000 2017,"['premier', 'league', 'football', 'clubs', 'ge...",0.159524,"London, UK",51.507351,-0.127758,True
11,BristolPCity,RT @aidanmccartney: Latest ticket update - the...,"Bristol, England",1830.0,175,Tue Nov 14 12:30:22 +0000 2017,"['@aidanmccartney', 'latest', 'ticket', 'updat...",0.225000,"Bristol, Avon, England",51.453790,-2.591680,True
12,BristolPost,RT @aidanmccartney: Latest ticket update - the...,"Bristol, UK",118562.0,736,Tue Nov 14 12:30:22 +0000 2017,"['@aidanmccartney', 'latest', 'ticket', 'updat...",0.225000,"Bristol, City of Bristol, South West England, ...",51.453802,-2.597298,True
13,ChelseaFC_MP,European football top 10 wage bills: PSG top B...,"London, England",445.0,62,Tue Nov 14 12:30:10 +0000 2017,"['european', 'football', 'top', '10', 'wage', ...",0.250000,"London, UK",51.507351,-0.127758,True
14,RMadrid_MP,European football top 10 wage bills: PSG top B...,"Madrid, Spain",129.0,70,Tue Nov 14 12:30:06 +0000 2017,"['european', 'football', 'top', '10', 'wage', ...",0.250000,"Madrid, Comunidad de Madrid",40.420280,-3.705770,True
15,therockparmar3,"RT @UltraAutistic: Javier Tebas: ""I'm sure PSG...","New York, USA",264.0,578,Tue Nov 14 12:29:55 +0000 2017,"['@ultraautistic', 'javier', 'tebas', ""i'm"", '...",0.250000,"NYC, New York, United States of America",40.730646,-73.986614,True
16,martin131166,@YesterdaysStars The city of Manchester should...,manchester,610.0,606,Tue Nov 14 12:29:14 +0000 2017,"['@yesterdaysstars', 'city', 'manchester', 'so...",0.400000,"Manchester, Lancashire, England",53.479590,-2.248740,True
17,AlIAhmeD12T,@21LVA My dream I watch a match for my team fr...,Sudan,277.0,3134,Tue Nov 14 12:29:14 +0000 2017,"['@21lva', 'dream', 'watch', 'match', 'team', ...",0.500000,السودان,14.584444,29.491769,True
18,BrownPhilip,@baeing @ndrlee @undertheraedar Middlesbrough ...,United Kingdom,780.0,775,Tue Nov 14 12:29:04 +0000 2017,"['@baeing', '@ndrlee', '@undertheraedar', 'mid...",0.050000,United Kingdom,53.408387,-1.969560,True
19,mcfcnewsapp,A Liverpool transfer swoop could hand Guardiol...,Etihad Stadium,295.0,128,Tue Nov 14 12:27:03 +0000 2017,"['liverpool', 'transfer', 'swoop', 'could', 'h...",0.136364,"Etihad Stadium, Joe Mercer Way, Beswick, Manch...",53.483158,-2.200534,True
20,PhilGreengbg,RT @City_Chief: Manchester City enjoyed a clea...,Where are you from...,1248.0,1906,Tue Nov 14 12:21:59 +0000 2017,"['@city_chief', 'manchester', 'city', 'enjoyed...",0.433333,Start Where You Are,-36.765210,144.277550,True
21,aidanmccartney,Latest ticket update - they won't be around fo...,"Coventry, England",2775.0,812,Tue Nov 14 12:21:28 +0000 2017,"['latest', 'ticket', 'update', ""won't"", 'aroun...",0.225000,"Coventry, UK",52.406822,-1.519693,True
22,uMAXitFootball,It's easy for young players to be chewed up an...,United Kingdom,15994.0,267,Tue Nov 14 12:20:43 +0000 2017,"[""it's"", 'easy', 'young', 'players', 'chewed',...",0.344444,United Kingdom,53.408387,-1.969560,True
23,bobskino,"RT @Jon_LeGossip: According to L'Equipe, promi...",Port Harcourt,1875.0,1480,Tue Nov 14 12:20:25 +0000 2017,"['@jon_legossip', 'according', ""l'equipe"", 'pr...",0.200000,"Port Harcourt, Port-Harcourt, Rivers, 500211, ...",4.767658,7.018853,True
24,TheDockyardMCUK,MAKE SOME NOISE MEDIA CITY! We’ve got a brand ...,MediaCityUK,4149.0,203,Tue Nov 14 12:19:41 +0000 2017,"['make', 'noise', 'media', 'city', 'got', 'bra...",0.136364,"The Greenhouse, 101-110 Broadway, Salford M50 ...",53.474092,-2.297598,True
25,SithokozoC,RT @SkySportsNews: ⚽️@ManCity's @DeBruyneKev h...,"Nseleni, South Africa",69.0,493,Tue Nov 14 12:19:13 +0000 2017,"['@skysportsnews', '⚽', '️', '@mancity', '@deb...",0.350000,"Nseleni, uThungulu, Kwazulu Natal",-28.663830,32.022060,True
26,CliffSinc,RT @BBCNWT: Nearly 6 months after the Manchest...,England,139.0,75,Tue Nov 14 12:19:04 +0000 2017,"['@bbcnwt', 'nearly', '6', 'months', 'manchest...",0.050000,"England, UK",52.795479,-0.540240,True
27,ultra_barcelona,European football top 10 wage bills: PSG top B...,"Barcelona, España",123.0,18,Tue Nov 14 12:18:07 +0000 2017,"['european', 'football', 'top', '10', 'wage', ...",0.250000,"Barcelona, Catalunya",41.385610,2.168720,True
28,nick1lewis1,RT @MundialMag: It's Manchester City and Wolve...,London,1201.0,189,Tue Nov 14 12:18:01 +0000 2017,"['@mundialmag', ""it's"", 'manchester', 'city', ...",0.500000,"London, Greater London, England, UK",51.507322,-0.127647,True
29,HeelLeClech,RT @GNews_Center: #Sport - Manchester City pai...,Lormont,2658.0,248,Tue Nov 14 12:17:10 +0000 2017,"['@gnews_center', '#sport', 'manchester', 'cit...",0.800000,"33310 Lormont, France",44.880163,-0.523108,True
...,...,...,...,...,...,...,...,...,...,...,...,...
8095,LewisGibson98,"RT @FootyAccums: Gerard Pique: ""My love for Ma...","Ayr, Scotland",623.0,945,Thu Nov 09 08:41:23 +0000 2017,"['@footyaccums', 'gerard', 'pique', 'love', 'm...",0.466667,"Ayr, Ayrshire, Scotland",55.442810,-4.629190,True
8096,GmAj21,"RT @indykaila: Gerard Pique: ""My love for Manc...",city of salford manchester 🐝,783.0,1224,Thu Nov 09 08:41:18 +0000 2017,"['@indykaila', 'gerard', 'pique', 'love', 'man...",0.466667,"Manchester Bolton & Bury Canal, Salford, Great...",53.479106,-2.260286,True
8097,Ahmedalassaf5,"RT @Devils_Latest: Gerard Pique: ""My love for ...",Riyadh,159.0,403,Thu Nov 09 08:40:52 +0000 2017,"['@devils_latest', 'gerard', 'pique', 'love', ...",0.466667,Riyadh,24.682160,46.687190,True
8098,NewRiverSport,"Since joining Manchester City, Sergio Aguero h...","White Hart Lane, London",503.0,1909,Thu Nov 09 08:40:49 +0000 2017,"['since', 'joining', 'manchester', 'city', 'se...",0.200000,"White Hart Lane, Penshurst Road, Tottenham, Lo...",51.604480,-0.070949,True
8099,juliusceasariga,"RT @WelBeast: Since joining Manchester City, S...",Kampala uganda,340.0,314,Thu Nov 09 08:39:43 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,Kampala,0.314260,32.575570,True
8100,sgarba9,"RT @ManUtdReport_: Gerard Pique: ""My love for ...","Abuja, Nigeria",98.0,90,Thu Nov 09 08:39:43 +0000 2017,"['@manutdreport_', 'gerard', 'pique', 'love', ...",0.466667,"Abuja, Municipal Area Council, Federal Capital...",9.064330,7.489297,True
8101,AlyBitou,"RT @FootyAccums: Gerard Pique: ""My love for Ma...",somalia tanzania,745.0,392,Thu Nov 09 08:39:28 +0000 2017,"['@footyaccums', 'gerard', 'pique', 'love', 'm...",0.466667,J. C. R Tanzania,-6.823740,39.277460,True
8102,liampeet,"RT @Devils_Latest: Gerard Pique: ""My love for ...","Ashton-under-Lyne, England",939.0,519,Thu Nov 09 08:38:57 +0000 2017,"['@devils_latest', 'gerard', 'pique', 'love', ...",0.466667,"Ashton-under-Lyne, Lancashire, England",53.489450,-2.088060,True
8103,comrie_stewart,"RT @ManUtdUpdates_: Gerard Pique: ""My love for...","Salford, England",64.0,241,Thu Nov 09 08:38:37 +0000 2017,"['@manutdupdates_', 'gerard', 'pique', 'love',...",0.466667,"Salford, Greater Manchester, North West Englan...",53.487746,-2.289192,True
8104,mR_mIAh_AFC,"RT @WelBeast: Since joining Manchester City, S...","Birmingham, England",324.0,758,Thu Nov 09 08:38:14 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"Birmingham, West Midlands, England",52.478670,-1.908480,True
8105,Tejasviverma,"RT @ManUtdUpdates_: Gerard Pique: ""My love for...","New Delhi, Delhi",272.0,835,Thu Nov 09 08:38:00 +0000 2017,"['@manutdupdates_', 'gerard', 'pique', 'love',...",0.466667,"New Delhi, Delhi, India",28.614179,77.202266,True
8106,ZainabbPatell,RT @Leicester_Merc: The city is outperforming ...,England,486.0,396,Thu Nov 09 08:37:53 +0000 2017,"['@leicester_merc', 'city', 'outperforming', '...",0.050000,England,52.592743,-1.458626,True
8107,JackInman_,"RT @FootyAccums: Gerard Pique: ""My love for Ma...",Warrington/Preston,1177.0,753,Thu Nov 09 08:37:48 +0000 2017,"['@footyaccums', 'gerard', 'pique', 'love', 'm...",0.466667,"Warrington Road, Sandymoor, Moore, Halton, Nor...",53.348493,-2.659612,True
8108,KraftyKnickers,RT @LCFC: Supporters can enjoy special matchda...,"England, United Kingdom",726.0,891,Thu Nov 09 08:37:21 +0000 2017,"['@lcfc', 'supporters', 'enjoy', 'special', 'm...",0.378571,England,52.592743,-1.458626,True
8109,si_bung,"RT @Pa_Ward1: Pique: ""My love for Manchester U...",Jakarta,292.0,593,Thu Nov 09 08:37:07 +0000 2017,"['@pa_ward1', 'pique', 'love', 'manchester', '...",0.466667,"Jakarta, Gambir, Jakarta Pusat, Daerah Khusus ...",-6.175394,106.827183,True
8110,JGephun,"RT @WelBeast: Since joining Manchester City, S...",Happy 😄,1694.0,873,Thu Nov 09 08:36:46 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"Happy, Kentucky",37.204840,-83.095920,True
8111,JamilaSinal,RT @Leicester_Merc: The city is outperforming ...,"England, United Kingdom",196.0,156,Thu Nov 09 08:36:43 +0000 2017,"['@leicester_merc', 'city', 'outperforming', '...",0.050000,"England, UK",52.795479,-0.540240,True
8112,JLsudds,"RT @WelBeast: Since joining Manchester City, S...",LONDON,248.0,234,Thu Nov 09 08:36:07 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"London, England",51.506420,-0.127210,True
8113,Blackfranchiz,"RT @WelBeast: Since joining Manchester City, S...",In yuh mind,854.0,1328,Thu Nov 09 08:35:30 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,Mind,13.999120,74.545100,True
8114,thetwiggy94,"RT @ManUtdUpdates_: Gerard Pique: ""My love for...","Wiltshire, England",421.0,784,Thu Nov 09 08:35:13 +0000 2017,"['@manutdupdates_', 'gerard', 'pique', 'love',...",0.466667,"Wiltshire, South West England, England, UK",51.250000,-1.916667,True
8115,Timehin_,"RT @WelBeast: Since joining Manchester City, S...",The Dreaming,1619.0,920,Thu Nov 09 08:34:54 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,Dreaming,-12.100540,-77.036660,True
8116,TheArcher94,"RT @indykaila: Gerard Pique: ""My love for Manc...",Liverpool city,142.0,154,Thu Nov 09 08:34:38 +0000 2017,"['@indykaila', 'gerard', 'pique', 'love', 'man...",0.466667,"Liverpool, North West England, England, UK",53.405472,-2.980539,True
8117,PedroJr03,"RT @WelBeast: Since joining Manchester City, S...",London,373.0,273,Thu Nov 09 08:34:17 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"London, England",51.506420,-0.127210,True
8118,aidenrooney7,"RT @WelBeast: Since joining Manchester City, S...","Coatbridge, Scotland",125.0,299,Thu Nov 09 08:33:48 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"Coatbridge, Lanarkshire, Scotland",55.859000,-4.036040,True
8119,instinct1234,"RT @indykaila: Gerard Pique: ""My love for Manc...",South africa,82.0,189,Thu Nov 09 08:33:47 +0000 2017,"['@indykaila', 'gerard', 'pique', 'love', 'man...",0.466667,South Africa,-28.816624,24.991639,True
8120,b4_the_party,"RT @WelBeast: Since joining Manchester City, S...","Kampala, Uganda",861.0,645,Thu Nov 09 08:33:04 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,Kampala,0.314260,32.575570,True
8121,nyc_messenger,Gabriel Jesus Reportedly Set to Be Offered New...,New York City,12546.0,345,Thu Nov 09 08:32:48 +0000 2017,"['gabriel', 'jesus', 'reportedly', 'set', 'off...",0.136364,"NYC, New York, United States of America",40.730646,-73.986614,True
8122,JohnsenMwangi,"Gerard Pique - ""My love for Manchester United ...","Waikiki Honolulu, Hawaii",2029.0,2840,Thu Nov 09 08:32:06 +0000 2017,"['gerard', 'pique', 'love', 'manchester', 'uni...",0.466667,"Waikīkī, Hawaii",21.282780,-157.829440,True
8123,Edemzo5,"RT @WelBeast: Since joining Manchester City, S...","Kampala, Uganda",97.0,152,Thu Nov 09 08:30:58 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,"Kampala, Central Region, 7063, Uganda",0.317714,32.581354,True
8124,Chizzydivaa,"RT @WelBeast: Since joining Manchester City, S...",Nigeria,4590.0,3439,Thu Nov 09 08:30:43 +0000 2017,"['@welbeast', 'since', 'joining', 'manchester'...",0.200000,Nigeria,9.593697,8.106778,True

In [2]:
with open("MUn5000.txt","w") as f:
    for i in range(len(U)):
        f.write("new google.maps.LatLng("+str(U['lat'][i])+','+str(U['lon'][i])+"),\n"+'          ')

NameError: name 'U' is not defined

In [3]:
MUn=pd.read_csv(open('MUn-geo.csv','rU'),sep=',')
MCn=pd.read_csv(open('MCn-geo.csv','rU'),sep=',')

/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 'U' mode is deprecated
  """Entry point for launching an IPython kernel.
/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning: 'U' mode is deprecated

In [4]:
MUn['token_stop_lower'][1]

"['@deadlinedaylive', 'antoine', 'griezemann', 'expected', 'snub', 'move', 'manchester', 'united', 'next', 'summer', 'says', 'would', 'dream', 'play', 'fo']"